import * as THREE from '../vendor/three.module.js';
import {loadCharacter} from './avatar-loader.js';
import {buildWorld} from './world.js';
import {Simulation,ECONOMY} from './simulation.js';
import {move,angleTowards,blocked,cameraDistance} from './controller.js';
import {createResidents} from './npcs.js';
import {regions,destinations} from './geography.js';
const $=id=>document.getElementById(id),fmt=n=>Math.round(n).toLocaleString('fr-FR')+' F';
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,alpha:false,powerPreference:'high-performance'});}catch{$('fallback').hidden=false;throw new Error('WebGL unavailable; legacy mode linked');}
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color('#accacc');scene.fog=new THREE.Fog('#accacc',45,115);
const camera=new THREE.PerspectiveCamera(52,1,.12,150);const sun=new THREE.DirectionalLight('#fff0ce',3.2);sun.position.set(-22,40,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-40;sun.shadow.camera.right=40;sun.shadow.camera.top=40;sun.shadow.camera.bottom=-40;sun.shadow.camera.far=100;sun.shadow.normalBias=.035;sun.shadow.bias=-.00015;scene.add(sun);
const hemi=new THREE.HemisphereLight('#d2e8ed','#b48a5f',2.0);scene.add(hemi);
const skyU={uTop:{value:new THREE.Color('#5598b7')},uHorizon:{value:new THREE.Color('#cde0db')},uSunDir:{value:sun.position.clone().normalize()}};
const sky=new THREE.Mesh(new THREE.SphereGeometry(120,24,12),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:skyU,vertexShader:'varying vec3 v;void main(){v=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 v;uniform vec3 uTop,uHorizon,uSunDir;void main(){float h=clamp(v.y,0.,1.);vec3 c=mix(uHorizon,uTop,pow(h,.6));float d=max(dot(normalize(v),uSunDir),0.);c+=vec3(.5,.4,.22)*(pow(d,600.)+pow(d,8.)*.2);gl_FragColor=vec4(c,1.);}'}));scene.add(sky);
const world=buildWorld(scene);
const sim=new Simulation();let player=await loadCharacter({shirt:'#e8dfc6',skin:'#633f2e'});scene.add(player.group);player.group.position.set(-7,.24,12);let residents=createResidents(scene);
const markerMat=new THREE.MeshBasicMaterial({color:'#e4b565',transparent:true,opacity:.72,depthWrite:false});const marker=new THREE.Mesh(new THREE.RingGeometry(.6,.68,32),markerMat);marker.rotation.x=-Math.PI/2;marker.position.y=.27;scene.add(marker);
const parcel=new THREE.Mesh(new THREE.BoxGeometry(.45,.4,.25),new THREE.MeshStandardMaterial({color:'#997b50',roughness:.9}));parcel.position.set(0,1.12,-.19);player.group.add(parcel);
let active=false,near=null,yaw=.2,pitch=.38,vx=0,vz=0,keys={},joy={x:0,y:0},running=false,drag=null,clock=0,accumulator=0,hudClock=0,saveClock=0,last=performance.now(),frames=[],muted=true,audio=null,lastSale=0,dialogSource=null;
const saveKey='togo-life:montagne:v2';let saved=null;try{saved=localStorage.getItem(saveKey);}catch{}if(saved){const probe=new Simulation();if(probe.load(saved))$('continueBtn').hidden=false;}
function save(){sim.state.position={x:player.group.position.x,z:player.group.position.z};try{localStorage.setItem(saveKey,JSON.stringify(sim.snapshot()));}catch{toast('Sauvegarde indisponible : le stockage de ce navigateur est bloqué.');}}
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4200);}
function tone(good=true){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(good?520:220,audio.currentTime);o.frequency.exponentialRampToValueAtTime(good?780:150,audio.currentTime+.13);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.22);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.23);}catch{}}
function open(id){resetInput();$(id).showModal();}function close(id){$(id).close();resetInput();}
function modal(){return !!document.querySelector('dialog[open]');}
function resetInput(){keys={};joy.x=joy.y=0;running=false;drag=null;$('stick').style.transform='';}
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>close(b.dataset.close);
for(const d of document.querySelectorAll('dialog'))d.addEventListener('close',resetInput);
$('start').addEventListener('cancel',e=>e.preventDefault());$('start').showModal();
let starting=false;
async function start(continuing=false){if(starting)return;starting=true;$('startBtn').disabled=true;$('continueBtn').disabled=true;try{if(continuing&&!sim.load(saved))return toast('La sauvegarde est invalide.');if(!continuing){sim.state.name=$('name').value.trim().slice(0,24)||'Kossi';sim.state.appearance={shirt:$('shirt').value,skin:$('skin').value};}scene.remove(player.group);player.group.remove(parcel);player.dispose();player=await loadCharacter(sim.state.appearance);scene.add(player.group);player.group.add(parcel);const p=sim.state.position;player.group.position.set(p.x,.24,p.z);if(blocked(p.x,p.z,world.colliders))player.group.position.set(-7,.24,12);active=true;close('start');save();updateHUD();toast(continuing?'Votre vie de quartier reprend.':'Ama vous attend au marché. Un colis peut financer votre première journée.');}finally{starting=false;$('startBtn').disabled=false;$('continueBtn').disabled=false;}}
$('startBtn').onclick=()=>start();$('continueBtn').onclick=()=>start(true);
function updateHUD(){const s=sim.state;$('money').textContent=fmt(s.money);$('clock').textContent='JOUR '+s.day+' · '+String(Math.floor(s.time)).padStart(2,'0')+':'+String(Math.floor(s.time%1*60)).padStart(2,'0');$('energy').value=s.energy;$('food').value=s.food;$('inventory').textContent=`Sac ${s.carried} / 12 · Stock ${s.stock} · Réputation ${s.rep}`;let title='Votre première opportunité',text='Rejoignez le marché. Prenez un colis ou lancez votre commerce.';if(s.contract){title='Un colis à livrer';text='Atelier de couture, au nord du marché. Récompense : 1 200 F avant demain soir.';}else if(s.carried){title='Transportez vos marchandises';text='Votre comptoir est au sud du marché. Ouvrez-le, puis déposez votre sac.';}else if(s.biz){title=s.sales?'Votre commerce prend vie':'Vos premiers clients';text=`${s.sales} produits vendus · recettes ${fmt(s.revenue)}. Prix : ${fmt(s.price)}. Réapprovisionnez ou aménagez votre logement.`;}else if(s.completed){title='De livreur à entrepreneur';text='Un kiosque coûte 9 000 F. Achetez votre stock au marché avant d’investir.';}$('goal').textContent=title;$('goalText').textContent=text;}
function nearest(){let best=null,bestD=Infinity;const pos=player.group.position;for(const p of world.places){const d=Math.hypot(pos.x-p.x,pos.z-p.z);if(d<p.radius&&d<bestD){best=p;bestD=d;}}for(const p of residents.people){const d=Math.hypot(pos.x-p.character.group.position.x,pos.z-p.character.group.position.z);if(d<1.6&&d<bestD){best={id:'npc',name:p.name,npc:p};bestD=d;}}return best;}
function act(type,data={}){const result=sim.act({type,...data},{location:dialogSource?.id,npcId:dialogSource?.npc?.id});tone(result.ok);toast(result.message);if(result.ok){save();updateHUD();close('action');}return result;}
function choice(text,cost,fn,disabled=false){const b=document.createElement('button');const label=document.createElement('span'),value=document.createElement('span');label.textContent=text;value.textContent=cost;b.append(label,value);b.disabled=disabled;b.onclick=fn;$('choices').append(b);}
function interact(){if(!active||modal())return;near=nearest();if(!near)return toast('Approchez-vous du marché, du comptoir ou d’un habitant.');dialogSource=near;$('actionTitle').textContent=near.name;$('actionTag').textContent='LA VIE DU QUARTIER';$('choices').replaceChildren();const s=sim.state;
 const description={market:'Produits locaux : 350 F à l’achat. Votre sac peut porter 12 unités. La vente se fait au comptoir, après transport.',kiosk:'Investissez, livrez votre stock puis choisissez un prix. Les clients arrivent selon le prix et les heures d’ouverture (7 h–21 h).',studio:'Cet atelier attend le colis confié au marché. Le paiement dépend de votre livraison réelle.',home:'Entrez dans la cour par la porte au sud. Le loyer quotidien est de 800 F. Aménager améliore votre récupération.',taxi:'La carte présente les destinations nationales. Ce quartier est le seul lieu jouable dans cette version.',npc:`${near.name} · ${near.npc?.job}. Les habitants suivent des parcours et des pauses de travail, d’achat et d’attente.`};$('actionText').textContent=description[near.id]||'';
 if(near.id==='market'){choice('Acheter 4 produits','−1 400 F',()=>act('buy',{quantity:4}),s.carried>8||s.money<1400);choice('Acheter 12 produits','−4 200 F',()=>act('buy',{quantity:12}),s.carried>0||s.money<4200);choice('Prendre un colis','Livraison +1 200 F',()=>act('contract'),!!s.contract||s.lastContractDay===s.day);choice('Manger au marché','−300 F',()=>act('meal'),s.food>90||s.money<300);}
 if(near.id==='kiosk'){choice('Ouvrir mon comptoir','−9 000 F',()=>act('invest'),s.biz||s.money<9000);choice('Déposer mon sac',`${s.carried} produits`,()=>act('deposit'),!s.biz||!s.carried);for(const price of [450,650,850,1100])choice('Prix '+fmt(price),price<=650?'Demande forte':price<1000?'Demande faible':'Aucun client',()=>act('price',{price}),!s.biz||s.price===price);}
 if(near.id==='studio')choice('Remettre le colis','+1 200 F',()=>act('deliver'),!s.contract);
 if(near.id==='home'){choice('Aménager mon logement','−4 000 F',()=>act('housing'),s.home||s.money<4000);choice('Régler le loyer',fmt(s.debt),()=>act('rent'),!s.debt||s.money<s.debt);choice('Se reposer','Temps +2 h',()=>act('rest'),!!s.debt);}
 if(near.id==='npc')choice('Discuter','Conseil du quartier',()=>act('talk'),s.conversations.includes(near.npc.id));
 if(near.id==='taxi')choice('Voir les destinations','Répertoire',()=>{close('action');open('map');});open('action');}
$('interactBtn').onclick=interact;$('mapBtn').onclick=()=>open('map');$('pauseBtn').onclick=()=>{save();open('pause');};$('muteBtn').onclick=()=>{muted=!muted;$('muteBtn').textContent='Son : '+(muted?'off':'on');tone();};
for(const [code,name]of Object.entries(regions)){const d=document.createElement('details'),summary=document.createElement('summary'),p=document.createElement('p');summary.textContent=name;p.textContent=destinations.filter(x=>x[1]===code).map(x=>x[0]).join(' · ');d.append(summary,p);$('regions').append(d);}
$('quality').onchange=()=>{renderer.shadowMap.enabled=$('quality').value==='high';renderer.setPixelRatio($('quality').value==='high'?Math.min(devicePixelRatio,1.5):1);resize();};
function resize(){const w=innerWidth,h=innerHeight;renderer.setPixelRatio($('quality').value==='low'?1:Math.min(devicePixelRatio,1.5));renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||modal())return;const k=e.key.toLowerCase();if(['w','a','s','d','z','q','arrowup','arrowdown','arrowleft','arrowright','shift',' '].includes(k)){e.preventDefault();keys[k]=true;}if(k==='e'&&!e.repeat)interact();if(k==='escape'){save();open('pause');}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('blur',()=>{resetInput();if(active&&!modal())open('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden){save();resetInput();if(active&&!modal())open('pause');}last=performance.now();});
const canvas=$('world');canvas.addEventListener('pointerdown',e=>{if(modal())return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;yaw-=(e.clientX-drag.x)*.006;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-drag.y)*.004,.12,.9);drag.x=e.clientX;drag.y=e.clientY;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(ev,()=>drag=null);
const joystick=$('joystick');let joyId=null;function stickMove(e){const r=joystick.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/40,y=(e.clientY-r.top-r.height/2)/40,l=Math.max(1,Math.hypot(x,y));joy.x=x/l;joy.y=y/l;$('stick').style.transform=`translate(${joy.x*35}px,${joy.y*35}px)`;}joystick.addEventListener('pointerdown',e=>{if(modal())return;joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);stickMove(e);});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joyId)stickMove(e);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(ev,()=>{joyId=null;joy.x=joy.y=0;$('stick').style.transform='';});$('runBtn').addEventListener('pointerdown',e=>{running=true;$('runBtn').setPointerCapture(e.pointerId);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('runBtn').addEventListener(ev,()=>running=false);
function shareCard(){const c=$('shareCard'),ctx=c.getContext('2d'),s=sim.state;ctx.fillStyle='#173d3d';ctx.fillRect(0,0,1080,1080);ctx.fillStyle='#dfb36a';ctx.fillRect(70,70,940,5);ctx.font='bold 40px Arial';ctx.fillText('TOGO LIFE',80,145);ctx.font='78px Georgia';ctx.fillStyle='#f4ead2';ctx.fillText('Une vie à Lomé.',80,315);ctx.font='30px Arial';ctx.fillStyle='#b8d3c7';ctx.fillText('Mon quartier. Mes décisions. Mon histoire.',80,390);ctx.font='bold 60px Arial';ctx.fillStyle='#dfb36a';ctx.fillText(s.sales+' produits vendus',80,570);ctx.fillText(s.completed+' livraisons réussies',80,670);ctx.font='36px Arial';ctx.fillStyle='#f4ead2';ctx.fillText(s.biz?'Mon premier commerce est ouvert.':'Mon aventure vient de commencer.',80,790);ctx.fillText('Jour '+s.day+' · Réputation '+s.rep,80,850);ctx.font='22px Arial';ctx.fillStyle='#b8d3c7';ctx.fillText('Simulation solo · monnaie virtuelle · aucun argent réel',80,970);const url=location.origin+location.pathname;$('whatsapp').href='https://wa.me/?text='+encodeURIComponent('TOGO LIFE : '+s.sales+' produits vendus et '+s.completed+' livraisons à Lomé. '+url);open('share');}
$('shareBtn').onclick=shareCard;$('downloadCard').onclick=()=>{$('shareCard').toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='togo-life-mon-quartier.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);});};$('nativeShare').onclick=async()=>{try{const blob=await new Promise(r=>$('shareCard').toBlob(r));const f=new File([blob],'togo-life.png',{type:'image/png'});if(navigator.canShare?.({files:[f]}))await navigator.share({files:[f],title:'TOGO LIFE',text:'Une vie à Lomé.'});else toast('Téléchargez la carte pour la publier sur Facebook ou TikTok.');}catch(e){if(e.name!=='AbortError')toast('Le partage est indisponible. Téléchargez la carte.');}};
let sunlightClock=0;function lighting(dt){sunlightClock+=dt;if(sunlightClock<1)return;sunlightClock=0;const t=sim.state.time,daylight=Math.max(.08,Math.sin((t-6)/12*Math.PI));sun.intensity=daylight*3.2;hemi.intensity=.35+daylight*1.65;skyU.uTop.value.set(daylight>.3?'#5598b7':'#102738');skyU.uHorizon.value.set(daylight>.3?'#cde0db':'#344f59');scene.fog.color.copy(skyU.uHorizon.value);sun.position.set(-25,8+daylight*34,25*Math.cos((t-6)/12*Math.PI));skyU.uSunDir.value.copy(sun.position).normalize();}
function step(dt){if(!active||modal()){vx*=.8;vz*=.8;player.update(dt,0);return;}const ix=(keys.d||keys.arrowright?1:0)-(keys.a||keys.q||keys.arrowleft?1:0)+joy.x,iz=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.z||keys.arrowup?1:0)+joy.y;const len=Math.max(1,Math.hypot(ix,iz)),speed=(keys.shift||running?4.5:2.1)*(sim.state.energy<15||sim.state.food<15?.65:1);const tx=(ix/len*Math.cos(yaw)+iz/len*Math.sin(yaw))*speed,tz=(-ix/len*Math.sin(yaw)+iz/len*Math.cos(yaw))*speed;const smooth=1-Math.exp(-dt*(ix||iz?12:16));vx+=(tx-vx)*smooth;vz+=(tz-vz)*smooth;const oldX=player.group.position.x,oldZ=player.group.position.z;move(player.group.position,vx,vz,dt,world.colliders,world.bounds);const actual=Math.hypot(player.group.position.x-oldX,player.group.position.z-oldZ)/dt;if(actual>.07)player.group.rotation.y=angleTowards(player.group.rotation.y,Math.atan2(vx,vz),dt);player.update(dt,actual);if(actual>3)sim.state.energy=Math.max(0,sim.state.energy-dt*.05);sim.tick(dt);if(sim.state.food<5)sim.state.energy=Math.max(0,sim.state.energy-dt*.08);residents.update(dt,sim.state.time);world.traffic.update(dt);lighting(dt);clock+=dt;saveClock+=dt;if(saveClock>8){saveClock=0;save();}if(sim.state.sales>lastSale){lastSale=sim.state.sales;toast('Un client a acheté au comptoir : +'+fmt(sim.state.price));tone();}parcel.visible=sim.state.carried>0||!!sim.state.contract;}
const desired=new THREE.Vector3(),focus=new THREE.Vector3();camera.position.set(-5,4.5,19);
function cameraUpdate(dt){const p=player.group.position;focus.set(p.x,1.2,p.z);const distance=innerWidth<600?7.6:7;desired.set(p.x+Math.sin(yaw)*distance*Math.cos(pitch),1.4+Math.sin(pitch)*distance,p.z+Math.cos(yaw)*distance*Math.cos(pitch));const hit=cameraDistance(focus,desired,world.colliders);if(hit<.96)desired.lerp(focus,1-hit);camera.position.lerp(desired,1-Math.exp(-dt*9));camera.lookAt(focus);}
let metrics={fps:0,frameMs:0,loadedMs:0};metrics.loadedMs=performance.now();
function frame(now){const raw=(now-last)/1000;last=now;const dt=Math.min(.1,Math.max(0,raw));accumulator+=dt;while(accumulator>=1/60){step(1/60);accumulator-=1/60;}cameraUpdate(dt);near=nearest();$('nearText').textContent=near?near.name:'Explorez le quartier';$('interactBtn').disabled=!near||!active;marker.visible=active&&!modal();const target=sim.state.contract?world.places.find(p=>p.id==='studio'):sim.state.carried?world.places.find(p=>p.id==='kiosk'):world.places.find(p=>p.id==='market');marker.position.x=target.x;marker.position.z=target.z;marker.scale.setScalar(1+Math.sin(now*.003)*.06);renderer.render(scene,camera);hudClock+=dt;if(hudClock>.3){hudClock=0;updateHUD();}if(raw>0&&raw<2){frames.push(raw);if(frames.length>180)frames.shift();metrics.frameMs=frames.reduce((a,b)=>a+b,0)/frames.length*1000;metrics.fps=1000/metrics.frameMs;}requestAnimationFrame(frame);}
// Diagnostics are enabled explicitly for QA; no state mutation hooks in normal play.
if(new URLSearchParams(location.search).has('qa')){window.__THREE_GAME_DIAGNOSTICS__={renderer:renderer.info,get state(){return {player:{x:player.group.position.x,z:player.group.position.z,speed:Math.hypot(vx,vz),animation:player.animationState},simulation:sim.snapshot(),npcs:residents.people.map(p=>({id:p.id,state:p.state,visits:p.visits,x:p.character.group.position.x,z:p.character.group.position.z})),performance:{...metrics},physics:{engine:'kinematic-circle-aabb',timestep:1/60,colliders:world.colliders.length},quality:$('quality').value};}};}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();resetInput();active=false;toast('Contexte graphique perdu. Rechargez pour reprendre votre sauvegarde.');save();});requestAnimationFrame(frame);
