'use strict';
const $=s=>document.querySelector(s), app=$('#app');
const KEY='ypp-prep-v2', SESSION='ypp-session-v2';
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
let state=read(KEY,{items:{},history:[],days:[]});
if(!state || typeof state.items!=='object'||!Array.isArray(state.history)||!Array.isArray(state.days))state={items:{},history:[],days:[]};
let session=null,timer=null,view='dashboard';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{$('#storageNotice').hidden=false}}
const save=()=>persist(KEY,state),saveSession=()=>persist(SESSION,session);
const pct=(a,b)=>b?Math.round(a/b*100):0;
function shuffle(xs){const a=[...xs];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const sourceLink=id=>SOURCES[id]?`<a href="${SOURCES[id].url}" target="_blank" rel="noopener noreferrer">${esc(SOURCES[id].title)} ↗</a>`:'';
function stats(d){const qs=QUESTIONS.filter(q=>!d||q.d===d),seen=qs.filter(q=>state.items[q.id]);return {seen:seen.length,correct:seen.filter(q=>state.items[q.id].ok).length,total:qs.length}}
function confidentErrors(){return QUESTIONS.filter(q=>state.items[q.id]&&!state.items[q.id].ok&&state.items[q.id].conf==='high').length}
function avgSeconds(){const rows=state.history.flatMap(h=>h.rows||[]).filter(r=>r.sel!==null&&Number.isFinite(r.seconds));return rows.length?Math.round(rows.reduce((a,r)=>a+r.seconds,0)/rows.length):0}
function actions(){return `<div class="actions"><button class="btn" onclick="startDiagnostic()">Faire mon diagnostic</button><button class="ghost" onclick="showView('exam')">Examen blanc · 45 min</button></div>`}
function dashboard(){const s=stats(),ce=confidentErrors(),avg=avgSeconds();app.innerHTML=`<div class="hero"><div><div class="eyebrow">YPP ASSESSMENT LAB · 23 SEPTEMBRE 2026</div><h2>Entraîne la décision, pas la mémorisation.</h2><p>160 questions · 40 par domaine · raisonnement non numérique · SJT alignés sur les valeurs et compétences publiées par la BAD · verbal reasoning à partir de passages.</p>${actions()}</div><div class="scorebox"><small>COUVERTURE</small><div class="score">${s.seen}<small>/${s.total}</small></div><small>${s.seen?pct(s.correct,s.seen)+' % de réponses justes':'Commence par le diagnostic'}<br>Indicateur d’entraînement, jamais une probabilité de sélection.</small></div></div><div class="notice"><b>Format confirmé par ton invitation :</b> QCM · 45 minutes · une seule session · aucune réponse rédigée · aucune composante mathématique · calculatrice non nécessaire · français ou anglais. Le nombre de questions et le barème officiels ne sont pas publiés.</div><div class="grid4">${Object.entries(DOMAINS).map(([d,label])=>{const x=stats(d);return `<button class="card module-button" onclick="startPractice('${d}')"><small>${label}</small><div class="num">${x.seen?pct(x.correct,x.seen)+'%':'—'}</div><small>${x.seen}/${x.total} questions explorées</small><p>Travailler ce domaine →</p></button>`}).join('')}</div><div class="section-title"><h2>Signaux à corriger</h2></div><div class="grid4"><div class="card"><small>Erreurs à forte confiance</small><div class="num">${ce}</div><p>Priorité : elles révèlent les fausses certitudes.</p></div><div class="card"><small>Temps moyen observé</small><div class="num">${avg?avg+' s':'—'}</div><p>Mesure descriptive, pas une cible officielle.</p></div><div class="card"><small>Examens blancs</small><div class="num">${state.history.filter(h=>h.exam).length}</div><p>Fais au moins deux simulations complètes.</p></div><div class="card"><small>Banque actuelle</small><div class="num">160</div><p>40 questions dans chacun des quatre domaines.</p></div></div><div class="panel"><h3>Mode intensif</h3><p>Alterne précision et pression temporelle : verbal reasoning, SJT puis sprint mixte. Les sprints cachent la correction jusqu’à la fin.</p><div class="actions"><button class="btn" onclick="startSpeedSprint()">Sprint mixte · 12 / 10 min</button><button class="ghost" onclick="startVerbalSprint()">Verbal · 9 / 8 min</button><button class="ghost" onclick="startSjtSprint()">SJT · 12 / 10 min</button></div></div><div class="section-title"><h2>Banque & veille</h2><span class="muted">Sources officielles vérifiées au 23 septembre 2026</span></div><div class="knowledge">${NEWS.slice(0,3).map(n=>`<article><small>${n.date}</small><h3>${n.title}</h3><p>${n.body}</p>${sourceLink(n.source)}</article>`).join('')}</div>`}
function learn(){app.innerHTML=`<p class="muted">${LESSONS.length} fiches de révision · français, avec lexique anglais. Clique sur une fiche, puis explique-la sans regarder.</p><div class="knowledge">${LESSONS.map(([title,d,body,source])=>`<details><summary>${esc(title)}</summary><p>${esc(body)}</p>${sourceLink(source)}<p><button class="ghost" onclick="startPractice('${d}')">M’entraîner sur ce domaine</button></p></details>`).join('')}</div>`}
function news(){app.innerHTML=`<div class="notice"><b>Veille éditoriale vérifiée au 23 septembre 2026.</b> Sélection de sources retrouvées, sans actualisation automatique ni garantie d’exhaustivité. Les pages complètes de certaines sources n’étaient pas accessibles lors de la vérification ; les fiches s’en tiennent aux informations visibles dans leurs résultats officiels. Consulte les publications nouvelles avant le test.</div><div class="knowledge">${NEWS.map(n=>`<article><span class="tag">${n.date}</span><h3>${n.title}</h3><p>${n.body}</p><div class="explain"><b>Question de réflexion</b><p>${n.prompt}</p></div><p>${sourceLink(n.source)}</p></article>`).join('')}</div><div class="panel"><h3>Actualités à vérifier avant le 28 septembre</h3><p>Privilégie les publications de la BAD sur les opérations, Mission 300, le FAD, les perspectives économiques et les pays africains. Pour chaque nouvelle publication, note date, instrument, cible, état d’avancement et lien avec les High 5.</p>${sourceLink('news')}</div>`}
function practiceHome(){app.innerHTML=`<div class="panel"><h2>Choisis ton entraînement</h2><p>Les modes libres donnent une correction immédiate. Les sprints et examens cachent la correction jusqu’au bilan pour préserver la pression de décision.</p>${actions()}<div class="actions"><button class="btn" onclick="startAdaptive()">Faiblesse prioritaire · 10</button><button class="ghost" onclick="startErrors()">Reprendre mes erreurs</button><button class="ghost" onclick="startOverconfidence()">Erreurs à forte confiance</button></div></div><div class="section-title"><h2>Simulations ciblées</h2></div><div class="grid4"><button class="card module-button" onclick="startVerbalSprint()"><h3>Verbal reasoning</h3><p>9 passages · Vrai / Faux / Impossible à conclure · 8 min.</p><span>Lancer →</span></button><button class="card module-button" onclick="startSjtSprint()"><h3>SJT sous pression</h3><p>12 situations professionnelles · 10 min · valeurs et compétences BAD.</p><span>Lancer →</span></button><button class="card module-button" onclick="startSpeedSprint()"><h3>Sprint mixte</h3><p>12 questions des quatre domaines · 10 min · correction à la fin.</p><span>Lancer →</span></button><button class="card module-button" onclick="showView('exam')"><h3>Simulation 45 min</h3><p>40 ou 60 questions · une seule session.</p><span>Configurer →</span></button></div><div class="section-title"><h2>Entraînement par domaine</h2></div><div class="grid4">${Object.entries(DOMAINS).map(([d,label])=>`<button class="card module-button" onclick="startPractice('${d}')"><h3>${label}</h3><p>${QUESTIONS.filter(q=>q.d===d).length} questions disponibles</p><span>Commencer →</span></button>`).join('')}</div>`}
function balanced(n){return shuffle(Object.keys(DOMAINS).flatMap(d=>shuffle(QUESTIONS.filter(q=>q.d===d)).slice(0,n)))}
function prioritize(qs){return shuffle(qs).sort((a,b)=>{const rank=q=>!state.items[q.id]?1:state.items[q.id].ok?2:0;return rank(a)-rank(b)})}
function startDiagnostic(){startQuiz(balanced(5),false,'Diagnostic')}
function startPractice(d){startQuiz(prioritize(QUESTIONS.filter(q=>q.d===d)).slice(0,10),false,DOMAINS[d])}
function startAdaptive(){const d=Object.keys(DOMAINS).sort((a,b)=>{const x=stats(a),y=stats(b);return (x.seen?x.correct/x.seen:0)-(y.seen?y.correct/y.seen:0)})[0];startPractice(d)}
function startErrors(){const qs=QUESTIONS.filter(q=>state.items[q.id]&&!state.items[q.id].ok);if(!qs.length){app.innerHTML='<div class="panel"><h2>Aucune erreur à reprendre</h2><p>Fais un diagnostic pour identifier tes points à travailler.</p>'+actions()+'</div>';return}startQuiz(shuffle(qs).slice(0,20),false,'Reprise des erreurs')}
function startOverconfidence(){const qs=QUESTIONS.filter(q=>state.items[q.id]&&!state.items[q.id].ok&&state.items[q.id].conf==='high');if(!qs.length){app.innerHTML='<div class="panel"><h2>Aucune erreur à forte confiance</h2><p>En entraînement libre, indique ton niveau de confiance après avoir choisi une réponse. Les erreurs sûres de toi apparaîtront ici.</p>'+actions()+'</div>';return}startQuiz(prioritize(qs).slice(0,20),false,'Fausses certitudes')}
function startVerbalSprint(){const qs=shuffle(QUESTIONS.filter(q=>q.kind==='verbal')).slice(0,9);startQuiz(qs,false,'Sprint verbal',{strict:true,durationMs:480000,kind:'sprint'})}
function startSjtSprint(){const qs=prioritize(QUESTIONS.filter(q=>q.d==='sjt')).slice(0,12);startQuiz(qs,false,'Sprint SJT',{strict:true,durationMs:600000,kind:'sprint'})}
function startSpeedSprint(){const qs=shuffle(Object.keys(DOMAINS).flatMap(d=>shuffle(QUESTIONS.filter(q=>q.d===d)).slice(0,3)));startQuiz(qs,false,'Sprint mixte',{strict:true,durationMs:600000,kind:'sprint'})}
function startExam(){const n=Number($('#examSize').value);startQuiz(balanced(n/4),true,'Examen blanc',{strict:true,durationMs:2700000,kind:'exam'})}
function startQuiz(qs,exam,title,opts={}){clearInterval(timer);const duration=opts.durationMs??(exam?2700000:null),strict=opts.strict??exam;session={id:Date.now()+'-'+Math.random(),qs:qs.map(q=>({ ...q,order:shuffle(q.o.map((_,i)=>i))})),answers:{},checked:{},flagged:{},times:{},confidence:{},i:0,exam:!!exam,strict:!!strict,kind:opts.kind||(exam?'exam':'practice'),title,start:Date.now(),deadline:duration?Date.now()+duration:null,entered:Date.now()};saveSession();renderQ();clock();}
function remaining(){return Math.max(0,Math.ceil((session.deadline-Date.now())/1000))}
function time(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function clock(){clearInterval(timer);if(!session?.deadline)return;timer=setInterval(()=>{if(!session)return;const s=remaining();if($('#timer'))$('#timer').textContent=time(s);if(!s)finish(true)},500)}
function track(){if(!session)return;session.times[session.i]=(session.times[session.i]||0)+Math.max(0,Date.now()-session.entered);session.entered=Date.now()}
function renderQ(){const q=session.qs[session.i],sel=session.answers[session.i],checked=session.checked[session.i],conf=session.confidence?.[session.i];$('#pageTitle').textContent=session.title;const timerHtml=session.deadline?`<b id="timer" role="timer">${time(remaining())}</b> · `:'';const stimulus=q.stimulus?`<div class="stimulus"><small>PASSAGE</small><p>${esc(q.stimulus)}</p></div>`:'';const confidence=(!session.strict&&sel!==undefined&&!checked)?`<div class="confidence"><small>Niveau de confiance — facultatif</small><div><button class="mini ${conf==='low'?'active':''}" onclick="setConfidence('low')">Faible</button><button class="mini ${conf==='medium'?'active':''}" onclick="setConfidence('medium')">Moyenne</button><button class="mini ${conf==='high'?'active':''}" onclick="setConfidence('high')">Forte</button></div></div>`:'';app.innerHTML=`<div class="quiz"><div class="qtop"><span>${DOMAINS[q.d]}${q.kind==='verbal'?' · VERBAL':''}</span><span>${timerHtml}Question ${session.i+1}/${session.qs.length}</span></div><progress max="${session.qs.length}" value="${Object.keys(session.answers).length}" aria-label="Questions renseignées"></progress>${stimulus}<h2 class="question" tabindex="-1">${esc(q.fr)}</h2>${q.table||''}<div class="options" role="group" aria-label="Réponses">${q.order.map((original,pos)=>`<button class="option ${sel===original?'selected':''} ${checked&&original===q.a?'correct':''} ${checked&&sel===original&&sel!==q.a?'wrong':''}" aria-pressed="${sel===original}" ${checked?'disabled':''} onclick="selectOpt(${original})">${String.fromCharCode(65+pos)}. ${esc(q.o[original])}</button>`).join('')}</div>${confidence}${checked?`<div class="explain" role="status"><b>${sel===q.a?'✓ Bonne réponse':'À revoir'}${conf?' · confiance '+({low:'faible',medium:'moyenne',high:'forte'})[conf]:''}</b><p>${esc(q.x)}</p>${sourceLink(q.source)}</div>`:''}<div class="quizfoot"><button class="ghost" ${session.i===0?'disabled':''} onclick="move(-1)">Précédente</button><button class="ghost" aria-pressed="${!!session.flagged[session.i]}" onclick="flag()">${session.flagged[session.i]?'★ Marquée':'☆ À revoir'}</button>${!session.strict&&!checked?`<button class="btn" ${sel===undefined?'disabled':''} onclick="checkAnswer()">Vérifier</button>`:`<button class="btn" onclick="move(1)">${session.i===session.qs.length-1?'Voir le bilan':'Suivante'}</button>`}</div><div class="question-map" aria-label="Navigation entre questions">${session.qs.map((_,i)=>`<button class="${i===session.i?'current':''} ${session.answers[i]!==undefined?'answered':''}" aria-label="Question ${i+1}${session.flagged[i]?', marquée':''}" onclick="jump(${i})">${i+1}${session.flagged[i]?'★':''}</button>`).join('')}</div><div class="quizfoot"><small>${session.strict?'Correction uniquement au bilan.':'Réponds, estime ta confiance, puis vérifie.'}</small><button class="ghost" onclick="finish(false)">Terminer la séance</button></div></div>`}
function selectOpt(i){if(session.checked[session.i])return;session.answers[session.i]=i;saveSession();renderQ()}
function setConfidence(level){if(!session||session.checked[session.i])return;session.confidence=session.confidence||{};session.confidence[session.i]=level;saveSession();renderQ()}
function checkAnswer(){if(session.answers[session.i]===undefined||session.checked[session.i])return;track();session.checked[session.i]=true;saveSession();renderQ()}
function flag(){session.flagged[session.i]=!session.flagged[session.i];saveSession();renderQ()}
function jump(i){track();session.i=i;saveSession();renderQ();$('.question').focus()}
function move(dir){if(dir===1&&session.i===session.qs.length-1){finish(false);return}jump(session.i+dir)}
function finish(auto=false){if(!session)return;if(!auto&&!confirm('Terminer cette séance ? Les questions sans réponse compteront comme incorrectes.'))return;track();clearInterval(timer);const total=session.qs.length,correct=session.qs.filter((q,i)=>session.answers[i]===q.a).length;const result={id:session.id,title:session.title,date:new Date().toISOString(),exam:session.kind==='exam',kind:session.kind||'practice',total,correct,elapsed:Math.round((Date.now()-session.start)/1000),rows:session.qs.map((q,i)=>({id:q.id,sel:session.answers[i]??null,seconds:Math.round((session.times[i]||0)/1000),conf:session.confidence?.[i]||null}))};if(!state.history.some(h=>h.id===result.id)){result.rows.forEach(r=>{if(r.sel!==null){const q=QUESTIONS.find(q=>q.id===r.id);state.items[r.id]={ok:r.sel===q.a,attempts:(state.items[r.id]?.attempts||0)+1,date:result.date,conf:r.conf||state.items[r.id]?.conf||null,seconds:r.seconds}}});state.history.unshift(result);state.history=state.history.slice(0,60);save()}session=null;saveSession();renderResult(result,auto)}
function renderResult(r,auto=false){$('#pageTitle').textContent='Bilan de séance';const cw=r.rows.filter(row=>{const q=QUESTIONS.find(q=>q.id===row.id);return q&&row.sel!==q.a&&row.conf==='high'}).length;const verbal=r.rows.filter(row=>QUESTIONS.find(q=>q.id===row.id)?.kind==='verbal');app.innerHTML=`<div class="panel result"><span class="tag">${auto?'TEMPS ÉCOULÉ':'SÉANCE TERMINÉE'}</span><div class="big-result">${pct(r.correct,r.total)}%</div><h2>${r.correct} / ${r.total} bonnes réponses</h2><p>${r.rows.filter(x=>x.sel===null).length} sans réponse · ${time(r.elapsed)} écoulées</p><p class="muted">Score d’entraînement uniquement. Le seuil et le barème officiels ne sont pas connus.</p><div class="actions"><button class="btn" onclick="startErrors()">Reprendre mes erreurs</button>${cw?`<button class="ghost" onclick="startOverconfidence()">${cw} erreur(s) à forte confiance</button>`:''}<button class="ghost" onclick="showView('progress')">Ma progression</button></div></div><div class="grid4">${Object.entries(DOMAINS).map(([d,label])=>{const rows=r.rows.filter(x=>QUESTIONS.find(q=>q.id===x.id)?.d===d);return `<div class="card"><small>${label}</small><div class="num">${rows.length?pct(rows.filter(x=>x.sel===QUESTIONS.find(q=>q.id===x.id).a).length,rows.length)+'%':'—'}</div></div>`}).join('')}</div>${verbal.length?`<div class="panel"><b>Verbal reasoning</b><p>${verbal.filter(x=>x.sel===QUESTIONS.find(q=>q.id===x.id).a).length}/${verbal.length} correct. Ici, la règle est stricte : n’ajoute aucune connaissance extérieure au passage.</p></div>`:''}<h2>Correction complète</h2>${r.rows.map((row,i)=>{const q=QUESTIONS.find(q=>q.id===row.id);if(!q)return '';return `<details ${row.sel!==q.a?'open':''}><summary>${i+1}. ${row.sel===q.a?'✓':'À revoir ·'} ${esc(q.fr)}</summary>${q.stimulus?`<div class="stimulus compact"><p>${esc(q.stimulus)}</p></div>`:''}<p><b>Ta réponse :</b> ${row.sel===null?'Sans réponse':esc(q.o[row.sel])}</p><p><b>Bonne réponse :</b> ${esc(q.o[q.a])}</p><p>${esc(q.x)}</p><small>${row.seconds} s${row.conf?' · confiance '+({low:'faible',medium:'moyenne',high:'forte'})[row.conf]:''} · </small>${sourceLink(q.source)}</details>`}).join('')}`}
function examHome(){app.innerHTML=`<div class="hero"><div><span class="tag">EXAMEN BLANC</span><h2>45 minutes. QCM. Aucun calcul.</h2><p>Corrections à la fin, questions et choix mélangés. Le raisonnement est non numérique. Le chronomètre continue si tu changes d’onglet ou actualises la page.</p><label for="examSize">Format d’entraînement</label><select id="examSize"><option value="40">40 questions · 10 par domaine</option><option value="60">60 questions · 15 par domaine</option></select><p>Répartition pédagogique, sans présumer du format officiel.</p><button class="btn gold" onclick="startExam()">Commencer · 45:00</button></div></div><div class="notice"><b>En conditions réelles :</b> ordinateur conseillé, connexion stable, calme et 45 minutes disponibles. Aucune calculatrice n’est nécessaire. Cette plateforme sert uniquement avant le test ; l’invitation interdit l’IA, les ressources externes et l’assistance pendant l’évaluation officielle.</div>`}
function progress(){const s=stats(),ce=confidentErrors(),avg=avgSeconds();app.innerHTML=`<div class="grid4"><div class="card"><small>Questions différentes</small><div class="num">${s.seen}/${s.total}</div></div><div class="card"><small>Dernières réponses justes</small><div class="num">${s.seen?pct(s.correct,s.seen)+'%':'—'}</div></div><div class="card"><small>Erreurs à forte confiance</small><div class="num">${ce}</div></div><div class="card"><small>Temps moyen observé</small><div class="num">${avg?avg+' s':'—'}</div></div></div><div class="panel"><h2>Historique des 60 dernières séances</h2>${state.history.length?state.history.map((h,i)=>`<button class="history-row" onclick="openResult(${i})"><span>${esc(h.title)} · ${new Date(h.date).toLocaleDateString('fr-FR')}</span><b>${h.correct}/${h.total} · ${pct(h.correct,h.total)} % →</b></button>`).join(''):'<p>Aucune séance terminée. Commence par un diagnostic.</p>'}<p><b>Priorité pédagogique :</b> corrige d’abord les erreurs à forte confiance, puis les erreurs répétées, puis la vitesse. Un bon score sur des questions mémorisées ne garantit pas la réussite.</p><div class="actions"><button class="btn" onclick="startOverconfidence()">Fausses certitudes</button><button class="ghost" onclick="startErrors()">Toutes les erreurs</button><button class="ghost" onclick="exportProgress()">Exporter</button></div><p><label class="ghost" for="importFile">Restaurer une progression</label> <input id="importFile" type="file" accept="application/json,.json" onchange="importProgress(this)"></p><small>Sauvegarde locale à ce navigateur. Aucun compte ni envoi de tes réponses à un serveur.</small></div>`}
function openResult(i){renderResult(state.history[i])}
function exportProgress(){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify({version:2,state},null,2)],{type:'application/json'}));a.href=u;a.download='ypp-progression.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function importProgress(input){try{const f=input.files[0];if(!f)return;if(f.size>2000000)throw Error();const x=JSON.parse(await f.text());if(x.version!==2||!x.state||!Array.isArray(x.state.history)||!Array.isArray(x.state.days)||typeof x.state.items!=='object')throw Error();const clean={items:{},history:[],days:x.state.days.filter(n=>Number.isInteger(n)&&n>=0&&n<12)};for(const q of QUESTIONS){const v=x.state.items[q.id];if(v&&typeof v.ok==='boolean')clean.items[q.id]={ok:v.ok,attempts:Math.max(1,Number(v.attempts)||1),date:String(v.date),conf:['low','medium','high'].includes(v.conf)?v.conf:null,seconds:Math.max(0,Number(v.seconds)||0)}}for(const h of x.state.history.slice(0,40)){if(!Array.isArray(h.rows)||!Number.isFinite(h.total)||!Number.isFinite(h.correct)||!Number.isFinite(h.elapsed)||isNaN(Date.parse(h.date)))throw Error();const rows=h.rows.filter(r=>{const q=QUESTIONS.find(q=>q.id===r.id);return q&&(r.sel===null||Number.isInteger(r.sel)&&r.sel>=0&&r.sel<q.o.length)}).map(r=>({id:r.id,sel:r.sel,seconds:Math.max(0,Number(r.seconds)||0),conf:['low','medium','high'].includes(r.conf)?r.conf:null}));if(rows.length!==h.total)throw Error();clean.history.push({id:String(h.id),title:String(h.title),date:h.date,exam:!!h.exam,kind:String(h.kind|| (h.exam?'exam':'practice')),total:rows.length,correct:rows.filter(r=>r.sel===QUESTIONS.find(q=>q.id===r.id).a).length,elapsed:Math.max(0,h.elapsed),rows})}if(!confirm('Remplacer la progression locale par ce fichier ?'))return;state=clean;save();progress()}catch{alert('Fichier de progression invalide. Choisis un export YPP version 2.')}}
function plan(){app.innerHTML=`<div class="panel"><h2>12 séances avant l’ouverture du test</h2><p>Prévois 60 à 90 minutes par séance ; garde 45 minutes pour chaque simulation, puis un temps séparé pour sa correction. Adapte le rythme au temps disponible.</p></div><div class="plan-list">${PLAN.map((text,i)=>`<label class="panel plan-item"><input type="checkbox" ${state.days.includes(i)?'checked':''} onchange="toggleDay(${i},this.checked)"><span><b>Séance ${i+1}</b><br>${text}</span></label>`).join('')}</div><div class="notice">Pour le test officiel : choisis une date dans la fenêtre du 28 septembre au 5 octobre, sans attendre le dernier soir. La BAD indique que le lien sera envoyé avant 8 h 00 GMT le lundi 28 septembre. Une fois lancé, le test de 45 minutes doit être terminé en une seule session. Au Togo, l’heure locale correspond à GMT.</div>`}
function toggleDay(i,on){state.days=on?[...new Set([...state.days,i])]:state.days.filter(d=>d!==i);save()}
function showView(v){if(session){if(session.strict){alert('Une simulation chronométrée est en cours. Termine-la pour ouvrir les autres sections.');return}if(!confirm('Quitter et enregistrer le bilan de cette séance ?'))return;finish(true)}view=v;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#pageTitle').textContent=({dashboard:'Tableau de bord',learn:'Fiches de révision',news:'Actualités & sources',practice:'Entraînement',exam:'Examen blanc',progress:'Ma progression',plan:'Programme personnel'})[v];({dashboard,learn,news,practice:practiceHome,exam:examHome,progress,plan})[v]();window.scrollTo(0,0)}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));
const pending=read(SESSION,null);
if(pending&&Array.isArray(pending.qs)&&pending.qs.length&&pending.qs.every(q=>QUESTIONS.some(x=>x.id===q.id)&&Array.isArray(q.order))&&pending.answers&&pending.checked&&pending.times&&pending.flagged){session=pending;session.confidence=session.confidence||{};session.strict=session.strict??!!session.exam;session.kind=session.kind||(session.exam?'exam':'practice');session.entered=Date.now();if(state.history.some(h=>h.id===session.id)){session=null;saveSession();dashboard()}else if(session.deadline&&remaining()===0)finish(true);else{renderQ();clock()}}else dashboard();
