'use strict';
function demanding(q){return q.lv>=4}
function familyOf(q){return q.family||String(q.id)}
function freshFirst(qs){return shuffle(qs).sort((a,b)=>Number(!!state.items[a.id])-Number(!!state.items[b.id]))}
function uniqueFamilies(qs,n){if(n<=0)return [];const used=new Set(),out=[];for(const q of qs){const f=familyOf(q);if(!used.has(f)){used.add(f);out.push(q);if(out.length===n)break}}return out}
function demandingExam(){const extra=shuffle(Object.keys(DOMAINS)).slice(0,2);return shuffle(Object.keys(DOMAINS).flatMap(d=>{const n=12+Number(extra.includes(d));if(d!=='reason')return uniqueFamilies(freshFirst(QUESTIONS.filter(q=>q.d===d&&demanding(q))),n);const parts=[['verbal',8],['logic',3],['detail',1]];const picked=parts.flatMap(([k,count])=>uniqueFamilies(freshFirst(QUESTIONS.filter(q=>q.d===d&&q.kind===k&&demanding(q))),count));return picked.concat(uniqueFamilies(freshFirst(QUESTIONS.filter(q=>q.d===d&&demanding(q)&&!picked.some(p=>familyOf(p)===familyOf(q)))),n-picked.length))}))}
function verbalSet(n=12){return uniqueFamilies(freshFirst(QUESTIONS.filter(q=>q.kind==='verbal'&&demanding(q))),n)}
function startVerbalCoach(){startQuiz(verbalSet(),false,'Atelier verbal · preuve et raisonnement',{guided:true,kind:'coach',preset:'guided'})}
function startVerbalChallenge(){startQuiz(verbalSet(),false,'Verbal exigeant · 12 minutes',{strict:true,forward:true,durationMs:720000,kind:'sprint',preset:'advanced'})}
function startTrap(trap){const qs=uniqueFamilies(freshFirst(QUESTIONS.filter(q=>q.kind==='verbal'&&demanding(q)&&q.trap===trap)),10);if(!qs.length)return;startQuiz(qs,false,TRAPS[trap],{guided:true,kind:'coach',preset:'guided'})}
function startWeakVerbal(){const errs={};for(const q of QUESTIONS.filter(q=>q.kind==='verbal'&&q.trap)){if(state.items[q.id]&&!state.items[q.id].ok)errs[q.trap]=(errs[q.trap]||0)+1}const trap=Object.keys(errs).sort((a,b)=>errs[b]-errs[a])[0];if(trap)startTrap(trap);else startVerbalCoach()}
function verbalHome(){const rows=state.history.flatMap(h=>h.rows||[]).filter(r=>QUESTIONS.find(q=>q.id===r.id)?.kind==='verbal');const matrix=Array.from({length:3},()=>[0,0,0]);rows.forEach(r=>{const q=QUESTIONS.find(q=>q.id===r.id);if(r.sel!==null&&r.sel>=0&&r.sel<3)matrix[q.a][r.sel]++});const labels=['Vrai','Faux','Impossible'];app.innerHTML=`<div class="hero wide"><div><span class="tag">ATELIER VERBAL</span><h2>Réponds avec une preuve.</h2><p>${QUESTIONS.filter(q=>q.kind==='verbal'&&demanding(q)).length} questions exigeantes sur ${new Set(QUESTIONS.filter(q=>q.kind==='verbal'&&demanding(q)).map(familyOf)).size} passages : conditions, négations, causalité, exceptions, chronologie et informations manquantes. Un seul item de chaque passage par séance pour limiter les réponses mémorisées.</p><div class="actions"><button class="btn" onclick="startVerbalCoach()">Apprendre · sans chrono</button><button class="ghost" onclick="startVerbalChallenge()">Tester · 12 questions / 12 min</button><button class="ghost" onclick="startWeakVerbal()">Travailler mon piège principal</button></div></div></div><div class="panel"><h3>La méthode en trois décisions</h3><div class="method-grid"><article><b>Vrai</b><p>Le texte impose l’affirmation. Repère la phrase ou la chaîne de déduction qui la prouve.</p></article><article><b>Faux</b><p>Le texte impose le contraire. Une contradiction ou un contre-exemple explicite suffit.</p></article><article><b>Impossible à conclure</b><p>Les deux scénarios restent compatibles avec le passage. Il manque un fait décisif.</p></article></div><p><b>Contrôle :</b> si tu ne peux pas citer la preuve, vérifie si tu as ajouté une connaissance, inversé une règle ou confondu une obligation et sa réalisation.</p></div><div class="panel"><h3>Mes confusions observées</h3><p>Lignes : réponse attendue. Colonnes : ta réponse. Les nombres cumulent tes tentatives verbales, sans les questions omises.</p><table><thead><tr><th>Attendue / choisie</th>${labels.map(l=>`<th>${l}</th>`).join('')}</tr></thead><tbody>${matrix.map((row,i)=>`<tr><th>${labels[i]}</th>${row.map((n,j)=>`<td class="${i===j?'matrix-good':'matrix-error'}">${n}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="section-title"><h2>Travailler un piège précis</h2></div><div class="knowledge">${[...new Set(QUESTIONS.filter(q=>q.kind==='verbal'&&demanding(q)).map(q=>q.trap))].map(k=>`<button class="card module-button" onclick="startTrap('${k}')"><h3>${TRAPS[k]}</h3><p>${QUESTIONS.find(q=>q.kind==='verbal'&&q.trap===k&&demanding(q)).rule}</p><span>Exercice guidé →</span></button>`).join('')}</div>`}
function coachControls(q,checked){if(!session.guided||!q.sentences)return '';const selected=session.proofs?.[session.i]||[];const hint=session.hints?.[session.i];return `<div class="proof-panel"><b>Quelle(s) phrase(s) justifie(nt) ta décision ?</b><p>Choisis les éléments nécessaires. Ce choix t’entraîne à distinguer la preuve de l’intuition ; il ne modifie pas le score du QCM.</p><div class="proof-options">${q.sentences.map((s,i)=>`<button class="proof-option ${selected.includes(i)?'selected':''}" aria-pressed="${selected.includes(i)}" ${checked?'disabled':''} onclick="selectProof(${i})"><b>Phrase ${i+1}</b> ${esc(s)}</button>`).join('')}<button class="proof-option ${selected.includes(-1)?'selected':''}" aria-pressed="${selected.includes(-1)}" ${checked?'disabled':''} onclick="selectProof(-1)">Je n’ai pas trouvé de phrase pertinente.</button></div>${!checked?`<button class="ghost" onclick="toggleHint()">${hint?'Masquer l’indice':'Afficher un indice'}</button>${hint?`<p class="hint">${esc(q.hint)}</p>`:''}`:''}</div>`}
function selectProof(i){if(!session?.guided||session.checked[session.i])return;const arr=session.proofs[session.i]||[];session.proofs[session.i]=arr.includes(i)?arr.filter(n=>n!==i):i===-1?[-1]:[...arr.filter(n=>n!==-1),i];saveSession();renderQ()}
function toggleHint(){if(!session?.guided||session.checked[session.i])return;session.hints[session.i]=!session.hints[session.i];saveSession();renderQ()}
function proofOkay(q,proof){return !!q.evidence&&q.evidence.every(i=>proof.includes(i))&&proof.every(i=>q.evidence.includes(i))}
function workedSolution(q,selected,proof){return `<div class="worked"><span class="tag">${esc(TRAPS[q.trap]||'Raisonnement')}</span>${q.rule?`<p><b>Règle :</b> ${esc(q.rule)}</p>`:''}${q.sentences?`<p><b>Indices clés :</b> ${q.evidence.map(i=>'phrase '+(i+1)).join(', ')}.</p>`:''}${proof?`<p><b>Preuve sélectionnée :</b> ${proofOkay(q,proof)?'Tu as isolé les éléments décisifs.':'Compare ta sélection aux indices clés : un élément décisif manque ou un élément superflu a été choisi.'}</p>`:''}${q.why?`<ul>${q.o.map((o,i)=>`<li><b>${esc(o)} :</b> ${esc(q.why[i])}</li>`).join('')}</ul>`:''}</div>`}
function demandingDashboard(){const first=state.history.filter(h=>h.exam&&h.status==='completed'&&h.familyNovelTotal>=35).slice(0,3);return `<div class="panel demanding-panel"><span class="tag">NOUVEAU · NIVEAU EXIGEANT</span><h3>Mesure-toi sur des questions inédites.</h3><p>${MASTERY_QUESTIONS.length+EXPERT_QUESTIONS.length} exercices exigeants, dont ${EXPERT_QUESTIONS.length} cas de niveau expert ajoutés. La difficulté est éditoriale, sans calibration sur les candidats réels. Les anciens scores restent dans ton historique.</p><div class="actions"><button class="btn" onclick="showView('lab')">Apprendre Vrai / Faux / Impossible</button><button class="ghost" onclick="showView('immersive')">Simulation immersive · 50 / 50</button></div><p><b>Repère personnel :</b> ${first.length?first.map(h=>h.familyNovelCorrect+'/'+h.familyNovelTotal+' familles inédites').join(' · '):'Pas encore de simulation exigeante terminée avec au moins 35 questions inédites.'}</p></div>`}
function noveltyPanel(r){if(!r.preset)return '';const names={expert:'Expert · 50 minutes','expert-overload':'Expert · 35 minutes','expert-guided':'Lecture dense guidée',pressure:'Défi par question',advanced:'Exigeant · 50 minutes',overload:'Surentraînement · 35 minutes',basic:'Fondamentaux',guided:'Apprentissage guidé'};const n=r.novelTotal??0;return `<div class="panel"><h3>${names[r.preset]||esc(r.preset)}</h3><p><b>Questions inédites au début :</b> ${n}/${r.total}${n?' · '+r.novelCorrect+'/'+n+' justes':''}. Les questions déjà vues peuvent bénéficier de la mémorisation.</p><p>La difficulté et la note décrivent cet entraînement ; elles ne donnent ni percentile ni rang de recrutement.</p>${r.rows.some(x=>x.proof)?`<p><b>Preuves complètes :</b> ${r.rows.filter(x=>x.proof&&proofOkay(QUESTIONS.find(q=>q.id===x.id),x.proof)).length}/${r.rows.filter(x=>x.proof).length}.</p>`:''}</div>`}
function difficultyResearch(){app.innerHTML=`<div class="panel"><h2>Pourquoi le niveau a changé</h2><p>La première banque contenait des distracteurs parfois extrêmes et des formulations simples. Un score élevé sur cette banque ne suffit pas à mesurer la robustesse sur un test inconnu.</p><p>Le niveau exigeant utilise les nouveaux cas : plusieurs contraintes, frontières entre groupes, étapes distinctes et alternatives professionnelles plus proches. Les simulations choisissent d’abord des questions non tentées et évitent plusieurs items du même passage.</p></div><div class="panel"><h3>Ce qui est confirmé</h3><p>Consignes de coordination vérifiées le 1er octobre, avec priorité au courriel du 30 septembre : 50 QCM, 50 minutes, toutes les réponses requises, aucun calcul, une seule session, caméra activée, français ou anglais, fenêtre du 1er au 8 octobre GMT.</p><p>L’invitation Bryq reçue le 1er octobre confirme aussi le questionnaire démographique obligatoire après « Voir les résultats », sans affichage du score officiel. Le message initial annonce connaissance BAD, développement africain, jugement situationnel et raisonnement. Il ne publie ni répartition, ni seuil, ni chronomètre par item.</p></div><div class="panel"><h3>Ce que disent les témoignages</h3><p>Deux récits publics consultés évoquent le manque de temps pour lire sur Bryq, et la confusion Faux / Impossible dans un autre test verbal. Ces récits sont anonymes, concernent d’autres employeurs et ne prouvent pas le contenu du test BAD 2026.</p><p>${sourceLink('bryqExperience')} · ${sourceLink('verbalExperience')}</p><p>Nous en tirons des axes d’entraînement : lecture précise, gestion du temps, raisonnement justifié et résistance à des options proches. Les durées des témoignages ne sont pas transférées à la simulation BAD.</p></div><div class="panel"><h3>Ce qui reste pédagogique</h3><p>La répartition des domaines, le niveau exigeant, les 35 minutes de surentraînement et le défi par question sont nos réglages. Aucun score ni classement officiel n’est prédit. Le guide Bryq sert de référence de familiarisation ; les instructions de ton épreuve priment.</p><p>${sourceLink('bryqGuide')} · ${sourceLink('bryqSamples')}</p></div>`}

function updateExamPreview(){const mins=$('#difficultyMode').value==='overload'?35:50;$('#formatHeading').textContent=`50 questions. ${mins} minutes. Aucun calcul.`;$('#examStart').textContent=`Commencer · ${mins}:00`}
