/* Editorial snapshot. Practice cases and figures are synthetic unless explicitly sourced. */
const SOURCES = {
  yppskills:{title:'BAD — YPP 2026 : compétences et conditions d’admissibilité',url:'https://www.afdb.org/en/careers/young-professionals-program-ypp/eligibility-requirements',date:'Mis à jour le 25 février 2026'},
  yppselection:{title:'BAD — YPP : processus de sélection',url:'https://www.afdb.org/fr/about-us/careers/young-professionals-program-ypp/selection-process',date:'Mis à jour le 8 novembre 2025'},
  values:{title:'BAD — Valeurs fondamentales',url:'https://www.afdb.org/fr/about-us/corporate-information/our-values',date:'Mis à jour le 18 mai 2024'},
  ethics:{title:'BAD — Bureau de l’éthique',url:'https://www.afdb.org/fr/about-us/organisational-structure/ethics-office',date:'Mis à jour le 11 septembre 2026'},
  aeo2026:{title:'BAD — Perspectives économiques en Afrique 2026',url:'https://www.afdb.org/fr/documents-publications/perspectives-economiques-en-afrique',date:'18 juin 2026'},
  adf17:{title:'BAD — Rapport FAD-17',url:'https://www.afdb.org/en/documents/adf-17-report-prosperous-inclusive-resilient-and-integrated-africa',date:'19 juin 2026'},
  regional2026:{title:'BAD — ADER 2026 : Intégrer l’Afrique',url:'https://www.afdb.org/en/annual-development-effectiveness-review-2026/chapter-4-integrate-africa-regional-integration-and-trade',date:'28 mai 2026'},
  missionsep:{title:'BAD — Mission 300 : Côte d’Ivoire et Pacte national de l’énergie',url:'https://www.afdb.org/fr/news-and-events/mission-300-la-banque-africaine-de-developpement-accompagne-la-cote-divoire-dans-lacceleration-de-la-mise-en-oeuvre-de-son-pacte-national-de-lenergie-96703',date:'14 septembre 2026'},
  mission50:{title:'BAD — Mission 300 : plus de 50 millions de personnes raccordées',url:'https://www.afdb.org/fr/news-and-events/press-releases/une-nouvelle-approche-permet-de-raccorder-plus-de-50-millions-de-personnes-lelectricite-en-afrique-dans-le-cadre-de-linitiative-mission-300-94527',date:'16 juin 2026'},
  koafecfinal:{title:'BAD — KOAFEC 2026 : IA, infrastructures numériques et investissement privé',url:'https://www.afdb.org/en/news-and-events/press-releases/koafec-2026-korea-african-development-bank-chart-new-phase-partnership-ai-digital-infrastructure-and-private-investment-96811',date:'16 septembre 2026'},
  aihub:{title:'BAD — Korea–Africa AI Hub',url:'https://www.afdb.org/en/news-and-events/press-releases/korea-african-development-bank-sign-deal-launch-joint-ai-hub-support-africa-96857',date:'17 septembre 2026'},
  afawa2026:{title:'BAD — AXIAN, AFAWA et We-Fi : finance numérique pour les entreprises dirigées par des femmes',url:'https://www.afdb.org/fr/news-and-events/press-releases/la-banque-africaine-de-developpement-et-axian-lancent-un-programme-de-finance-numerique-pour-soutenir-34-000-entreprises-dirigees-par-des-femmes-en-afrique-96454',date:'2 septembre 2026'},
  mali2026:{title:'BAD — Mali Country Focus Report 2026',url:'https://www.afdb.org/en/news-and-events/mali-has-powerful-levers-transform-its-economy-according-african-development-banks-2026-country-focus-report-96965',date:'22 septembre 2026'},

strategy:{title:'BAD — Stratégie décennale 2024–2033',url:'https://www.afdb.org/en/news-and-events/press-releases/african-development-bank-group-unveils-new-ten-year-strategy-2024-2033-71299',date:'29 mai 2024'},
mission:{title:'BAD — Mission 300',url:'https://www.afdb.org/en/topics-and-sectors/initiatives-and-partnerships/mission-300',date:'Initiative en cours'},
adf:{title:'Fonds africain de développement — présentation',url:'https://adf.afdb.org/',date:'Consulté le 23 septembre 2026'},
cardinal:{title:'BAD — Vision présidentielle : Four Cardinal Points',url:'https://cse.afdb.org/',date:'Vision présidentielle'},
annual:{title:'BAD — Assemblées annuelles 2026',url:'https://am.afdb.org/en',date:'Mai 2026'},
nafa:{title:'BAD — Discours au 39e sommet de l’Union africaine',url:'https://www.afdb.org/en/news-and-events/press-releases/39th-african-union-summit-his-first-speech-african-heads-state-dr-sidi-ould-tah-presents-nafa-strategic-lever-african-sovereignty-90892',date:'15 février 2026'},
news:{title:'BAD — Publications et actualités officielles',url:'https://www.afdb.org/en/news-and-events',date:'À consulter avant le test'},
};
const LESSONS = [
['La Banque et ses instruments','afdb',`Le Groupe de la BAD finance le développement économique durable et le progrès social des pays membres régionaux. Il comprend la Banque africaine de développement, le Fonds africain de développement (FAD / ADF) et le Fonds spécial du Nigeria (NTF). Ne le confonds pas avec une banque centrale : il ne fixe pas les taux directeurs nationaux. Le FAD est le guichet concessionnel du Groupe. Un financement concessionnel comporte des conditions plus favorables que celles du marché ; un don n’est pas un prêt. Une garantie partage certains risques ; elle ne supprime pas tous les risques. Une opération souveraine implique l’État ou sa garantie ; le financement non souverain peut notamment concerner une entreprise privée.`, 'adf'],
['Stratégie 2024–2033 et High 5','afdb',`La stratégie décennale 2024–2033 combine croissance verte inclusive et économies prospères et résilientes. Les High 5 sont les priorités opérationnelles : éclairer et alimenter l’Afrique en énergie ; nourrir l’Afrique ; industrialiser l’Afrique ; intégrer l’Afrique ; améliorer la qualité de vie des populations africaines. Associe énergie → électricité fiable ; agriculture → sécurité alimentaire ; industrie → transformation locale ; intégration → connexions transfrontalières ; qualité de vie → compétences et services essentiels. Les thèmes transversaux comprennent climat, genre, jeunesse, fragilité et gouvernance. Un projet peut contribuer à plusieurs priorités.`, 'strategy'],
['Nouvelle présidence et points cardinaux','afdb',`Les Assemblées annuelles de 2026 indiquent l’approbation, par les gouverneurs, de la vision des quatre points cardinaux présentée par Sidi Ould Tah. Il faut distinguer ce cadre présidentiel des cinq priorités opérationnelles High 5. Travaille la logique : mobiliser davantage de financements, renforcer l’architecture financière africaine, tirer parti du dividende démographique et relier infrastructures résilientes et valorisation locale des ressources. Ces formulations sont une synthèse pédagogique ; consulte la source pour les intitulés officiels.`, 'annual'],
['Mission 300 : objectif et résultats','afdb',`L’initiative vise à connecter 300 millions d’Africains à l’électricité d’ici 2030. C’est une cible, pas un résultat déjà atteint. Pour analyser une initiative énergétique, distingue capacité installée, raccordements, fiabilité, coût pour les ménages et usage productif. Une ligne électrique construite est un produit ; un accès effectif et fiable est un résultat. Dans un cas agricole, demande si l’électricité permet pompage, stockage frigorifique et transformation à un coût soutenable.`, 'mission'],
['Lire une actualité de développement','africa',`Utilise six questions : qui intervient ? Dans quel pays ? Quel problème ? Quel instrument ? Quel montant et quel statut ? Quel résultat attendu ? Approbation, signature, décaissement et résultat ne sont pas synonymes. Conserve date, unité, devise et source. Une prévision de croissance n’est pas une croissance observée. Un financement annoncé n’est pas de l’argent déjà dépensé. Ne mélange jamais objectif continental et contribution propre d’une institution.`, null],
['Croissance, dette et inclusion','africa',`La croissance réelle retire l’effet des prix ; le PIB réel par habitant tient aussi compte de la population. La croissance moyenne ne décrit pas la répartition des revenus. Une dette en devises expose au risque de change. Une réduction du déficit primaire ne garantit pas une baisse du ratio dette/PIB : intérêts, croissance et change comptent aussi. Pour apprécier un projet, examine viabilité, coût d’opportunité, emplois, accès des populations vulnérables et résilience aux chocs.`, null],
['Agriculture et transformation structurelle','africa',`Dans un projet fictif au Togo, une hausse de rendement ne suffit pas si pertes post-récolte, transport, eau et débouchés limitent le revenu. Examine toute la chaîne de valeur : intrants, production, stockage, transformation et marché, avec services financiers et assurance. L’intégration régionale peut agrandir le marché, mais les coûts logistiques et les barrières non tarifaires restent importants. Mesure le revenu net et la pérennité des emplois, pas uniquement les tonnes produites ou les personnes formées.`, null],
['Climat, genre et fragilité','africa',`L’adaptation réduit la vulnérabilité aux effets du climat ; l’atténuation réduit les émissions ou renforce les puits de carbone. Une irrigation solaire peut contribuer aux deux mais doit aussi maîtriser les prélèvements d’eau. Désagrège les résultats par sexe, âge et territoire. La participation de femmes à une réunion ne prouve pas leur pouvoir de décision. En contexte fragile, intègre sécurité, institutions locales, accès équitable et risques de tensions dans la conception et le suivi.`, null],
['Jugement professionnel : arbitrages','sjt',`Méthode pédagogique, sans prétendre au barème de la BAD : identifier les faits et l’urgence ; protéger personnes, confidentialité et intégrité ; vérifier les règles ; proposer une solution réalisable ; communiquer et escalader au niveau adapté. Ne dissimule pas un problème pour tenir un délai. N’escalade pas systématiquement au sommet un désaccord courant. En revanche, un danger immédiat ou un signalement sensible peut nécessiter le canal spécialisé. La réponse la plus longue n’est pas forcément la meilleure.`, null],
['Raisonnement sans calcul : règles et déductions','reason',`Le courriel de recrutement reçu le 23 septembre précise qu’il n’y a pas de composante mathématique et qu’aucune calculatrice n’est nécessaire. Entraîne donc surtout les relations logiques : condition nécessaire ou suffisante, contraposée, ordre des actions, cohérence entre prémisses, information manquante et conclusion réellement soutenue. Ne transforme pas une association en causalité et ne suppose pas la réciproque d’une règle.`, null],
['Logique et lecture critique','reason',`« Tous les A sont B » ne signifie pas que tous les B sont A. « Certains B sont C » ne suffit pas à conclure que certains A sont C. Une corrélation ne prouve pas une causalité. Pour une déduction, utilise uniquement les prémisses données. Dans un texte, distingue ce qui est explicitement établi, ce qui est contredit et ce qui reste impossible à déterminer. Repère aussi les généralisations excessives, les hypothèses implicites et les changements de sens entre une source et son résumé.`, null],
['Lexique français–anglais','afdb',`Décaissement = disbursement ; engagement = commitment ; financement concessionnel = concessional finance ; don = grant ; garantie = guarantee ; passation des marchés = procurement ; sauvegardes = safeguards ; redevabilité = accountability ; produit = output ; effet = outcome ; impact = impact ; valeur ajoutée = value addition ; intégration régionale = regional integration ; résilience = resilience ; conflit d’intérêts = conflict of interest.`, null],
];
const NEWS = [
{date:'Mai 2026',title:'Les gouverneurs approuvent la vision des quatre points cardinaux',body:'Les Assemblées annuelles 2026 présentent cette approbation. À retenir : distinguer orientation présidentielle, stratégie décennale et priorités opérationnelles.',source:'annual',prompt:'Pourquoi une orientation de mobilisation financière est-elle complémentaire aux High 5 ?'},
{date:'15 février 2026',title:'Architecture financière africaine au sommet de l’Union africaine',body:'La BAD présente le discours de Sidi Ould Tah au 39e sommet de l’UA autour de NAFA comme levier de souveraineté africaine. À retenir : relier ressources financières et investissements de développement, sans mémoriser un acronyme non vérifié.',source:'nafa',prompt:'Comment transformer une épargne disponible en financement productif de long terme ?'},
{date:'Initiative en cours',title:'Mission 300 : un objectif d’accès à l’électricité pour 2030',body:'La cible annoncée est de 300 millions d’Africains connectés à l’électricité d’ici 2030. Attention à la différence entre objectif et réalisation.',source:'mission',prompt:'Quels indicateurs permettraient de dépasser le simple décompte des raccordements ?'},
{date:'29 mai 2024 · cadre toujours pertinent',title:'La stratégie décennale 2024–2033',body:'Le cadre articule croissance verte inclusive et résilience. Révise comment les High 5 traduisent cette ambition dans les opérations.',source:'strategy',prompt:'À quelles priorités rattacher une unité de transformation agricole alimentée par énergie solaire ?'}
];
const PLAN = ['Diagnostic : 20 questions équilibrées. Pour chaque erreur, identifie si elle vient d’un manque de connaissance, d’une inférence abusive, d’un SJT trop extrême ou d’une lecture trop rapide.','Groupe BAD, FAD, instruments. 10 questions et rappel sans notes.','Stratégie 2024–2033 et High 5. Relier 5 projets aux priorités.','Présidence, points cardinaux et fiches d’actualité. Ouvrir les sources.','Croissance, dette, commerce régional. 10 questions.','Agriculture, climat, genre et fragilité. Expliquer les arbitrages.','Jugement situationnel : valeurs BAD, intégrité, confidentialité, conflit d’intérêts et proportionnalité.','Jugement situationnel : collaboration et priorisation.','Raisonnement : déductions, conditions, séquences et contradictions.','Raisonnement verbal : Vrai / Faux / Impossible à conclure, sans connaissance extérieure.','Examen blanc 45 min. Revoir erreurs et questions lentes.','Deuxième examen blanc. Révision légère, matériel et connexion.'];
SOURCES.crisis={title:'BAD · communiqué du 8 septembre 2026 — énergie et engrais',url:'https://afdb.africa-newsroom.com/press/african-development-bank-group-launches-up-to-usd-51-billion-response-plan-to-offset-energy-and-fertilizer-shocks-in-african-countries?lang=en',date:'8 septembre 2026'};
SOURCES.axian={title:'BAD · communiqué du 2 septembre 2026 — AXIAN, AFAWA et We-Fi',url:'https://afdb.africa-newsroom.com/press/african-development-bank-and-axian-launch-digital-finance-programme-to-support-34000-womenled-businesses-in-africa?lang=en',date:'2 septembre 2026'};
SOURCES.koafec={title:'BAD · communiqué du 3 septembre 2026 — KOAFEC',url:'https://afdb.africa-newsroom.com/press/korea-and-africa-chart-new-course-on-artificial-intelligence-ai-and-digital-infrastructure-at-20th-anniversary-of-koreaafrica-economic-cooperation-koafec?lang=en',date:'3 septembre 2026'};
SOURCES.sir={title:'BAD · communiqué du 22 juillet 2026 — projet Clean Air',url:'https://afdb.africa-newsroom.com/press/cote-divoire-the-african-development-bank-grants-euro200-million-in-financing-to-strengthen-production-of-lowsulfur-fuels?lang=en',date:'22 juillet 2026'};
SOURCES.boost={title:'BAD · 22 septembre 2026 — projet BOOST au Soudan',url:'https://www.afdb.org/en/news-and-events/press-releases/sudan-african-development-bank-and-partners-launch-boost-targeting-stronger-harvests-jobs-and-resilient-livelihoods-96962',date:'22 septembre 2026'};
LESSONS[2]=['Présidence : les quatre points cardinaux','afdb','Le communiqué KOAFEC du 3 septembre 2026 décrit les quatre points cardinaux de Sidi Ould Tah : libérer le potentiel du capital africain ; reconstruire la souveraineté financière ; transformer les tendances démographiques en dividende ; développer des infrastructures résilientes et des chaînes de valeur compétitives. Il rattache à ce cadre la New African Financial Architecture for Development (NAFAD). Ces axes présidentiels sont à distinguer des cinq priorités opérationnelles High 5. Les formulations françaises ici sont des traductions pédagogiques.','koafec'];
NEWS.unshift(
{date:'22 septembre 2026',title:'Soudan : lancement du projet BOOST pour les systèmes agroalimentaires',body:'La BAD et ses partenaires ont lancé BOOST afin de renforcer la sécurité alimentaire, restaurer la production agricole et améliorer les moyens de subsistance dans des communautés touchées par les conflits et les pressions climatiques. Le projet est financé par le FAD et mis en œuvre avec plusieurs partenaires internationaux.',source:'boost',prompt:'Quels liens peux-tu faire entre sécurité alimentaire, résilience, fragilité et la priorité Nourrir l’Afrique ?'},
{date:'8 septembre 2026 · approbation le 1er septembre',title:'Énergie et engrais : un cadre de réponse jusqu’à 5,1 milliards USD',body:'Le GEFCRF prévoit 4,1 milliards USD de prêts BAD supplémentaires et jusqu’à 960 millions USD du FAD. Réponse temporaire d’un an : stabilité macroéconomique, approvisionnements essentiels, protection des ménages vulnérables et résilience. Il s’agit d’un cadre de financement, pas de décaissements déjà réalisés.',source:'crisis',prompt:'Pourquoi un choc sur les engrais peut-il affecter simultanément les récoltes, les prix alimentaires et les finances publiques ?'},
{date:'3 septembre 2026 · annonce',title:'KOAFEC : coopération Corée–Afrique, IA et infrastructures numériques',body:'Le communiqué annonce la conférence ministérielle du 8 au 11 septembre à Séoul, centrée sur IA et infrastructures numériques. Il prévoit un plan d’action 2027–2028. Ce document d’annonce ne permet pas à lui seul de confirmer les conclusions finales de la conférence.',source:'koafec',prompt:'Pourquoi l’adoption de l’IA dépend-elle aussi de l’électricité, des réseaux et des compétences ?'},
{date:'2 septembre 2026',title:'BAD–AXIAN : entrepreneuriat féminin et inclusion financière',body:'Avec AFAWA et We-Fi, le programme cible 34 000 entreprises dirigées par des femmes pour les services financiers à Madagascar, en Tanzanie et au Sénégal. Un volet distinct vise la formation de 25 000 femmes dans cinq pays, dont le Togo et les Comores. Ne pas additionner ces cibles comme des bénéficiaires uniques.',source:'axian',prompt:'Le Togo figure-t-il dans le volet financier à trois pays ou dans le volet formation à cinq pays ?'},
{date:'22 juillet 2026 · approbation le 13 juillet',title:'Côte d’Ivoire : financement du projet Clean Air',body:'La BAD a approuvé un prêt pour un complexe de désulfuration du diesel de la SIR. Retenir surtout la distinction entre contribution d’un bailleur, coût total d’un projet, calendrier de mise en œuvre et résultats effectivement obtenus.',source:'sir',prompt:'Pourquoi faut-il distinguer financement approuvé, mise en œuvre et impact environnemental observé ?'}
);

LESSONS.push(
['Compétences YPP : ce que la BAD recherche','sjt',`La page d’admissibilité 2026 cite explicitement : travail d’équipe, négociation, orientation client, communication, perspective stratégique, leadership, gestion de projet, analyse, esprit d’entreprise, orientation résultats, résolution de problèmes, sens des affaires, innovation, adaptation à un environnement divers et maîtrise du numérique. Pour les SJT, privilégie les réponses qui combinent intégrité, résultats, écoute, proportionnalité, responsabilité et coopération plutôt que les réactions extrêmes.`,'yppskills'],
['Les cinq valeurs BAD comme boussole SJT','sjt',`Les valeurs fondamentales sont Excellence, Esprit d’équipe, Intégrité, Professionnalisme et Transparence. Dans un dilemme, demande-toi : la réponse protège-t-elle l’intégrité ? reste-t-elle professionnelle ? rend-elle les faits et décisions traçables ? recherche-t-elle une solution de qualité ? permet-elle de travailler avec les autres sans sacrifier les règles ? Une bonne réponse évite souvent les deux extrêmes : passivité et escalade disproportionnée.`,'values'],
['Verbal reasoning : Vrai, Faux, Impossible à conclure','reason',`Format d’entraînement générique inspiré de tests psychométriques publics, sans présumer du fournisseur de la BAD. Lis uniquement le passage fourni. Vrai = le passage impose la conclusion. Faux = le passage la contredit. Impossible à conclure = l’information manque, même si l’affirmation semble plausible dans la vie réelle. Les pièges majeurs sont la réciproque, les mots absolus comme « toujours », la causalité inventée et l’ajout de connaissances extérieures.`,null],
['Perspectives économiques en Afrique 2026','africa',`Le thème 2026 est la mobilisation à grande échelle du financement du développement africain dans un monde fragmenté. Les tensions géopolitiques, les conflits, les contraintes de financement et les chocs commerciaux renforcent l’intérêt pour la mobilisation des ressources domestiques, l’épargne, les marchés financiers, le capital privé et une meilleure coordination des institutions africaines. Retenir les mécanismes et arbitrages est plus utile que mémoriser une liste de chiffres.`,'aeo2026'],
['FAD-17, appropriation africaine et effet de levier','afdb',`Le FAD-17 couvre 2026–2028 et a mobilisé un financement record. Le message stratégique est double : préserver le financement concessionnel des pays à faible revenu et accroître l’appropriation africaine, notamment par de nouvelles contributions africaines. Relie FAD-17 aux thèmes de résilience, intégration, création d’emplois, secteur privé et mobilisation du capital à l’échelle.`,'adf17'],
['Développement numérique et IA : raisonner en système','africa',`L’IA n’est pas seulement un sujet technologique. Son adoption dépend d’électricité fiable, connectivité, données, compétences, financement, gouvernance et capacité institutionnelle. Les partenariats KOAFEC 2026 et le Korea–Africa AI Hub illustrent cette approche systémique : infrastructures numériques, investissement privé, expertise, coopération et usage responsable doivent avancer ensemble.`,'aihub']
);

NEWS.unshift(
{date:'22 septembre 2026',title:'Mali : mobiliser davantage de ressources domestiques et privées',body:'Le Country Focus Report 2026 met en avant la mobilisation des recettes domestiques, de l’épargne nationale, des transferts de la diaspora, des marchés financiers régionaux, du capital privé, de la formalisation et des capacités institutionnelles.',source:'mali2026',prompt:'Pourquoi une stratégie de financement du développement gagne-t-elle à diversifier ses sources plutôt qu’à dépendre d’un seul flux externe ?'},
{date:'17 septembre 2026',title:'Korea–Africa AI Hub : coopération sur l’IA responsable',body:'La BAD et la Corée ont signé une lettre d’intention pour créer un hub réunissant gouvernements, institutions financières, centres de recherche, universités et entreprises autour de projets d’IA en Afrique.',source:'aihub',prompt:'Quels prérequis non technologiques conditionnent l’impact réel d’un projet d’IA ?'},
{date:'16 septembre 2026',title:'KOAFEC 2026 : investissement, technologie et secteur privé',body:'La coopération Corée–BAD met davantage l’accent sur l’investissement, les infrastructures numériques, l’IA et l’engagement du secteur privé, en cohérence avec la mobilisation de capitaux et la transformation économique.',source:'koafecfinal',prompt:'Comment distinguer un partenariat de financement d’un résultat de développement effectivement observé ?'},
{date:'14 septembre 2026',title:'Mission 300 : passer du Pacte énergétique à la mise en œuvre',body:'En Côte d’Ivoire, les parties prenantes ont travaillé sur les réformes, les projets prioritaires et la mobilisation du financement nécessaires pour traduire le Pacte national de l’énergie en actions concrètes.',source:'missionsep',prompt:'Pourquoi l’accès à l’électricité dépend-il à la fois d’infrastructures, de réformes et de financement ?'}
);
