/* Original training cases. Complexity labels and pace targets are editorial, not Bryq norms. */
'use strict';
const EXPERT_QUESTIONS=[];
function expertPassage(key,sentences,items){
  items.forEach(([statement,answer,explanation,trap,evidence,why,worlds],i)=>EXPERT_QUESTIONS.push({
    id:`expert-v-${key}-${i}`,family:`expert-v-${key}`,d:'reason',kind:'verbal',lv:5,
    fr:`Selon ce passage uniquement : ${statement}`,o:['Vrai','Faux','Impossible à déterminer'],a:answer,
    x:explanation,stimulus:sentences.join(' '),sentences,trap,evidence,why,worlds:worlds||null,
    rule:TRAPS[trap],hint:'Repère le groupe concerné, le moment et la direction de la règle. Cherche une preuve ou deux situations compatibles.',targetSeconds:70
  }));
}
expertPassage('extension',[
 'Un programme de maintenance distingue les centres pilotes, visités pendant la phase initiale, des centres dont l’intégration est envisagée pour la phase suivante.',
 'Tous les centres pilotes ayant reçu l’autorisation définitive disposent d’un technicien habilité ; la présence de ce technicien ne suffit toutefois pas à obtenir l’autorisation.',
 'Noria a reçu l’autorisation définitive comme centre pilote, tandis que Salo, également pilote, a un technicien habilité mais attend encore une décision.',
 'L’équipe propose d’intégrer Temba, qui ne fait pas partie des centres pilotes, sans que le rapport indique si ce centre dispose déjà d’un technicien.',
 'Pour les centres intégrés ultérieurement, les exigences seront précisées dans une note qui n’a pas encore été adoptée.',
 'Les visites de la phase initiale avaient uniquement pour objet de documenter les conditions de maintenance ; elles ne constituaient ni une sélection définitive ni une garantie de financement.'
],[
 ['Noria dispose d’un technicien habilité.',0,'Noria est un pilote autorisé. La condition nécessaire s’applique donc à ce centre.','necessary',[1,2],['La règle et le statut de Noria imposent cette conclusion.','Faux contredirait la condition nécessaire explicitement remplie par les centres autorisés.','L’information est déductible ; il ne manque pas de fait décisif.']],
 ['La présence du technicien a suffi à autoriser Salo.',1,'Salo attend encore une décision ; le passage nie en outre que le technicien soit une condition suffisante.','stages',[1,2],['Une capacité technique ne vaut pas décision d’autorisation.','L’attente de décision et la règle contredisent l’affirmation.','Le statut de Salo est donné : il ne s’agit pas d’un simple silence.']],
 ['Temba ne dispose d’aucun technicien habilité.',2,'La règle porte sur les pilotes autorisés, pas sur Temba. Son équipement n’est pas renseigné.','scope',[3],['La non-appartenance au pilote ne prouve pas l’absence de technicien.','Le texte ne confirme pas non plus la présence d’un technicien à Temba.','Présence et absence restent possibles.'],['Temba dispose déjà d’un technicien, mais n’a pas rejoint le pilote.','Temba ne dispose pas encore de technicien et attend les futures exigences.']]
]);
expertPassage('audit',[
 'La revue annuelle utilise deux circuits : un contrôle documentaire pour tous les dossiers et une visite supplémentaire pour ceux qui comportent un signalement de risque.',
 'Le règlement prévoit une validation centrale avant publication, mais le rapport de revue ne vérifie pas systématiquement si cette obligation a été respectée pour les publications antérieures.',
 'Le dossier R a fait l’objet d’une visite à cause d’un signalement, alors que le dossier S a seulement subi le contrôle documentaire.',
 'Le rapport précise que le contrôle documentaire de S est terminé et que sa publication reste en attente de validation centrale.',
 'Un dossier peut recevoir une visite complémentaire à la demande de son responsable même sans signalement ; aucune demande de ce type n’est indiquée pour S.',
 'Les visites n’ont pas toutes lieu pendant la même semaine et leur calendrier ne fournit pas, à lui seul, une mesure de la gravité des risques.'
],[
 ['S n’a pas encore obtenu la validation centrale nécessaire à sa publication.',0,'Le rapport place explicitement S en attente de cette validation.','stages',[3],['Le statut en attente fournit directement la preuve.','Faux nierait un statut expressément indiqué.','Ce fait ne dépend pas de la conformité des autres dossiers.']],
 ['Selon la procédure, un signalement de risque est nécessaire pour qu’un dossier puisse recevoir une visite.',1,'Les visites sur demande sans signalement sont explicitement possibles. L’affirmation de nécessité est donc rejetée par la règle.','converse',[0,4],['Signalement implique visite, mais visite n’implique pas signalement.','La possibilité explicite d’un autre circuit invalide la nécessité affirmée.','Le texte donne la règle qui contredit cette nécessité, même sans nommer un dossier visité sur demande.']],
 ['Toutes les publications antérieures ont été validées centralement.',2,'Une obligation ne prouve pas son respect ; celui-ci n’a pas été systématiquement contrôlé.','compliance',[1],['La règle prescrite n’est pas une observation de conformité.','L’absence de contrôle ne prouve pas une violation.','Conformité et violation restent compatibles.'],['Toutes les publications ont respecté l’obligation, sans contrôle exhaustif.','Une publication a échappé à la validation, sans avoir été détectée par la revue.']]
]);
expertPassage('enquete',[
 'Une étude interroge les entreprises qui ont accepté l’accompagnement et distingue celles qui l’ont terminé de celles qui l’ont interrompu.',
 'Parmi les entreprises ayant terminé, certaines déclarent avoir recruté après l’accompagnement ; parmi celles qui l’ont interrompu, des recrutements sont également signalés.',
 'Les auteurs n’observent pas les entreprises qui ont refusé l’offre et ne disposent d’aucune mesure comparable de leur situation avant le programme.',
 'Les entreprises interrogées déclarent toutes avoir reçu au moins une séance, mais cela ne signifie pas qu’elles ont suivi le même parcours ou bénéficié de la même durée d’appui.',
 'Une amélioration de la demande locale s’est produite pendant la période étudiée et peut aussi avoir influencé les décisions d’embauche.',
 'Le rapport décrit des recrutements déclarés et les limites de l’enquête, sans estimer la part des changements qui aurait eu lieu en l’absence d’accompagnement.'
],[
 ['Des entreprises ayant interrompu l’accompagnement ont déclaré des recrutements.',0,'Le passage signale des recrutements dans ce groupe.','scope',[1],['Le fait est explicite pour le groupe des entreprises ayant interrompu.','Faux contredirait les recrutements signalés.','Il n’est pas nécessaire de connaître leur nombre pour constater leur existence.']],
 ['L’étude dispose d’une mesure comparable de la situation initiale des entreprises ayant refusé l’offre.',1,'Elle ne les observe pas et ne possède pas de mesure initiale comparable.','sampling',[2],['La mesure invoquée est explicitement absente.','Le passage contredit directement sa disponibilité.','L’absence est donnée, et non simplement omise.']],
 ['Les recrutements déclarés auraient été moins nombreux sans accompagnement.',2,'Aucun contrefactuel n’est estimé ; la demande locale est aussi susceptible d’influencer les recrutements.','causality',[4,5],['Une succession temporelle ne mesure pas l’effet causal.','Le manque de mesure ne démontre pas l’absence d’effet.','Le programme peut avoir contribué ou non au recrutement observé.'],['L’appui a permis des recrutements qui n’auraient pas eu lieu autrement.','La demande locale aurait produit les mêmes recrutements sans l’appui.']]
]);
expertPassage('exceptions',[
 'La procédure d’archivage interdit l’accès externe aux notes internes, sauf lorsqu’une autorisation nominative du responsable a été enregistrée.',
 'Cette exception autorise la consultation de la version désignée et n’accorde pas, à elle seule, le droit de transmettre le document à d’autres personnes.',
 'Une autorisation concernant la version finale de la note K a été enregistrée pour Amina, qui est une consultante externe.',
 'Benoît, autre consultant externe, a demandé l’accès à la même note ; la demande est encore en cours et aucune autorisation n’est enregistrée pour lui.',
 'La note K existe aussi dans une version de travail, distincte de la version finale désignée par l’autorisation d’Amina.',
 'Les deux versions portent un titre voisin, et la procédure demande de vérifier l’identifiant de version plutôt que de déduire les droits de consultation du seul titre.'
],[
 ['Amina peut consulter la version finale de K selon la procédure.',0,'Son autorisation nominative enregistrée désigne cette version.','exception',[0,2],['L’exception est satisfaite pour cette personne et cette version.','Faux appliquerait l’interdiction générale en oubliant l’exception.','Les faits nécessaires à l’autorisation sont donnés.']],
 ['La demande de Benoît lui donne déjà le droit de consulter K.',1,'Sa demande reste en cours et il n’a aucune autorisation enregistrée ; l’exception ne s’applique pas.','stages',[0,3],['Une demande n’est pas une autorisation.','Les conditions de l’exception ne sont pas remplies.','Le statut de Benoît est explicitement renseigné.']],
 ['Amina a effectivement consulté la version finale de K.',2,'Le passage décrit un droit de consultation, sans dire s’il a été exercé.','observation',[2],['L’autorisation ne prouve pas la consultation effective.','Le silence sur la consultation ne prouve pas qu’elle n’a pas eu lieu.','Les deux comportements restent possibles.'],['Amina a utilisé son autorisation pour lire la version finale.','Amina a reçu l’autorisation mais n’a pas encore ouvert le document.']]
]);
expertPassage('chronologie',[
 'Une unité publie une note de cadrage, puis conduit une consultation avant d’approuver le plan définitif ; cet ordre est imposé pour le projet décrit et a été respecté.',
 'La note de cadrage a été publiée avant le lancement de la consultation, et le plan définitif a été approuvé après sa clôture.',
 'Le rapport de suivi précise qu’un atelier technique s’est tenu pendant la consultation mais ne situe pas la réunion budgétaire par rapport à cet atelier.',
 'La réunion budgétaire s’est déroulée avant l’approbation du plan, et ses conclusions figurent dans le dossier transmis à la direction.',
 'Les demandes formulées pendant la consultation ont été regroupées dans une annexe distincte afin d’éviter de confondre leur réception avec leur adoption.',
 'Le rapport confirme l’approbation du plan définitif, sans affirmer que toutes les demandes reçues ont été retenues ni que toutes les dépenses proposées ont été engagées.'
],[
 ['La consultation était close lorsque le plan définitif a été approuvé.',0,'Le texte situe explicitement l’approbation après la clôture.','chronology',[1],['L’ordre de ces deux événements est connu.','Faux inverserait l’ordre explicitement donné.','L’absence de dates chiffrées ne rend pas cet ordre indéterminé.']],
 ['Le plan définitif a été approuvé avant la publication de la note de cadrage.',1,'L’ordre respecté est note, consultation, puis approbation.','chronology',[0,1],['L’approbation n’est pas le premier événement.','L’ordre explicite contredit l’affirmation.','Les événements concernés sont ordonnés sans ambiguïté.']],
 ['La réunion budgétaire s’est tenue avant l’atelier technique.',2,'Les deux sont antérieurs à l’approbation, mais leur ordre relatif n’est pas donné.','chronology',[2,3],['Une échéance finale commune ne fixe pas leur ordre relatif.','Le passage ne donne pas non plus l’ordre inverse.','Les deux ordres sont compatibles.'],['La réunion budgétaire précède l’atelier, et tous deux précèdent l’approbation.','L’atelier précède la réunion budgétaire, et tous deux précèdent l’approbation.']]
]);
expertPassage('negations',[
 'La commission examine plusieurs propositions de formation et note, pour chacune, la validation du contenu et celle du calendrier.',
 'Le relevé affirme qu’aucune proposition dont le contenu n’a pas été validé n’a été retenue pour la session principale.',
 'La proposition K a été retenue pour cette session, mais son calendrier sera fixé après confirmation de la disponibilité des formateurs.',
 'Certaines propositions au contenu validé n’ont pas été retenues parce que leur mise en œuvre exigeait des équipements encore indisponibles.',
 'Les propositions écartées peuvent être réexaminées plus tard ; le relevé ne les présente donc pas comme définitivement abandonnées.',
 'La disponibilité d’un formateur pour K est en cours de vérification, sans indication permettant d’anticiper la date de confirmation ni la période exacte où la formation se tiendra.'
],[
 ['Le contenu de K a été validé.',0,'Aucun contenu non validé n’est retenu ; K est retenue, donc son contenu est validé.','negation',[1,2],['La double négation exprime une condition nécessaire satisfaite par K.','Faux serait incompatible avec la sélection de K.','La règle suffit à trancher le statut du contenu.']],
 ['Toutes les propositions au contenu validé ont été retenues.',1,'Certaines de ces propositions ont été écartées faute d’équipements.','quantifier',[3],['Le texte fournit un contre-exemple au « toutes ».','Le sous-groupe validé mais non retenu réfute l’affirmation.','Le contre-exemple est explicite, il ne manque pas de données.']],
 ['Le calendrier de K sera confirmé cette semaine.',2,'Le calendrier dépend d’une confirmation dont la date n’est pas indiquée.','chronology',[2,5],['Une confirmation en cours n’en fixe pas la date.','Une confirmation tardive n’est pas davantage annoncée.','Cette semaine et une semaine ultérieure restent possibles.'],['La disponibilité est confirmée rapidement et le calendrier est fixé cette semaine.','La vérification se prolonge et le calendrier est fixé la semaine suivante.']]
]);
expertPassage('canaux',[
 'Le dispositif de réclamation accepte les demandes déposées sur place, les appels téléphoniques et les messages transmis par le formulaire en ligne.',
 'Le tableau publié concerne uniquement les demandes enregistrées dans l’outil numérique, même lorsque leur canal d’origine est le téléphone ou un dépôt sur place.',
 'Les messages reçus par formulaire sont automatiquement enregistrés ; les deux autres canaux nécessitent une saisie par un agent qui peut intervenir plus tard.',
 'Le rapport signale un retard de saisie pour certaines demandes téléphoniques, mais ne donne ni le nombre de demandes encore absentes de l’outil ni celui des dépôts sur place non saisis.',
 'Toutes les demandes présentes dans le tableau ont un identifiant de suivi ; la possession d’un identifiant ne signifie pas que la demande a déjà été résolue.',
 'Les conclusions portent sur les demandes enregistrées à la date d’extraction et les auteurs demandent de compléter la saisie avant d’utiliser ce tableau comme inventaire exhaustif des demandes reçues.'
],[
 ['Le tableau exclut les demandes qui n’ont pas encore été saisies dans l’outil numérique.',0,'Son périmètre est limité aux demandes enregistrées.','scope',[1],['Le périmètre d’extraction impose cette exclusion.','Le canal d’origine ne remplace pas la condition d’enregistrement.','Le périmètre du tableau est connu.']],
 ['Toutes les demandes figurant dans le tableau ont été résolues.',2,'Un identifiant de suivi ne renseigne pas à lui seul sur la résolution.','stages',[4],['Le suivi n’est pas la résolution ; aucune exhaustivité des résolutions n’est donnée.','Le texte ne dit pas non plus qu’une demande du tableau demeure non résolue.','Toutes résolues ou certaines en cours sont deux états possibles.'],['Toutes les demandes enregistrées sont déjà résolues.','Une demande enregistrée et identifiée reste en cours de traitement.']],
 ['Le rapport donne le nombre de demandes téléphoniques restant à saisir.',1,'Il signale un retard mais indique expressément qu’il ne donne pas ce nombre.','observation',[3],['Constater un retard ne fournit pas son volume.','Le nombre invoqué est explicitement absent.','On sait que le rapport ne contient pas ce nombre.']]
]);
expertPassage('comparaison',[
 'La note économique compare le coût du transport dans les corridors Est et Ouest et distingue le coût moyen observé de la variabilité entre entreprises.',
 'Elle indique que le coût moyen du corridor Est a diminué entre les deux périodes étudiées, tandis que celui du corridor Ouest est resté stable.',
 'Dans le corridor Est, certaines entreprises signalent néanmoins une hausse de leurs coûts, liée notamment à l’allongement de trajets locaux.',
 'Les auteurs ne présentent pas de comparaison du niveau initial des coûts moyens entre les deux corridors et utilisent des groupes d’entreprises différents dans chacun.',
 'La diminution moyenne à l’Est coïncide avec une amélioration des formalités, mais le rapport n’isole pas l’effet de cette amélioration des autres changements survenus.',
 'Les conclusions décrivent les variations observées à l’intérieur de chaque corridor et avertissent qu’une évolution plus favorable ne signifie pas automatiquement un niveau final moins élevé.'
],[
 ['Une baisse du coût moyen à l’Est coexiste avec des hausses pour certaines entreprises de ce corridor.',0,'La tendance moyenne et les hausses individuelles sont toutes deux explicitement décrites.','aggregation',[1,2],['Une moyenne ne force pas chaque observation à évoluer dans le même sens.','Faux nierait un fait individuel expressément signalé.','Les deux observations sont données.']],
 ['Toutes les entreprises du corridor Est ont bénéficié d’une baisse de leurs coûts.',1,'Certaines entreprises ont signalé une hausse.','quantifier',[2],['Les hausses constituent un contre-exemple.','« Toutes » est réfuté par les entreprises en hausse.','Le contre-exemple est connu.']],
 ['Le coût moyen final est plus faible à l’Est qu’à l’Ouest.',2,'Les niveaux initiaux et la comparaison finale ne sont pas fournis.','aggregation',[1,3,5],['Baisser davantage ne suffit pas à atteindre un niveau plus bas.','L’Est pourrait tout de même finir moins cher : le contraire n’est pas établi.','Il manque les niveaux nécessaires à la comparaison.'],['Le coût à l’Est part de plus bas et reste inférieur après la baisse.','Le coût à l’Est part de beaucoup plus haut et reste supérieur malgré la baisse.']]
]);
expertPassage('contrat',[
 'Pour le contrat décrit, une livraison est acceptée si et seulement si le contrôle de conformité est positif et le bordereau correspondant est signé.',
 'Cette règle a été respectée sans dérogation pour toutes les livraisons mentionnées dans la note, mais elle ne porte pas sur le paiement des factures.',
 'La livraison K a un contrôle positif et un bordereau signé ; la livraison L a un contrôle positif mais son bordereau n’est pas signé.',
 'L’équipe distingue l’acceptation technique de la mise en paiement, qui exige également un dossier de facture complet et un visa financier.',
 'La note ne décrit pas l’état du dossier de facture de K et précise que l’acceptation technique peut précéder la réception de cette facture.',
 'Les difficultés de communication avec un fournisseur sont consignées séparément et ne modifient pas les conditions contractuelles d’acceptation dans ce scénario.'
],[
 ['La livraison K a été acceptée.',0,'Les deux conditions sont remplies et la règle, explicitement respectée, est suffisante.','sufficient',[0,1,2],['Le « si et seulement si » et la conformité posée rendent la conclusion certaine.','Faux serait incompatible avec les deux conditions réunies.','Le passage ferme explicitement la possibilité d’une dérogation.']],
 ['La livraison L a été acceptée.',1,'Le bordereau signé est nécessaire et il manque à L ; la règle a été respectée.','necessary',[0,1,2],['Le contrôle positif seul ne remplit pas les deux conditions.','L’absence du bordereau nécessaire exclut l’acceptation.','Le respect de la règle est posé ; il ne s’agit pas d’une simple obligation.']],
 ['La facture de K est déjà mise en paiement.',2,'Les conditions supplémentaires et l’état du dossier de facture ne sont pas renseignés.','stages',[3,4],['Acceptation technique et paiement sont des étapes différentes.','Le texte ne dit pas non plus que le dossier financier est incomplet.','Paiement engagé ou facture encore attendue restent possibles.'],['K a également une facture complète et un visa ; la mise en paiement est engagée.','K est acceptée techniquement, mais la facture n’a pas encore été reçue.']]
]);
expertPassage('selection',[
 'Un appel à projets évalue séparément l’admissibilité administrative, la pertinence technique et les possibilités de financement.',
 'Seuls les projets administrativement admissibles sont évalués techniquement, et tous les projets techniquement recommandés ont une évaluation terminée.',
 'Le projet K est techniquement recommandé ; le projet L est admissible mais son évaluation technique reste à terminer.',
 'Les recommandations seront ensuite examinées au regard des ressources disponibles, et le comité de financement ne s’est pas encore réuni.',
 'Le rapport ne contient aucune décision de financement pour K ou L et précise qu’une recommandation technique ne constitue pas une promesse de financement.',
 'Les porteurs sont invités à corriger les éléments manquants avant l’échéance applicable, sans que cette invitation établisse le résultat final de leur demande.'
],[
 ['Le projet K est administrativement admissible.',0,'K recommandé implique évaluation terminée ; seuls les admissibles sont évalués.','only',[1,2],['La chaîne de conditions nécessaires conduit à l’admissibilité.','Faux contredirait le périmètre de l’évaluation technique.','Les deux étapes de la déduction sont fournies.']],
 ['Le comité de financement s’est déjà réuni pour ces projets.',1,'Le texte dit qu’il ne s’est pas encore réuni.','chronology',[3],['Un examen futur n’est pas une réunion passée.','L’affirmation contredit directement le statut indiqué.','Le statut de la réunion est connu.']],
 ['K obtiendra un financement à l’issue du processus.',2,'La recommandation n’est pas une promesse et les ressources doivent encore être examinées.','stages',[3,4],['La recommandation ne garantit pas la décision future.','L’absence de décision n’est pas un refus définitif.','Une attribution ou un refus restent possibles.'],['Les ressources permettent de financer K lors de la réunion.','Les ressources sont insuffisantes et K n’est pas financé malgré la recommandation.']]
]);
expertPassage('causes',[
 'Deux groupes de producteurs ont reçu des offres différentes : le groupe A a eu accès à des conseils techniques et le groupe B à ces mêmes conseils ainsi qu’à un service de livraison.',
 'Les groupes ont été constitués sur la base de leur localisation, sans tirage aléatoire ; le rapport indique que leurs accès initiaux aux marchés n’étaient pas comparables.',
 'Après la saison, les ventes déclarées par le groupe B ont augmenté plus que celles du groupe A, et les deux groupes ont connu une hausse des prix de vente.',
 'Le coût d’utilisation du service de livraison a été enregistré séparément, mais les ventes déclarées ne sont pas présentées comme des revenus nets de tous les coûts.',
 'Le rapport confirme que des membres des deux groupes ont vendu une partie de leur récolte en dehors des circuits étudiés.',
 'Les auteurs proposent de recueillir des données supplémentaires avant d’attribuer l’écart de progression au service de livraison ou de conclure à une hausse plus forte du revenu net.'
],[
 ['Les groupes avaient des accès initiaux aux marchés comparables.',1,'Le rapport indique expressément qu’ils n’étaient pas comparables.','sampling',[1],['Le fait posé est l’absence de comparabilité initiale.','Le texte impose le contraire de l’affirmation.','Cette différence est explicitement documentée.']],
 ['Des membres des deux groupes ont utilisé des circuits de vente non étudiés.',0,'Ce comportement est explicitement confirmé.','scope',[4],['L’existence de ces ventes est donnée pour les deux groupes.','Faux nierait un fait confirmé.','Leur volume n’est pas nécessaire pour conclure à leur existence.']],
 ['Le service de livraison explique à lui seul l’écart de progression des ventes.',2,'La sélection initiale et les autres influences ne sont pas isolées. Le rapport ne démontre ni cette attribution exclusive ni son contraire.','attribution',[1,2,5],['La comparaison brute ne suffit pas à prouver une causalité exclusive.','Les facteurs possibles ne prouvent pas qu’ils ont effectivement causé l’écart.','Plusieurs explications restent ouvertes.'],['Le service explique tout l’écart, les différences initiales n’affectant pas la progression cette saison.','Une partie de l’écart vient de conditions de marché différentes entre les localités.']]
]);
expertPassage('ou',[
 'Un site ne peut être admis au dispositif de secours que s’il dispose d’un accès routier opérationnel ou d’une liaison fluviale sécurisée ; une seule de ces deux possibilités suffit pour satisfaire cette condition d’accès.',
 'Les sites admis disposent également d’un responsable de réception, et ces règles ont été respectées pour les sites du scénario.',
 'Le site K est admis, mais son accès routier n’est pas opérationnel ; le site L n’a ni accès routier opérationnel ni liaison fluviale sécurisée.',
 'Le responsable de réception de K a été confirmé après échange avec l’équipe locale, sans que le rapport indique si les installations de stockage de K sont couvertes.',
 'Une annexe décrit des sites candidats supplémentaires dont le statut n’est pas encore arrêté ; les informations de cette annexe ne modifient pas celles concernant K et L.',
 'Le choix du mode d’acheminement reste distinct de l’évaluation de la capacité de stockage, qui sera conduite dans une étape ultérieure.'
],[
 ['K dispose d’une liaison fluviale sécurisée.',0,'K admis satisfait route OU fleuve ; route faux impose fleuve vrai.','connective',[0,1,2],['L’alternative routière étant exclue, la liaison fluviale est nécessaire.','Faux rendrait impossible l’admission de K selon les règles respectées.','La disjonction et le statut permettent de trancher.']],
 ['L est un site admis selon ces règles.',1,'Aucune des deux conditions suffisantes d’accès n’est présente, et l’admission exige au moins l’une.','connective',[0,1,2],['Aucune alternative d’accès n’est satisfaite.','L est incompatible avec les conditions d’admission respectées.','Le scénario donne les deux absences.']],
 ['Les installations de stockage de K sont couvertes.',2,'La couverture du stockage n’est pas indiquée et n’entre pas dans la règle d’accès.','scope',[3,5],['La liaison fluviale ne prouve pas la couverture du stockage.','L’absence d’évaluation ne prouve pas un stockage découvert.','Les deux états restent compatibles.'],['K dispose d’un entrepôt couvert qui reste à évaluer.','K utilise un espace de stockage non couvert qui reste à évaluer.']]
]);
expertPassage('reserve',[
 'La note de financement classe les opérations en « approuvée », « en préparation » et « en attente de décision », selon leur état au moment de sa clôture.',
 'Le projet K figure parmi les opérations approuvées, tandis que L est en préparation et M attend une décision.',
 'Pour K, une première tranche a été décaissée ; la note précise que les tranches suivantes restent conditionnées à des étapes qui n’ont pas toutes été franchies.',
 'L’équipe a mené une visite sur le site de L, mais cette visite ne constitue pas une approbation et aucune décision d’approbation de L n’a été prise à la date de clôture.',
 'La note ne donne pas de compte rendu de chantier pour K et avertit qu’un décaissement n’est pas, à lui seul, une preuve de réalisation des travaux.',
 'Les catégories sont des états observés à une date donnée ; elles ne permettent pas de prédire le classement final des opérations encore en préparation ou en attente.'
],[
 ['Le financement de K a commencé à être décaissé.',0,'Une première tranche a effectivement été décaissée.','stages',[2],['L’événement financier est explicitement réalisé.','Faux contredirait le premier décaissement.','Le statut des travaux n’est pas nécessaire pour trancher ce fait financier.']],
 ['L était déjà approuvé à la date de clôture de la note.',1,'Aucune approbation de L n’avait été prise à cette date.','stages',[3],['Une visite préparatoire n’est pas une approbation.','L’absence de décision à la date de clôture est explicite.','Le statut de L n’est pas simplement omis.']],
 ['Les travaux de K ont déjà commencé.',2,'La note n’observe pas le chantier ; le décaissement n’établit pas ce fait.','stages',[2,4],['Un mouvement financier ne prouve pas le démarrage physique.','L’absence de compte rendu ne démontre pas un chantier à l’arrêt.','Travaux commencés ou pas encore commencés restent possibles.'],['Les fonds ont permis de démarrer des travaux, sans compte rendu inclus dans la note.','Les fonds sont disponibles mais les travaux n’ont pas encore commencé.']]
]);
expertPassage('confidentialite',[
 'Le registre des bénéficiaires contient une liste nominative et une annexe statistique qui a été rendue anonyme avant diffusion.',
 'La liste nominative est réservée à l’équipe habilitée, tandis que l’annexe anonyme peut être communiquée aux partenaires concernés.',
 'Le rapport affirme que seule l’annexe anonyme a été envoyée au partenaire P et que la liste nominative est restée dans l’espace restreint.',
 'Le partenaire P a accusé réception du fichier transmis, mais le rapport ne dit pas s’il l’a lu ou s’il en a tiré une analyse.',
 'Une demande ultérieure d’accès à la liste nominative a été reçue de P ; elle attend encore un examen au regard de l’habilitation et de la finalité demandées.',
 'La réception d’un fichier autorisé ne donne pas de droit automatique sur les autres fichiers du registre, même lorsqu’ils concernent la même opération.'
],[
 ['P a reçu l’annexe statistique anonyme.',0,'Le rapport confirme son envoi et l’accusé de réception de P.','observation',[2,3],['Le fichier envoyé est identifié et sa réception confirmée.','Faux contredirait les deux faits concordants.','On connaît le document reçu, même sans savoir s’il a été lu.']],
 ['La liste nominative a été envoyée à P lors de cette transmission.',1,'Seule l’annexe a été envoyée et la liste est restée restreinte.','negation',[2],['La restriction « seule » exclut la liste de cette transmission.','Le texte impose l’absence d’envoi de la liste.','Il s’agit d’un fait de transmission renseigné.']],
 ['P a utilisé l’annexe pour produire une analyse.',2,'L’accusé de réception n’indique ni lecture ni utilisation analytique.','observation',[3],['Recevoir n’est pas analyser.','Le silence n’établit pas non plus une absence d’analyse.','Une utilisation ou une simple réception restent possibles.'],['P a lu l’annexe et produit une analyse après réception.','P a accusé réception sans encore lire ni analyser l’annexe.']]
]);
expertPassage('restrictions',[
 'La charte d’un atelier autorise une personne à présider la séance si et seulement si elle appartient au comité et n’intervient pas comme rapporteuse pendant cette même séance.',
 'Les rôles ont été attribués conformément à la charte pour l’atelier décrit ; Amina préside la séance et Benoît en est le rapporteur.',
 'Céline appartient au comité mais le relevé ne dit pas si elle exerce également une fonction de rapporteuse à cette séance.',
 'L’appartenance au comité est indépendante de la participation à une réunion préparatoire ; des personnes extérieures ont aussi participé à cette réunion.',
 'Le relevé confirme la présence de David à la réunion préparatoire sans préciser son appartenance au comité ni son rôle pendant l’atelier.',
 'L’objectif de cette séparation des fonctions est d’éviter qu’une même personne dirige les échanges et rédige leur restitution, et non de limiter la présence d’observateurs extérieurs.'
],[
 ['Amina appartient au comité et n’est pas rapporteuse de cette séance.',0,'Présider impose les deux conditions et les rôles respectent la charte.','necessary',[0,1],['La règle de présidence impose l’appartenance et l’exclusion du rôle de rapporteur.','Faux serait incompatible avec la charte respectée.','Les conditions nécessaires sont déductibles.']],
 ['Benoît peut présider cette même séance selon la charte.',1,'Son rôle de rapporteur l’exclut de la présidence de cette séance.','negation',[0,1],['Le rapporteur échoue à la condition de non-cumul.','La charte interdit ce cumul dans la séance concernée.','Il n’est pas nécessaire de connaître son appartenance au comité.']],
 ['David appartient au comité.',2,'La participation à la réunion préparatoire est indépendante de cette appartenance.','converse',[3,4],['La présence à une réunion ne prouve pas l’appartenance.','Des externes sont possibles, mais David n’est pas identifié comme externe.','Membre et non-membre sont compatibles.'],['David est membre du comité et a assisté à la préparation.','David est un observateur extérieur ayant assisté à la préparation.']]
]);
expertPassage('modalites',[
 'Le programme propose aux coopératives une formation de gestion ; celles qui la terminent peuvent ensuite demander un diagnostic personnalisé.',
 'Le diagnostic n’est pas automatique : il exige une demande distincte et la confirmation d’un créneau par le conseiller.',
 'K a terminé la formation et envoyé sa demande, mais attend encore une confirmation ; L a terminé la formation sans déposer de demande.',
 'La note précise qu’aucun diagnostic de K ou L n’a commencé à sa date de clôture et que les places disponibles seront réparties lors d’une réunion ultérieure.',
 'Une entreprise de transport a proposé de faciliter les déplacements pour les diagnostics sur site ; cette proposition n’est pas encore intégrée au calendrier.',
 'Les critères de répartition des places ne figurent pas dans la note, qui ne permet donc pas de classer K par rapport aux autres demandes recevables.'
],[
 ['L peut demander un diagnostic personnalisé.',0,'La formation terminée ouvre ce droit de demande ; elle ne garantit pas un créneau.','necessary',[0,2],['L satisfait la condition qui permet la demande.','Faux confondrait ne pas avoir demandé et ne pas pouvoir demander.','La possibilité de demander est expressément établie.']],
 ['Le diagnostic de K avait déjà commencé à la clôture de la note.',1,'Aucun diagnostic de K ou L n’avait commencé.','stages',[3],['Une demande déposée ne vaut pas démarrage.','La note contredit explicitement le démarrage de K.','Ce fait est renseigné pour K.']],
 ['K sera prioritaire sur les autres demandes recevables.',2,'Les critères et le classement futur ne sont pas donnés.','scope',[5],['Avoir terminé et demandé ne prouve pas la priorité relative.','L’absence de classement n’impose pas une priorité inférieure.','Les deux classements restent possibles.'],['Les critères à venir donnent la priorité à K.','Un autre demandeur est prioritaire selon les critères à venir.']]
]);

function expertCase(id,d,fr,o,a,x,why,extra={}){
  EXPERT_QUESTIONS.push({id:`expert-${id}`,family:`expert-${id}`,d,fr,o,a,x,why,lv:5,targetSeconds:60,
    trap:d==='sjt'?'judgment':d==='afdb'?'institution':d==='africa'?'development':'constraints',...extra});
}
const LOGIC_CASES=[
 ['publication','Une note ne peut être publiée que si elle est autorisée. Toute autorisation exige à la fois un contrôle positif et un visa. Le visa de K n’a pas été accordé. Les règles sont respectées. Que peut-on affirmer ?',
  ['K ne peut pas être publiée dans cet état.','Le contrôle de K est nécessairement négatif.','K est autorisée mais attend seulement sa publication.','Le contrôle de K a nécessairement été effectué.'],0,
  'Sans visa, aucune autorisation ; sans autorisation, aucune publication. Le contrôle reste indéterminé.',
  ['Deux contraposées successives imposent cette conclusion.','L’absence du visa ne dit rien du contrôle.','L’autorisation exigerait le visa absent.','Le passage ne dit pas si un contrôle a été effectué.'],
  {vars:['p','a','c','v'],rules:['!p||a','!a||(c&&v)','!v'],options:['!p','!c','a&&!p','c']}],
 ['comite','Le comité active soit le circuit standard, soit le circuit exceptionnel, mais jamais les deux. Le circuit exceptionnel implique un avis externe. Un avis externe n’est émis que si le circuit standard est inactif. Pour K, aucun avis externe n’a été émis. Une des deux voies a bien été activée. Quelle conclusion s’impose ?',
  ['K a utilisé le circuit exceptionnel.','K n’a utilisé aucun des circuits.','K a utilisé le circuit standard.','Un avis externe sera obligatoirement émis plus tard.'],2,
  'L’absence d’avis exclut le circuit exceptionnel. Une voie étant active, c’est la voie standard.',
  ['Exceptionnel impliquerait un avis absent.','Le passage impose l’activation d’une voie.','L’exclusion de l’exceptionnel et la disjonction imposent le standard.','Les règles ne disent rien des avis futurs.'],
  {vars:['s','e','a','f'],rules:['s!==e','!e||a','!a||!s','!a'],options:['e','!s&&!e','s','f']}],
 ['pieces','Tout dossier accepté est complet. Tout dossier complet possède une annexe signée ou une dispense, au moins l’une des deux. K est accepté et ne bénéficie d’aucune dispense. Qu’est-ce qui est nécessairement vrai ?',
  ['K possède une annexe signée.','La dispense de K sera accordée ultérieurement.','L’acceptation suffit à prouver un paiement.','La signature suffit à faire accepter n’importe quel dossier.'],0,
  'Accepté implique complet ; complet et absence de dispense imposent la signature.',
  ['La chaîne et l’alternative éliminée prouvent la signature.','Aucune information sur une dispense future.','Paiement n’appartient pas aux conditions données.','La règle ne donne pas la réciproque signature vers acceptation.'],
  {vars:['a','c','s','d','p','f','b','h'],rules:['!a||c','!c||(s||d)','a','!d'],options:['s','f','p','!b||h']}],
 ['validation','L’enregistrement d’une validation exige une vérification. Une vérification exige une pièce originale ou une confirmation indépendante. K est validé, et il n’existe aucune pièce originale pour K. Quelle déduction est certaine ?',
  ['K a été validé sans vérification.','Une confirmation indépendante existe pour K.','Une pièce originale sera nécessairement obtenue ensuite.','La confirmation indépendante suffit à garantir toute validation.'],1,
  'La vérification est imposée par la validation ; faute d’original, la confirmation indépendante est nécessaire.',
  ['Cela contredirait la première règle.','La disjonction et l’absence d’original imposent la confirmation.','Le texte ne prévoit pas d’original futur.','Une condition nécessaire n’est pas forcément suffisante.'],
  {vars:['v','c','o','i','f','b','h'],rules:['!v||c','!c||(o||i)','v','!o'],options:['v&&!c','i','f','!b||h']}],
 ['deploiement','Si le déploiement a lieu, le site est prêt. Si le site est prêt et l’agent disponible, l’équipe intervient. L’agent est disponible, mais l’équipe n’intervient pas. Les règles sont toutes respectées. Quelle conclusion est nécessaire ?',
  ['Le site est prêt mais l’intervention a été annulée.','Le déploiement n’a pas eu lieu.','L’agent n’est pas réellement disponible.','L’intervention aura lieu demain.'],1,
  'Agent disponible et absence d’intervention excluent un site prêt ; cela exclut aussi le déploiement.',
  ['Prêt et disponible imposeraient une intervention.','Les deux implications, prises à rebours avec les faits, excluent le déploiement.','La disponibilité est explicitement donnée.','Le futur de l’intervention est inconnu.'],
  {vars:['d','p','a','i','f'],rules:['!d||p','!(p&&a)||i','a','!i'],options:['p&&!i','!d','!a','f']}],
 ['independance','Un dossier soumis à révision est confié soit à l’équipe interne soit à un expert externe, jamais aux deux. Un conflit déclaré interdit l’équipe interne. K est soumis à révision et présente un conflit déclaré. Quelle conclusion est imposée ?',
  ['K n’est pas soumis à révision.','K est confié aux deux intervenants.','Le conflit de K a été résolu.','K est confié à un expert externe.'],3,
  'Le conflit exclut l’interne ; la révision impose une voie ; l’externe reste donc la seule.',
  ['K est explicitement soumis à révision.','La double attribution est interdite.','Déclaré ne veut pas dire résolu.','L’exclusion de l’interne et la voie obligatoire imposent l’externe.'],
  {vars:['r','i','e','c','s'],rules:['!r||(i!==e)','!c||!i','r','c'],options:['!r','i&&e','s','e']}],
 ['admission','Un site est admis si et seulement s’il satisfait les conditions techniques et possède une convention signée. K satisfait les conditions techniques, mais n’est pas admis. Les règles sont respectées. Quelle conclusion s’impose ?',
  ['La convention de K n’est pas signée.','K échoue aux conditions techniques.','La convention a été retirée après admission.','Le prochain comité admettra K.'],0,
  'Si la convention était signée, les deux conditions imposeraient l’admission. L’absence d’admission impose donc une convention non signée.',
  ['La suffisance des deux conditions et le fait technique permettent de conclure.','Le texte affirme le contraire.','Aucune chronologie de retrait n’est donnée.','La décision future demeure inconnue.'],
  {vars:['a','t','c','r','f'],rules:['a===(t&&c)','t','!a'],options:['!c','!t','r','f']}],
 ['langue','Une réunion se tient soit en français soit en anglais, jamais dans les deux langues. Une réunion en anglais impose la présence d’un interprète pour l’équipe décrite. L’interprète est absent et la réunion a bien lieu. Quelle conclusion est certaine ?',
  ['La réunion se tient en anglais.','La réunion se tient en français.','La réunion est bilingue.','Tous les participants sont francophones.'],1,
  'Sans interprète, l’anglais est exclu ; une des deux langues est utilisée, donc le français.',
  ['L’anglais exigerait un interprète absent.','La voie restante est le français.','L’exclusivité exclut le bilinguisme dans ce scénario.','La langue de réunion ne décrit pas toutes les compétences des participants.'],
  {vars:['f','e','i','p'],rules:['f!==e','!e||i','!i'],options:['e','f','f&&e','p']}],
 ['controle','Si un signalement est confirmé, le dossier est réexaminé. Si un dossier est réexaminé, il reçoit une nouvelle note. K n’a reçu aucune nouvelle note. Le texte ne décrit pas les signalements non confirmés. Qu’est-ce qui est certain ?',
  ['K n’a reçu aucun signalement, même non confirmé.','K a été réexaminé sans note.','Aucun signalement de K n’a été confirmé.','K a été définitivement clôturé.'],2,
  'Sans note, pas de réexamen ; sans réexamen, pas de signalement confirmé. Un signalement non confirmé reste possible.',
  ['La règle n’exclut pas un signalement non confirmé.','Un réexamen imposerait une note.','La double contraposée exclut la confirmation.','La clôture n’apparaît pas dans les règles.'],
  {vars:['s','r','n','u','c'],rules:['!s||r','!r||n','!n'],options:['!s&&!u','r&&!n','!s','c']}],
 ['garantie','Le pilote exige, pour toute opération retenue, une garantie ou une assurance. La présence simultanée des deux est autorisée. K est retenue et n’a pas d’assurance. Que doit-on conclure ?',
  ['K dispose d’une garantie.','K dispose forcément des deux protections.','Aucune autre opération ne peut cumuler les protections.','Toutes les garanties entraînent automatiquement une sélection.'],0,
  'L’alternative inclusive est obligatoire pour K. L’absence d’assurance impose la garantie ; elle ne dit rien des autres opérations.',
  ['L’une des deux protections est imposée et l’assurance est exclue.','L’assurance de K est explicitement absente.','Le cumul est autorisé.','La règle va de retenue vers protection, pas l’inverse.'],
  {vars:['r','g','a','x','y','b','h'],rules:['!r||(g||a)','r','!a'],options:['g','g&&a','!(x&&y)','!b||h']}],
 ['acces','Un compte externe actif possède un responsable désigné. Aucun compte sans contrat valide n’est actif. K n’a aucun responsable désigné ; le texte ne précise pas si son contrat est valide. Quelle conclusion est certaine ?',
  ['Le contrat de K n’est pas valide.','K n’est pas un compte actif.','Le contrat de K est valide.','Tout compte avec contrat valide est actif.'],1,
  'L’absence du responsable nécessaire exclut l’activité, sans fixer le statut du contrat.',
  ['Un contrat valide pourrait coexister avec un compte inactif.','La condition nécessaire du responsable est absente.','Le contrat reste indéterminé.','Le contrat est nécessaire mais pas annoncé comme suffisant.'],
  {vars:['a','r','c','x'],rules:['!a||r','!a||c','!r'],options:['!c','!a','c','!c||a']}],
 ['reunion','Pour cette séance, être rapporteur implique être présent. Être président implique être présent et ne pas être rapporteur. K est rapporteur. L’appartenance au comité est indépendante de ces rôles. Quelle conclusion est obligatoire ?',
  ['K est président et présent.','K est absent.','K est membre du comité.','K est présent et n’est pas président.'],3,
  'Rapporteur impose présence et exclut la présidence, puisque le président ne peut être rapporteur.',
  ['Président et rapporteur sont incompatibles.','Le rapporteur est nécessairement présent.','L’appartenance n’est pas déduite des rôles.','Les deux règles imposent présence et absence de présidence.'],
  {vars:['r','p','s','c'],rules:['!r||s','!p||(s&&!r)','r'],options:['p&&s','!s','c','s&&!p']}]
];
for(const [id,fr,o,a,x,why,model] of LOGIC_CASES)expertCase(`l-${id}`,'reason',fr,o,a,x,why,{kind:'logic',targetSeconds:65,model});

const DETAIL_CASES=[
 ['reference','Recopie le dossier admissible : référence exactement « KA-072-B », version FINALE, consentement OUI. Une seule ligne respecte les trois critères.',
  [['KA-072-B','FINALE','OUI'],['KA-072-B','PROVISOIRE','OUI'],['KA-072-8','FINALE','OUI'],['KA-072-B','FINALE','NON']],0,['Référence, version et consentement coïncident.','La version est provisoire.','Le dernier caractère est 8, pas B.','Le consentement est NON.']],
 ['echeance','Sélectionne le dossier reçu AVANT le 8 octobre, COMPLET et VALIDÉ. Les dates sont toutes d’octobre 2026.',
  [['08 octobre','COMPLET','VALIDÉ'],['07 octobre','COMPLET','VALIDÉ'],['06 octobre','INCOMPLET','VALIDÉ'],['07 octobre','COMPLET','À VALIDER']],1,['« Avant » exclut le 8.','Le 7 précède le 8 et les deux statuts conviennent.','Le dossier est incomplet.','À valider n’est pas validé.']],
 ['acces','Accorde l’accès seulement à un membre HABILITÉ de l’équipe ACHATS avec une autorisation NON EXPIRÉE.',
  [['ACHATS','HABILITÉ','EXPIRÉE'],['SUIVI','HABILITÉ','NON EXPIRÉE'],['ACHATS','HABILITÉ','NON EXPIRÉE'],['ACHATS','À HABILITER','NON EXPIRÉE']],2,['L’autorisation est expirée.','L’équipe est SUIVI.','Les trois conditions sont réunies.','L’habilitation reste à faire.']],
 ['version','Le destinataire demande le document D-104, RÉVISION 2, sans ANNEXE NOMINATIVE. Sélectionne l’envoi conforme.',
  [['D-104','RÉVISION 1','SANS ANNEXE'],['D-140','RÉVISION 2','SANS ANNEXE'],['D-104','RÉVISION 2','ANNEXE NOMINATIVE'],['D-104','RÉVISION 2','SANS ANNEXE']],3,['La révision est 1.','La référence est D-140.','L’annexe nominative doit être exclue.','Référence, révision et absence d’annexe correspondent.']],
 ['doublon','Donnée de référence : « Temba | terrain | +228 91 74 68 32 ». Une copie diffère sur exactement DEUX champs. Laquelle ?',
  [['Temba','achats','+228 91 74 68 32'],['Tempa','achats','+228 91 74 68 32'],['Temba','terrain','+228 91 74 86 32'],['Tempa','terrain','+228 91 74 68 32']],1,['Un seul champ diffère : la fonction.','Nom et fonction diffèrent ; le téléphone est identique.','Un seul champ diffère : le téléphone.','Un seul champ diffère : le nom.']],
 ['statuts','Le rapport doit compter les opérations APPROUVÉES et DÉCAISSÉES dont le contrôle est CLOS. Choisis une ligne à inclure.',
  [['APPROUVÉE','À DÉCAISSER','CLOS'],['EN INSTRUCTION','DÉCAISSÉE','CLOS'],['APPROUVÉE','DÉCAISSÉE','OUVERT'],['APPROUVÉE','DÉCAISSÉE','CLOS']],3,['Le décaissement est à faire.','L’instruction n’est pas l’approbation.','Le contrôle est ouvert.','Les trois états demandés sont réalisés.']],
 ['lieu','L’invitation concerne Kara, session DU MATIN, groupe RELAIS. Sélectionne le bon enregistrement.',
  [['Kara','MATIN','RELAIS'],['Kara','SOIR','RELAIS'],['Kpalimé','MATIN','RELAIS'],['Kara','MATIN','CONSEILLERS']],0,['Les trois champs correspondent.','La session est le soir.','La localité est Kpalimé.','Le groupe est CONSEILLERS.']],
 ['ordre','Instruction : contrôler d’abord la VERSION, puis le CONSENTEMENT, enfin l’IDENTIFIANT. Quel journal respecte cet ordre exact ?',
  [['VERSION','IDENTIFIANT','CONSENTEMENT'],['CONSENTEMENT','VERSION','IDENTIFIANT'],['VERSION','CONSENTEMENT','IDENTIFIANT'],['IDENTIFIANT','CONSENTEMENT','VERSION']],2,['Les deux derniers contrôles sont inversés.','Les deux premiers contrôles sont inversés.','L’ordre correspond à l’instruction.','L’ordre est inversé.']],
 ['union','Un candidat est admissible s’il est membre ACTIF et possède soit une CARTE soit une ATTESTATION. Les deux titres sont acceptés. Choisis le candidat admissible.',
  [['INACTIF','CARTE','ATTESTATION'],['ACTIF','AUCUNE CARTE','ATTESTATION'],['ACTIF','AUCUNE CARTE','AUCUNE ATTESTATION'],['À ACTIVER','CARTE','ATTESTATION']],1,['Les titres ne compensent pas l’inactivité.','Actif et attestation suffisent ; la carte n’est pas nécessaire.','Aucun des titres n’est disponible.','À activer n’est pas actif.']],
 ['exclusion','Diffusion permise : synthèse ANONYME, statut FINAL, destinataire PARTENAIRE HABILITÉ. Trouve l’envoi conforme.',
  [['NOMINATIVE','FINAL','PARTENAIRE HABILITÉ'],['ANONYME','PROJET','PARTENAIRE HABILITÉ'],['ANONYME','FINAL','PARTENAIRE NON HABILITÉ'],['ANONYME','FINAL','PARTENAIRE HABILITÉ']],3,['La synthèse est nominative.','Le statut est PROJET.','Le destinataire n’est pas habilité.','Les trois restrictions sont satisfaites.']],
 ['exact','Référence à vérifier : « ASS-014-L0 ». La lettre finale est L suivie du chiffre zéro. Quelle ligne est identique ?',
  [['ASS-014-L0','VÉRIFIÉ','FINAL'],['ASS-014-LO','VÉRIFIÉ','FINAL'],['ASS-041-L0','VÉRIFIÉ','FINAL'],['AS5-014-L0','VÉRIFIÉ','FINAL']],0,['La référence est exacte.','La terminaison contient la lettre O au lieu du chiffre 0.','014 est devenu 041.','Le second S est devenu 5.']],
 ['circuit','À traiter : plainte ENREGISTRÉE, canal TÉLÉPHONE, réponse NON ENVOYÉE. Choisis la ligne correspondante.',
  [['À ENREGISTRER','TÉLÉPHONE','NON ENVOYÉE'],['ENREGISTRÉE','FORMULAIRE','NON ENVOYÉE'],['ENREGISTRÉE','TÉLÉPHONE','NON ENVOYÉE'],['ENREGISTRÉE','TÉLÉPHONE','ENVOYÉE']],2,['L’enregistrement est à faire.','Le canal est FORMULAIRE.','Les trois critères correspondent.','La réponse a été envoyée.']]
];
for(const [id,fr,rows,a,why] of DETAIL_CASES){
 const o=rows.map((_,i)=>`Ligne ${String.fromCharCode(65+i)}`);
 const table=`<div class="table-scroll"><table><caption>Tableau à vérifier</caption><thead><tr><th>Ligne</th><th>Champ 1</th><th>Champ 2</th><th>Champ 3</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><th>${String.fromCharCode(65+i)}</th>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 expertCase(`d-${id}`,'reason',fr,o,a,why[a],why,{kind:'detail',trap:'detail',table,targetSeconds:45,detailRows:rows});
}

const SJT_CASES=[
 ['alerte','La direction attend ce soir une synthèse pour décider d’un décaissement. Deux sources officielles donnent des statuts différents pour une condition préalable. Le responsable de la donnée est joignable, et tu peux encore mettre à jour la synthèse. Quelle première réponse est la plus solide ?',
  ['Utiliser la source la plus récente et expliquer le choix dans une note à la direction.','Demander au responsable de rapprocher les preuves, signaler l’incertitude et actualiser la synthèse avant décision.','Reporter toute la synthèse jusqu’à réception d’une attestation signée par les deux services.','Retenir le statut le plus prudent et laisser au comité la responsabilité de le rectifier.'],1,
  ['La récence ne suffit pas à résoudre une contradiction sur une condition décisive.','La vérification reste possible ; rendre visible l’incertitude protège la décision sans bloquer inutilement le travail.','L’attestation des deux services n’est pas une exigence posée et peut empêcher une clarification disponible.','Un choix prudent mais non vérifié peut être faux et ne résout pas la divergence.']],
 ['plainte','Une coopérative signale que le partenaire d’exécution exclut certaines femmes de réunions essentielles. Le partenaire conteste les faits. Tu n’as pas encore vérifié la situation et une rencontre est prévue demain. Que fais-tu en priorité ?',
  ['Demander au partenaire de présenter demain son bilan de participation et discuter de ses conclusions.','Organiser demain une confrontation publique entre la coopérative et le partenaire pour clarifier les faits.','Recueillir les faits par un canal accessible et confidentiel, puis faire examiner l’alerte par le responsable compétent.','Suspendre immédiatement tout le programme et informer les bénéficiaires que l’exclusion est établie.'],2,
  ['Les seuls chiffres du partenaire ne suffisent pas à comprendre une exclusion contestée.','Une confrontation publique peut exposer les plaignantes et empêcher une expression libre.','L’écoute protégée et la vérification permettent une réponse proportionnée sans présumer du résultat.','Il faut traiter l’alerte sérieusement sans présenter comme établi ce qui reste à vérifier.']],
 ['cadeau','À la veille d’une sélection de prestataires, un candidat t’offre une invitation professionnelle dont la valeur n’est pas claire. Tu n’es pas seul décideur, mais tu contribues à l’analyse. Quelle démarche protège le mieux l’impartialité ?',
  ['Décliner l’avantage, en informer le canal compétent et vérifier les mesures nécessaires pour poursuivre l’analyse impartialement.','Accepter seulement si le candidat confirme par écrit que l’invitation est ouverte à tous les analystes.','Transférer l’invitation à un collègue qui ne vote pas, puis poursuivre normalement ton analyse.','Conserver l’invitation sans l’utiliser avant la fin de la sélection et la mentionner ensuite.'],0,
  ['La contribution à l’analyse suffit à justifier le traitement transparent d’un avantage offert.','L’ouverture à plusieurs analystes ne supprime pas le risque d’influence.','Le transfert maintient l’avantage et évite sa gestion officielle.','Reporter la déclaration laisse subsister un risque pendant la sélection.']],
 ['delegation','Une tâche urgente exige une validation que tu n’es pas habilité à donner. Le signataire habituel est absent, mais un délégataire formel est disponible. Une équipe propose ton accord provisoire pour éviter un retard. Que fais-tu ?',
  ['Donner ton accord provisoire et faire régulariser la signature par le délégataire plus tard.','Attendre le retour du signataire habituel pour préserver la cohérence de toutes les validations.','Demander à l’équipe de considérer le dossier comme validé à condition de ne pas encore l’envoyer.','Transmettre les éléments au délégataire habilité et organiser avec lui la validation dans le délai.'],3,
  ['La régularisation ultérieure ne crée pas ton habilitation.','Un délégataire formel est disponible : l’attente n’est pas nécessaire.','Une validation informelle reste une décision sans habilitation, même avant l’envoi.','Cette voie respecte la responsabilité de validation et permet de tenir le délai.']],
 ['equipe','Ton collègue livre une analyse incomplète avant une réunion importante. Il dit avoir suivi un cadrage différent, validé par un autre responsable. Il reste du temps pour corriger les points critiques, mais pas pour tout refaire. Quelle réponse est la plus utile ?',
  ['Présenter ton propre cadrage comme la référence et refaire les parties manquantes sans solliciter le collègue.','Recaler rapidement les attendus avec les responsables, répartir les corrections critiques et signaler les limites restantes.','Reporter la réunion et demander une nouvelle analyse intégrale conforme à ton cadrage.','Conserver l’analyse reçue et préciser à la réunion qu’elle reflète le cadrage de l’autre responsable.'],1,
  ['Cela peut reproduire une divergence de cadrage et écarter l’expertise utile du collègue.','La clarification, la priorisation et la transparence traitent le conflit d’attendus dans le temps disponible.','Le scénario permet encore les corrections essentielles ; une reprise totale est disproportionnée.','Attribuer la responsabilité ne rend pas l’analyse exploitable.']],
 ['terrain','Deux sites demandent une visite à la même date. Le premier présente une alerte de sécurité à vérifier ; le second attend une visite de routine déjà promise. Une équipe qualifiée peut couvrir le second si tu lui transmets le dossier. Que privilégies-tu ?',
  ['Maintenir la visite promise et demander au premier site un rapport détaillé pour la semaine suivante.','Annuler les deux visites et demander à la direction de choisir un site prioritaire.','Vérifier l’urgence, organiser une réponse qualifiée au premier site et coordonner la visite du second avec l’équipe disponible.','Visiter successivement les deux sites en réduisant chaque visite pour respecter les promesses.'],2,
  ['Une promesse de routine ne suffit pas à justifier le retard de traitement d’une alerte de sécurité.','Une alternative opérationnelle permet de couvrir les deux besoins.','La priorité au risque et la délégation coordonnée préservent les obligations utiles.','Réduire les visites sans examiner les besoins risque de compromettre leur qualité.']],
 ['chiffres','Une erreur de consolidation modifie un chiffre déjà transmis à un partenaire. Tu as identifié la source et la valeur correcte. Le partenaire doit utiliser le document dans une réunion prochaine. Quelle réponse est la plus appropriée ?',
  ['Faire corriger et transmettre une version clairement identifiée, expliquer l’effet de l’erreur et demander le remplacement du document.','Remplacer silencieusement le document partagé afin que le partenaire utilise désormais la bonne version.','Attendre la revue mensuelle, puis inclure le chiffre correct avec les autres mises à jour.','Envoyer le chiffre corrigé au partenaire et conserver le document pour garder la trace de la première version.'],0,
  ['La correction doit être traçable et exploitable avant la réunion.','La correction silencieuse ne garantit pas que le partenaire remplace sa copie.','Attendre expose la réunion à une information erronée connue.','Le maintien sans identification claire des deux versions entretient une incohérence.']],
 ['confidentialite','Un partenaire habilité à recevoir une synthèse te demande la liste nominative complète pour une analyse urgente. Ton mandat de partage ne couvre que les statistiques anonymes. Une extension d’accès peut être examinée par le responsable des données. Que fais-tu ?',
  ['Transmettre la liste sous mot de passe et demander au partenaire de limiter son usage à cette analyse.','Transmettre uniquement les noms, car les données sensibles sont dans les autres colonnes du registre.','Refuser toute collaboration avec le partenaire jusqu’à la prochaine revue complète de son habilitation.','Fournir la synthèse autorisée et faire examiner la demande nominative selon sa finalité et les droits d’accès.'],3,
  ['Un mot de passe ne remplace pas l’autorisation de partage.','Les noms restent des données nominatives au-delà du mandat donné.','La synthèse autorisée permet de poursuivre la collaboration.','Cette réponse satisfait le besoin permis tout en traitant l’extension de manière contrôlée.']],
 ['pression','Une autorité locale demande d’ajouter un site à une liste approuvée. Le besoin semble réel, mais les critères et la capacité budgétaire n’ont pas été examinés pour ce site. La procédure autorise les demandes complémentaires. Quelle réponse est la plus constructive ?',
  ['Ajouter le site sous réserve de confirmation budgétaire et expliquer au comité la nécessité locale.','Enregistrer la demande, la soumettre aux mêmes critères et préciser qu’aucun ajout n’est acquis avant décision.','Exclure définitivement le site pour éviter que la pression locale influence le programme.','Demander au site de mobiliser sa contribution avant d’examiner les autres critères d’admissibilité.'],1,
  ['Une réserve financière ne remplace pas l’examen et la décision requis.','Le besoin peut être examiné sans contourner l’équité ni promettre une sélection.','La pression ne justifie pas à elle seule un rejet définitif d’un besoin recevable.','Une contribution anticipée peut créer une attente sans examen des critères.']],
 ['innovation','Un outil nouveau réduit le temps de saisie dans un pilote. L’équipe veut l’imposer sur tous les sites, mais certains ont une faible connexion et aucune mesure de qualité des données n’a été faite. Quelle suite est la plus solide ?',
  ['Étendre immédiatement l’outil et corriger les problèmes de connexion à mesure qu’ils apparaissent.','Conserver définitivement l’ancien outil pour éviter les risques d’une nouvelle méthode.','Tester qualité et faisabilité sur des sites variés, prévoir une solution hors ligne et décider de l’extension sur ces résultats.','Étendre uniquement aux sites connectés et considérer leur résultat comme représentatif de tous les sites.'],2,
  ['Le gain de temps ne prouve ni la qualité ni l’utilisabilité universelle.','Une innovation utile mérite une validation ciblée, pas un rejet définitif.','La vérification élargie répond aux deux incertitudes et garde la possibilité d’innover.','Une sélection des sites les mieux connectés limite la généralisation.']],
 ['retour','Un responsable formule devant l’équipe une critique que tu estimes inexacte. Le désaccord concerne une méthode et la réunion porte sur une décision urgente. Quelle réaction préserve le mieux la qualité du travail ?',
  ['Clarifier brièvement le point factuel utile à la décision, puis convenir d’un échange séparé sur la méthode avec les pièces disponibles.','Répondre point par point à toute la critique pendant la réunion pour corriger immédiatement l’image de ton travail.','Accepter la critique sans clarification et modifier ensuite l’analyse pour satisfaire le responsable.','Demander à l’équipe de choisir laquelle des deux méthodes lui semble la plus crédible.'],0,
  ['La correction factuelle utile protège la décision ; l’échange séparé permet un examen complet sans accaparer la réunion.','Une défense exhaustive peut faire perdre l’objectif urgent.','L’acceptation sans examen peut dégrader la qualité de l’analyse.','Un vote d’opinion ne remplace pas la comparaison des méthodes et des preuves.']],
 ['risque','Un fournisseur propose de remplacer une pièce indisponible par un composant présenté comme équivalent. Le calendrier est tendu et tu n’as pas la compétence technique pour confirmer l’équivalence. Un spécialiste du projet est disponible. Que fais-tu ?',
  ['Accepter si le fournisseur garantit par écrit qu’il remplacera la pièce en cas de problème.','Refuser toute substitution jusqu’à la disponibilité de la pièce prévue initialement.','Demander aux usagers si le composant leur semble acceptable et valider sur leur accord.','Faire vérifier l’équivalence et ses impacts par le spécialiste, puis suivre la validation applicable avant substitution.'],3,
  ['La garantie du fournisseur ne remplace pas la vérification technique et la validation.','Une substitution acceptable peut éviter le retard après examen compétent.','Les usagers apportent un avis utile, mais pas la validation technique manquante.','Cette réponse traite le risque sans inventer une compétence ni bloquer une solution possible.']]
];
for(const [id,fr,o,a,why] of SJT_CASES)expertCase(`s-${id}`,'sjt',fr,o,a,why[a],why,{source:'yppskills',targetSeconds:65});

SOURCES.guarantees={title:'BAD — garanties et mobilisation des capitaux',url:'https://www.afdb.org/en/projects-and-operations/financial-products/african-development-bank/guarantees',date:'Consulté le 1er octobre 2026'};
SOURCES.additionality={title:'BAD — opérations non souveraines et additionnalité',url:'https://www.afdb.org/en/private-sector/how-work-us',date:'Consulté le 1er octobre 2026'};
SOURCES.safeguards={title:'BAD — Système de sauvegardes intégré actualisé',url:'https://www.afdb.org/en/news-and-events/press-releases/african-development-bank-groups-updated-integrated-safeguards-system-iss-becomes-effective-71539',date:'Consulté le 1er octobre 2026'};
const BANK_CASES=[
 ['addition','Une opération privée rentable dispose déjà de financement commercial aux mêmes conditions que l’appui proposé par la BAD. Aucun apport technique ou effet catalytique supplémentaire n’est identifié. Quelle question manque avant de justifier l’intervention ?',
  ['Quel avantage financier ou non financier la participation apporte-t-elle au-delà de ce que le marché fournirait seul ?','Le promoteur peut-il accroître sa marge en remplaçant le financement commercial par les ressources proposées ?','Le projet appartient-il à un secteur prioritaire, même si les conditions disponibles restent identiques ?','Le projet possède-t-il déjà une capacité de remboursement suffisante pour les prêteurs commerciaux ?'],0,
  ['L’additionnalité examine la valeur supplémentaire de l’intervention.','Une meilleure marge privée ne démontre pas une contribution additionnelle au développement.','L’alignement sectoriel est utile mais ne répond pas à l’absence d’additionnalité.','La viabilité est posée ; elle ne suffit pas à justifier l’apport de la Banque.'],'additionality'],
 ['garantie','Des prêteurs envisagent un projet viable mais craignent la non-exécution d’une obligation contractuelle de l’autorité publique. Le promoteur demande de couvrir aussi tout risque commercial. Quel cadrage répond au risque identifié ?',
  ['Accorder une subvention couvrant les revenus commerciaux futurs pour supprimer toute incertitude de recettes.','Étudier une couverture ciblée de l’obligation publique, en précisant exclusions, responsabilités et risques restant aux parties.','Garantir tous les risques de l’opération pour éviter que les prêteurs demandent une analyse complémentaire.','Financer exclusivement les équipements et considérer l’exécution de l’obligation publique comme un sujet séparé.'],1,
  ['La subvention de revenus ne cible pas le défaut d’obligation publique.','Les garanties de risque peuvent cibler l’exécution d’obligations publiques ; leur couverture n’est pas automatiquement universelle.','Une garantie ciblée ne supprime ni les limites contractuelles ni l’analyse des risques commerciaux.','Les équipements ne résolvent pas le risque posé.'],'guarantees'],
 ['integration','Deux pays disposent d’une liaison routière, mais les camions restent bloqués par des procédures incompatibles et des contrôles successifs. Quelle composante complète le mieux l’investissement physique dans l’objectif « Intégrer l’Afrique » ?',
  ['Ajouter un nouveau tronçon parallèle pour augmenter la capacité physique disponible aux frontières.','Subventionner temporairement le carburant des transporteurs opérant sur le corridor existant.','Coordonner les procédures et les organismes frontaliers pour rendre la liaison effectivement utilisable.','Mesurer uniquement les kilomètres réalisés afin de comparer les deux investissements nationaux.'],2,
  ['Le goulot décrit est procédural.','La subvention réduit un coût mais ne traite pas les incompatibilités.','L’intégration combine la connexion physique et les conditions de circulation effective.','Un indicateur de réalisation ne traite pas le blocage.'],'regional2026'],
 ['high5','Un programme associe irrigation, transformation locale et accès aux marchés régionaux. Quel raisonnement évite de réduire son intérêt stratégique à une seule étiquette High 5 ?',
  ['Retenir uniquement l’irrigation car le premier investissement détermine toutes les priorités du programme.','Retenir uniquement l’industrialisation car la transformation annule les objectifs de production agricole.','Attribuer automatiquement les cinq priorités sans expliquer les mécanismes de contribution.','Relier les composantes à leurs résultats attendus en agriculture, valeur ajoutée et intégration régionale.'],3,
  ['L’ordre des investissements ne résume pas leurs contributions.','Une composante de transformation ne supprime pas le lien à l’agriculture.','Une liste sans mécanisme n’établit pas la contribution.','Un projet peut servir plusieurs priorités avec des liens explicites.'],'strategy'],
 ['concession','Un pays admissible a de faibles capacités de financement et un important besoin de développement. On examine le guichet concessionnel du Groupe BAD. Quelle distinction institutionnelle est correcte ?',
  ['Le FAD est le guichet concessionnel du Groupe ; son appui ne dispense pas d’examiner la viabilité et les résultats.','Le FAD est le guichet commercial réservé aux sociétés privées capables d’emprunter sans garantie souveraine.','Le FAD remplace les autorités nationales pour toutes les décisions de politique budgétaire des pays soutenus.','Le FAD finance chaque opération admissible automatiquement, sans analyse de la capacité d’exécution.'],0,
  ['La concessionnalité décrit les conditions du guichet et non une absence d’examen.','Cette description ne correspond pas au guichet concessionnel.','Un appui de développement ne transfère pas toutes les décisions souveraines.','L’admissibilité du pays ne rend pas chaque opération automatique.'],'adf'],
 ['emploi','Un projet de formation annonce un nombre élevé de participants. Dans la logique d’amélioration de la qualité de vie, quelle vérification relie le mieux cette réalisation à l’objectif d’emploi ?',
  ['Comparer le nombre de salles ouvertes entre les centres de formation partenaires.','Examiner l’insertion et la qualité des emplois, en tenant compte des profils et des obstacles rencontrés.','Comparer uniquement le nombre de certificats imprimés aux prévisions de l’équipe.','Additionner les heures de formation pour établir directement le nombre d’emplois créés.'],1,
  ['Les salles renseignent sur les moyens, pas l’emploi.','L’insertion et la qualité des emplois sont plus proches du résultat recherché.','Un certificat n’établit pas une insertion.','Des heures ne se convertissent pas automatiquement en emplois.'],'strategy'],
 ['energie','Un projet d’électrification a livré des branchements, mais des coupures et des coûts élevés empêchent les entreprises locales d’utiliser le service. Quel suivi répond le mieux à l’objectif de développement ?',
  ['Le nombre de branchements réalisés, utilisé comme indicateur suffisant de transformation économique.','Le volume total investi, utilisé comme preuve d’amélioration des activités productives.','L’accès effectif, la fiabilité, l’abordabilité et les usages productifs, en plus des branchements.','La capacité nominale installée, sans information sur le service reçu par les entreprises.'],2,
  ['Une connexion matérielle ne suffit pas à démontrer un usage utile.','Une dépense ne démontre pas le service ni ses effets.','Le suivi doit examiner si l’accès permet effectivement les usages attendus.','La capacité nominale ne mesure pas le service fourni.'],'mission'],
 ['sauvegardes','Une opération de transport peut améliorer l’accès au marché, mais risque aussi d’affecter des terres et des moyens de subsistance. Quelle lecture des sauvegardes environnementales et sociales est correcte ?',
  ['L’intérêt économique rend inutile l’analyse des impacts négatifs avant l’exécution.','Les sauvegardes s’appliquent uniquement si l’opération est entièrement financée par le secteur public.','Les sauvegardes consistent uniquement à vérifier que le chantier respecte son budget.','L’analyse et la gestion des impacts accompagnent l’opération, avec prise en compte des personnes affectées.'],3,
  ['Un bénéfice économique ne supprime pas les impacts à examiner.','Les risques ne disparaissent pas du fait de la modalité de financement.','L’exécution financière ne remplace pas les exigences environnementales et sociales.','Les sauvegardes relient le développement à la prévention et à la gestion des impacts.'],'safeguards'],
 ['finance','Une garantie publique attire des capitaux privés sur une opération. Quelle information est nécessaire pour apprécier son effet catalytique sans confondre financement total et financement mobilisé ?',
  ['La participation privée additionnelle attribuable au mécanisme, les risques assumés et les conditions de l’opération.','Le montant total du projet, considéré comme entièrement mobilisé par la garantie proposée.','Le nombre de partenaires présents à la cérémonie de signature du dispositif.','Le seul montant nominal de la garantie, supposé égal au capital privé engagé.'],0,
  ['L’effet catalytique demande de distinguer la participation additionnelle et les risques transférés.','Le financement total inclut des ressources qui peuvent ne pas être causées par le mécanisme.','Une participation à une cérémonie n’est pas un engagement financier.','Garantie et capitaux engagés ne sont pas des montants automatiquement identiques.'],'additionality'],
 ['strategie','L’équipe doit relier un projet à la Stratégie décennale 2024–2033. Le projet accroît la production, mais les groupes vulnérables risquent d’être exclus et les équipements sont exposés aux inondations. Quelle analyse est la plus complète ?',
  ['Conclure à l’alignement dès que le volume de production augmente.','Examiner les résultats de croissance avec l’inclusion, la résilience et les modalités de mise en œuvre.','Remplacer le suivi économique par une description exclusivement environnementale.','Reporter toute analyse de vulnérabilité après la fin du financement.'],1,
  ['Une croissance isolée ne répond pas aux risques d’exclusion et de fragilité.','L’alignement doit examiner les résultats et les dimensions transversales de la stratégie.','Les dimensions économiques restent pertinentes.','Les risques doivent informer la conception et l’exécution.'],'strategy'],
 ['cycle','Une annonce officielle confirme l’approbation d’une opération. Un candidat écrit que les bénéficiaires ont déjà reçu l’ensemble des résultats promis. Quelle correction est la plus précise ?',
  ['Remplacer « approuvé » par « annoncé » et conserver l’ensemble des résultats comme atteints.','Affirmer que l’opération a échoué puisqu’aucun résultat n’est décrit dans l’annonce.','Distinguer l’approbation des décaissements, de l’exécution et des résultats effectivement observés.','Supprimer toutes les informations sur l’opération car une approbation ne vaut aucune information.'],2,
  ['Changer le verbe ne vérifie pas les résultats.','Le manque de résultat décrit ne prouve pas un échec.','Les étapes sont distinctes et nécessitent des preuves différentes.','L’approbation est un fait utile, sans prouver tout le reste.'],'news'],
 ['nonso','Une entreprise publique sollicite un financement sans garantie gouvernementale. Quel point évite une classification automatique de l’opération à partir de la seule propriété de l’entreprise ?',
  ['Toute entreprise publique implique forcément une garantie souveraine, même non prévue au contrat.','L’absence de garantie élimine toute analyse de l’éligibilité et des risques de l’entreprise.','Une opération privée exige toujours que l’État ne possède aucune part dans l’entreprise.','Examiner l’éligibilité de l’entité et la structure de financement, notamment l’absence de garantie souveraine.'],3,
  ['La propriété publique ne crée pas automatiquement la garantie.','L’absence de garantie ne dispense pas de l’examen.','Certaines entités publiques admissibles peuvent accéder aux opérations non souveraines.','La structure de l’opération et l’éligibilité doivent être examinées.'],'additionality']
];
for(const [id,fr,o,a,why,source] of BANK_CASES)expertCase(`b-${id}`,'afdb',fr,o,a,why[a],why,{source});

const DEVELOPMENT_CASES=[
 ['climat','Une zone agricole connaît une forte variabilité des pluies. Un système d’irrigation dépend lui-même d’une ressource en eau fragile. Quelle décision renforce la résilience sans déplacer le risque ?',
  ['Évaluer la disponibilité durable de l’eau, les usages concurrents et la maintenance avant de fixer la solution.','Dimensionner l’ouvrage seulement sur la surface à irriguer afin de maximiser la production potentielle.','Garantir les mêmes volumes d’eau chaque saison sans tenir compte des conditions hydrologiques.','Retenir une technologie identique sur tous les sites pour simplifier les futurs contrats.'],0,
  ['La résilience exige d’examiner la dépendance et les contraintes de la ressource.','La surface ne suffit pas à établir la ressource disponible.','Une promesse ne crée pas une ressource durable.','La standardisation ne répond pas aux différences hydrologiques.']],
 ['dette','Un État finance un équipement de long terme par une dette à refinancer rapidement. Les recettes du projet arrivent tard et restent incertaines. Quel risque est le plus directement décrit ?',
  ['Un risque de confusion entre production agricole et activité industrielle.','Un risque de refinancement et de décalage entre échéances de dette et flux disponibles.','Un risque nécessairement éliminé dès que le projet est économiquement utile.','Un risque exclusivement lié à la présence d’un prêteur étranger.'],1,
  ['Le secteur n’est pas le décalage posé.','L’échéance peut arriver avant les ressources nécessaires au remboursement.','L’utilité n’assure pas la disponibilité des flux à chaque échéance.','Un tel décalage peut exister aussi avec un prêteur domestique.']],
 ['genre','Un programme de crédit augmente les prêts à des entreprises dirigées par des femmes, mais certaines bénéficiaires ne contrôlent pas l’utilisation des fonds. Quelle mesure complète le mieux le suivi de volume ?',
  ['Le nombre total de dossiers instruits par l’établissement prêteur.','Le volume global des prêts accordés à tous les emprunteurs de la zone.','Le contrôle effectif des ressources, leur usage productif et les résultats pour les bénéficiaires.','Le seul nombre de signatures présentes sur les contrats de prêt.'],2,
  ['L’instruction est un processus, pas le contrôle des ressources.','Un agrégat global peut masquer la situation des bénéficiaires.','L’inclusion exige de regarder l’accès effectif et le pouvoir d’usage.','Une signature ne démontre pas le contrôle effectif.']],
 ['commerce','Un pays produit davantage de denrées exportables, mais les rejets à la frontière augmentent pour non-conformité. Quelle intervention traite le plus directement ce problème ?',
  ['Financer l’extension de la surface cultivée pour compenser les volumes rejetés.','Réduire le coût de stockage sans examiner les motifs de non-conformité.','Augmenter les subventions aux exportateurs selon leur volume déclaré.','Renforcer qualité, traçabilité et respect des exigences applicables aux marchés visés.'],3,
  ['Produire plus ne corrige pas la non-conformité.','Le stockage peut contribuer à la qualité, mais il faut traiter les motifs établis.','Une subvention de volume peut laisser le problème intact.','Cette intervention répond à la cause des rejets.']],
 ['emploi','Une subvention vise l’emploi durable des jeunes. Des placements sont annoncés, mais les départs sont fréquents après la fin de la subvention. Quelle question vérifie la durabilité ?',
  ['Quelle est la rétention après l’appui, avec quels revenus, conditions et perspectives d’activité ?','Combien de logos des entreprises partenaires figurent sur les supports du programme ?','Combien de jeunes ont reçu un message confirmant leur inscription au dispositif ?','Combien d’heures les équipes ont consacré aux réunions de placement ?'],0,
  ['La rétention et la qualité de l’activité décrivent la durabilité recherchée.','La visibilité des partenaires ne prouve pas l’emploi durable.','L’inscription ne garantit pas une activité conservée.','Le temps de gestion ne mesure pas la persistance de l’emploi.']],
 ['fragilite','Un ouvrage d’eau bénéficie à plusieurs communautés dont les droits d’accès sont contestés. La solution technique est validée, mais les règles de partage ne le sont pas. Quel risque reste décisif ?',
  ['Le seul risque que l’ouvrage soit plus grand que les autres ouvrages de la région.','Un risque de conflit et d’exclusion si les règles d’accès et les responsabilités restent contestées.','Un risque nécessairement nul puisque la technologie a été validée.','Un risque limité au coût d’achat initial des équipements.'],1,
  ['La taille comparative n’est pas le risque posé.','L’usage durable dépend aussi d’accords légitimes sur l’accès.','La validation technique ne résout pas les tensions sociales.','Les règles contestées dépassent le coût initial.']],
 ['mobilisation','Un pays veut accroître ses ressources domestiques en améliorant le recouvrement fiscal. Les entreprises soulignent la complexité et l’incertitude des procédures. Quelle combinaison répond au besoin sans ignorer cette contrainte ?',
  ['Augmenter les prélèvements sans modifier les procédures ni la qualité du service.','Remplacer durablement les recettes domestiques par des emprunts à court terme.','Améliorer l’assiette, la prévisibilité, le service et la conformité tout en examinant les effets sur l’activité.','Exiger que les entreprises financent elles-mêmes l’ensemble de la réforme administrative.'],2,
  ['Un taux plus élevé ne corrige pas la complexité du système.','Le refinancement court ne remplace pas durablement la mobilisation domestique.','La collecte et un environnement prévisible peuvent être améliorés ensemble.','Cela ne décrit pas une réforme opérationnelle du système fiscal.']],
 ['numerique','Une application de conseil atteint beaucoup de téléchargements, mais les utilisateurs ruraux disposent de peu de connexion et ne l’utilisent presque plus. Quel changement répond au diagnostic ?',
  ['Augmenter uniquement le budget publicitaire pour obtenir davantage de téléchargements.','Mesurer uniquement le nombre de fonctionnalités ajoutées par les développeurs.','Réserver toutes les fonctionnalités aux téléphones les plus récents disponibles.','Adapter l’accès hors ligne ou à faible débit et vérifier les usages et décisions réellement améliorés.'],3,
  ['La publicité ne résout pas l’obstacle d’usage.','Le volume de fonctionnalités ne prouve pas leur utilité.','La restriction peut aggraver l’exclusion.','L’adaptation et le suivi des usages répondent au besoin observé.']],
 ['assurance','Une assurance agricole déclenche le paiement à partir d’un indice climatique régional. Un producteur subit une perte importante, mais l’indice ne déclenche pas. Quel problème illustre ce scénario ?',
  ['Un risque de base entre le déclencheur indiciel et la perte réellement subie.','Une preuve que toute assurance climatique rembourse forcément chaque perte individuelle.','Un risque de remboursement du prêt qui disparaît dès la signature de l’assurance.','Une preuve que l’indice est toujours identique au rendement de chaque exploitation.'],0,
  ['L’indice peut ne pas refléter exactement la situation individuelle.','Le scénario décrit précisément l’absence de déclenchement.','L’assurance ne supprime pas automatiquement tout risque de crédit.','Un indice régional peut diverger du rendement individuel.']],
 ['logistique','Un centre de stockage moderne reste peu utilisé. Les producteurs vendent tôt pour couvrir des besoins de liquidité et les frais de dépôt sont mal compris. Quelle analyse est prioritaire ?',
  ['Conclure que les producteurs refusent la modernisation, sans examiner leurs contraintes.','Étudier les incitations, les besoins de liquidité et les conditions d’accès au stockage avant d’étendre l’équipement.','Construire davantage de centres identiques afin de créer une demande par la capacité disponible.','Mesurer seulement la capacité construite pour démontrer la réduction des pertes.'],1,
  ['Une faible utilisation peut être rationnelle face aux contraintes.','L’ouvrage doit répondre aux conditions économiques et pratiques d’utilisation.','La capacité supplémentaire peut rester inutilisée pour les mêmes raisons.','La capacité ne démontre pas les pertes évitées.']],
 ['impact','Un programme constate une hausse du revenu des participants pendant une hausse générale des prix agricoles. Quelle conclusion est la plus rigoureuse ?',
  ['La hausse observée mesure exactement l’effet du programme sur le revenu.','La hausse générale prouve que le programme n’a eu aucun effet.','La variation est observée, mais l’effet propre demande une comparaison crédible et un examen des autres influences.','Le nombre de participants suffit à isoler l’effet du changement de prix.'],2,
  ['Le contexte peut avoir contribué au changement.','Une influence externe possible n’exclut pas une contribution du programme.','Observation et attribution doivent être distinguées.','Un effectif ne crée pas un contrefactuel crédible.']],
 ['valeur','Une filière exporte une matière brute malgré une demande locale de transformation. L’électricité est irrégulière et les unités n’ont pas de débouchés contractualisés. Quel programme traite le mieux les contraintes conjointes ?',
  ['Subventionner seulement l’achat des machines pour faire apparaître une activité industrielle.','Augmenter seulement le volume brut exporté pour compenser l’absence de transformation.','Imposer une transformation locale immédiate sans modifier les conditions de production.','Combiner énergie fiable, capacités de transformation et accès commercial vérifié dans une séquence viable.'],3,
  ['La machine ne suffit pas sans énergie et clients.','L’exportation brute ne traite pas la demande de valorisation locale.','L’obligation ne rend pas les unités viables.','Les goulots sont complémentaires et doivent être traités ensemble.']]
];
for(const [id,fr,o,a,why] of DEVELOPMENT_CASES)expertCase(`a-${id}`,'africa',fr,o,a,why[a],why);
QUESTIONS.push(...EXPERT_QUESTIONS);
