const QUESTIONS=[
{id:1,d:'afdb',lv:1,fr:'Quel énoncé décrit le mieux la mission du Groupe de la Banque africaine de développement ?',en:'Which statement best describes the African Development Bank Group mission?',o:['Réduire la pauvreté et améliorer durablement les conditions de vie en Afrique en mobilisant des ressources pour le développement','Financer uniquement les gouvernements à revenu intermédiaire','Fixer les taux directeurs des banques centrales africaines','Gérer une monnaie commune africaine'],a:0,x:'La BAD est une institution multilatérale de financement du développement. Sa mission porte sur le développement économique durable et le progrès social de ses pays membres régionaux.'},
{id:2,d:'afdb',lv:1,fr:'La stratégie décennale actuellement en vigueur à la BAD couvre principalement quelle période ?',en:'The AfDB current Ten-Year Strategy mainly covers which period?',o:['2020–2030','2024–2033','2025–2035','2026–2036'],a:1,x:'La Ten-Year Strategy 2024–2033 constitue le cadre stratégique de long terme actuellement en vigueur.'},
{id:3,d:'afdb',lv:1,fr:'Lequel ne fait PAS partie des High 5 de la BAD ?',en:'Which is NOT one of the AfDB High 5 priorities?',o:['Éclairer et alimenter l’Afrique en énergie','Nourrir l’Afrique','Industrialiser l’Afrique','Créer une monnaie unique africaine'],a:3,x:'Les High 5 sont : Light up and Power Africa, Feed Africa, Industrialise Africa, Integrate Africa, Improve the Quality of Life for the People of Africa.'},
{id:4,d:'afdb',lv:2,fr:'Pourquoi les High 5 restent-ils importants sous la stratégie 2024–2033 ?',en:'Why do the High 5 remain important under the 2024–2033 strategy?',o:['Ils remplacent les objectifs stratégiques','Ils servent de priorités opérationnelles pour traduire la stratégie en résultats','Ils concernent seulement le secteur privé','Ils sont uniquement des indicateurs financiers'],a:1,x:'Les High 5 traduisent les ambitions stratégiques en domaines opérationnels concrets.'},
{id:5,d:'afdb',lv:2,fr:'Le nouveau cadre présenté en 2026 autour des « Four Cardinal Points » vise notamment à renforcer quoi ?',en:'The 2026 Four Cardinal Points framework notably aims to strengthen what?',o:['La mobilisation du capital africain, les systèmes financiers et les investissements','Une politique monétaire continentale unique','La suppression des banques nationales','Le financement exclusif des infrastructures routières'],a:0,x:'La nouvelle orientation met notamment l’accent sur la mobilisation des ressources africaines, la transformation du capital en investissement et le renforcement de l’architecture financière.'},
{id:7,d:'africa',lv:1,fr:'Un pays connaît une croissance réelle du PIB de 5 %, mais une croissance démographique de 3 %. Quel indicateur aide le mieux à juger l’amélioration moyenne du niveau de vie ?',en:'A country has 5% real GDP growth and 3% population growth. Which indicator best helps assess average living-standard improvement?',o:['PIB nominal total','Croissance du PIB réel par habitant','Exportations brutes','Réserves de change uniquement'],a:1,x:'Le PIB réel par habitant tient compte à la fois de la croissance réelle de la production et de la population.'},
{id:8,d:'africa',lv:2,fr:'Une forte dépendance aux exportations d’une seule matière première expose surtout un pays à :',en:'Heavy dependence on one commodity export mainly exposes a country to:',o:['Une baisse automatique de l’inflation','La volatilité des termes de l’échange et des recettes publiques','Une diversification immédiate','Une stabilité budgétaire accrue'],a:1,x:'La concentration des exportations augmente la vulnérabilité aux chocs de prix mondiaux.'},
{id:9,d:'africa',lv:2,fr:'Quel mécanisme favorise le plus directement l’intégration économique régionale ?',en:'Which mechanism most directly promotes regional economic integration?',o:['Augmenter les barrières non tarifaires','Réduire les coûts du commerce transfrontalier et harmoniser les règles','Limiter les infrastructures transfrontalières','Interdire les chaînes de valeur régionales'],a:1,x:'La réduction des frictions commerciales, l’harmonisation et la connectivité soutiennent les chaînes de valeur régionales.'},
{id:10,d:'africa',lv:2,fr:'Dans un projet d’irrigation, quel indicateur est le plus proche d’un résultat de développement plutôt que d’un simple produit ?',en:'In an irrigation project, which indicator is closer to a development outcome rather than an output?',o:['Nombre de pompes achetées','Kilomètres de canaux construits','Hausse du rendement et du revenu des exploitants ciblés','Nombre de contrats signés'],a:2,x:'Les équipements et ouvrages sont des outputs. L’évolution du rendement/revenu mesure davantage le changement produit chez les bénéficiaires.'},
{id:11,d:'reason',lv:1,fr:'Un portefeuille passe de 240 à 300 millions USD. Quel est le taux de croissance ?',en:'A portfolio rises from USD 240m to USD 300m. What is the growth rate?',o:['20 %','25 %','30 %','60 %'],a:1,x:'(300−240)/240 = 60/240 = 25 %.'},
{id:12,d:'reason',lv:2,fr:'Un programme de 48 M USD répartit 35 % à l’énergie et 25 % à l’agriculture. Le reste va à l’eau. Quel montant va à l’eau ?',en:'A USD 48m programme allocates 35% to energy and 25% to agriculture. The rest goes to water. How much goes to water?',o:['12,0 M','16,8 M','19,2 M','28,8 M'],a:2,x:'35 %+25 %=60 %. Reste=40 %. 48×0,40=19,2 M USD.'},
{id:13,d:'reason',lv:2,fr:'Trois projets ont des taux de décaissement de 60 %, 75 % et 90 %, avec budgets respectifs 10, 20 et 30 M. Quel est le taux pondéré global ?',en:'Three projects have disbursement rates of 60%, 75%, 90%, with budgets of 10, 20, 30m. What is the weighted overall rate?',o:['75 %','78 %','80 %','82,5 %'],a:2,x:'Décaissements=6+15+27=48 sur budget total 60, soit 80 %.'},
{id:14,d:'reason',lv:3,fr:'Une population cible est répartie en trois catégories sans chevauchement : 40 % de femmes de 35 ans ou plus, 35 % de jeunes hommes et le reste de jeunes femmes. Sur 12 000 bénéficiaires, combien sont de jeunes femmes ?',en:'A target population is 40% rural women, 35% young men, with the rest young women. Out of 12,000 beneficiaries, how many are young women?',o:['2 400','3 000','4 200','4 800'],a:1,x:'Reste = 25 %. 12 000 × 0,25 = 3 000.'},
{id:15,d:'sjt',lv:2,fr:'À la veille d’un rapport, vous découvrez que certaines données de résultats semblent exagérées. Votre supérieur veut soumettre immédiatement. Quelle est la meilleure première action ?',en:'Before a report deadline, you find some results data may be overstated. Your manager wants immediate submission. Best first action?',o:['Soumettre sans commentaire','Supprimer les données discrètement','Documenter rapidement l’anomalie, vérifier les faits et alerter le responsable avec une solution proportionnée','Contacter directement la presse'],a:2,x:'Une réponse professionnelle protège l’intégrité des données tout en respectant la chaîne de responsabilité : faits, vérification, transparence et solution.'},
{id:16,d:'sjt',lv:2,fr:'Un partenaire gouvernemental demande de contourner une procédure afin d’accélérer un décaissement urgent. Que faites-vous ?',en:'A government partner asks you to bypass a procedure to accelerate an urgent disbursement. What do you do?',o:['Accepter pour préserver la relation','Refuser sèchement et arrêter le projet','Clarifier l’urgence, identifier les voies accélérées autorisées et escalader si nécessaire sans contourner les contrôles','Ignorer le message'],a:2,x:'Il faut concilier résultats et conformité : comprendre le besoin, utiliser les mécanismes permis et escalader proportionnellement.'},
{id:17,d:'sjt',lv:3,fr:'Deux experts de cultures différentes sont en conflit et bloquent une mission. Quelle approche est la plus efficace ?',en:'Two experts from different cultural backgrounds are in conflict and blocking a mission. Most effective approach?',o:['Choisir immédiatement le plus expérimenté','Faciliter une discussion factuelle centrée sur l’objectif, clarifier les responsabilités et convenir d’actions mesurables','Éviter le conflit jusqu’à la fin','Remplacer les deux'],a:1,x:'L’approche privilégie écoute, faits, objectif commun, rôles clairs et résolution collaborative.'},
{id:18,d:'sjt',lv:3,fr:'Vous apprenez qu’un membre de l’équipe a un lien familial avec une entreprise soumissionnaire. Il affirme ne pas influencer la sélection. Quelle action est la plus appropriée ?',en:'You learn a team member is related to a bidding company. They say they do not influence selection. Most appropriate action?',o:['Ne rien faire sans preuve de fraude','Demander une déclaration du conflit potentiel et appliquer les règles de récusation/gestion prévues','Exclure automatiquement l’entreprise sans procédure','Publier le nom du collègue'],a:1,x:'Un conflit potentiel doit être déclaré et géré conformément aux règles, même sans preuve de faute.'},
{id:19,d:'africa',lv:3,fr:'Pourquoi le financement mixte (blended finance) peut-il être utilisé dans un projet de développement ?',en:'Why can blended finance be used in a development project?',o:['Pour éliminer tout risque','Pour utiliser des ressources concessionnelles de façon catalytique afin de mobiliser du capital additionnel lorsque le profil risque-rendement bloque l’investissement','Pour remplacer toute ressource privée','Pour éviter l’évaluation du projet'],a:1,x:'Le blended finance vise à améliorer le profil risque-rendement de manière ciblée afin de mobiliser des financements qui ne viendraient pas autrement.'},
{id:20,d:'reason',lv:3,fr:'Un projet devait toucher 80 000 personnes. Après 60 % de la durée, il en a touché 42 000. À rythme constant, quelle projection à 100 % ?',en:'A project planned to reach 80,000 people. After 60% of its duration it reached 42,000. At constant pace, what is the 100% projection?',o:['60 000','70 000','72 000','80 000'],a:1,x:'42 000 / 0,60 = 70 000. Cela indique un risque d’écart de 10 000 par rapport à la cible.'},
{id:21,d:'afdb',lv:2,fr:'Le Groupe de la BAD comprend notamment la BAD, le Fonds africain de développement et :',en:'The AfDB Group includes the AfDB, African Development Fund and:',o:['Le Fonds spécial du Nigeria','La Banque centrale africaine','La Commission de l’Union africaine','La BCEAO'],a:0,x:'Le Groupe comprend la Banque africaine de développement, le Fonds africain de développement et le Nigeria Trust Fund.'},
{id:22,d:'africa',lv:3,fr:'Un ratio dette/PIB augmente alors que le déficit primaire se réduit. Quelle explication reste plausible ?',en:'Debt-to-GDP rises while the primary deficit falls. Which explanation remains plausible?',o:['Une forte dépréciation de la monnaie sur une dette externe importante','Une hausse automatique des recettes','Une baisse de tous les taux d’intérêt','Une croissance nominale nécessairement plus forte'],a:0,x:'Une dépréciation peut augmenter en monnaie locale la valeur de la dette libellée en devises, même si le déficit primaire s’améliore.'},
{id:23,d:'reason',lv:2,fr:'Si 3 analystes examinent 18 dossiers en 6 heures au même rythme, combien 5 analystes examinent-ils en 4 heures ?',en:'If 3 analysts review 18 files in 6 hours at the same rate, how many can 5 analysts review in 4 hours?',o:['18','20','24','30'],a:1,x:'Productivité=18/(3×6)=1 dossier/analyste-heure. 5×4=20.'},
{id:24,d:'sjt',lv:2,fr:'Vous avez deux tâches urgentes : une note au Président dans 2 h et une demande routinière d’un collègue. Que faites-vous ?',en:'You have two urgent tasks: a note to the President in 2 hours and a colleague’s routine request. What do you do?',o:['Traiter dans l’ordre d’arrivée','Prioriser la note à fort impact/délai, informer le collègue et convenir d’un délai réaliste','Ignorer le collègue','Déléguer les deux sans suivi'],a:1,x:'La priorisation tient compte de l’impact et du délai, avec communication claire sur les attentes.'}
];
const DOMAINS={afdb:'BAD : mission & priorités',africa:'Développement africain',sjt:'Jugement situationnel',reason:'Raisonnement analytique'};
QUESTIONS.push({"id": "afdb-100", "d": "afdb", "lv": 2, "fr": "Quel guichet du Groupe fournit des financements concessionnels ?", "o": ["Le FAD", "Une banque centrale", "La ZLECAf", "Le Conseil de sécurité"], "a": 0, "x": "Le FAD est le guichet concessionnel du Groupe de la BAD.", "source": "adf"});
QUESTIONS.push({"id": "afdb-101", "d": "afdb", "lv": 2, "fr": "Mission 300 vise quel objectif ?", "o": ["300 millions de raccordements industriels en 2026", "300 millions d’Africains connectés à l’électricité d’ici 2030", "300 milliards de dollars décaissés", "300 centrales nucléaires"], "a": 1, "x": "La cible porte sur des personnes et une échéance de 2030, pas sur un montant ni un résultat déjà obtenu.", "source": "mission"});
QUESTIONS.push({"id": "afdb-102", "d": "afdb", "lv": 2, "fr": "Une interconnexion électrique entre pays contribue directement à quels High 5 ?", "o": ["Énergie et intégration", "Agriculture uniquement", "Santé uniquement", "Aucun"], "a": 0, "x": "Elle combine accès à l’énergie et connectivité régionale.", "source": "strategy"});
QUESTIONS.push({"id": "afdb-103", "d": "afdb", "lv": 2, "fr": "Quelle intervention illustre le mieux Industrialiser l’Afrique ?", "o": ["Exporter uniquement des produits bruts", "Remplacer les statistiques", "Transformer localement le cacao en produits à plus forte valeur ajoutée", "Limiter les entreprises locales"], "a": 2, "x": "La transformation locale développe la valeur ajoutée manufacturière.", "source": "strategy"});
QUESTIONS.push({"id": "afdb-104", "d": "afdb", "lv": 2, "fr": "Quel est le piège dans « Mission 300 a déjà connecté 300 millions de personnes » ?", "o": ["La cible est confondue avec un résultat", "Le terme personne est interdit", "2030 est une devise", "Une cible est toujours dépassée"], "a": 0, "x": "La source énonce une ambition à atteindre d’ici 2030. Elle ne prouve pas sa réalisation.", "source": "mission"});
QUESTIONS.push({"id": "afdb-105", "d": "afdb", "lv": 2, "fr": "Les High 5 comprennent-ils la qualité de vie ?", "o": ["Non, uniquement les routes", "Oui, améliorer la qualité de vie des populations africaines", "Seulement en Europe", "Uniquement les recettes fiscales"], "a": 1, "x": "La qualité de vie est l’une des cinq priorités opérationnelles.", "source": "strategy"});
QUESTIONS.push({"id": "afdb-106", "d": "afdb", "lv": 2, "fr": "Dans la stratégie 2024–2033, le climat doit être traité comment ?", "o": ["Comme un sujet transversal pertinent pour les opérations", "Uniquement après la clôture", "Uniquement dans les projets forestiers", "Comme une variable sans risque financier"], "a": 0, "x": "La croissance verte et la résilience impliquent de prendre en compte les risques et opportunités climatiques.", "source": "strategy"});
QUESTIONS.push({"id": "afdb-107", "d": "afdb", "lv": 2, "fr": "Qui porte la vision des quatre points cardinaux présentée aux Assemblées 2026 ?", "o": ["Le directeur d’une banque commerciale", "Le président Sidi Ould Tah", "Le secrétaire général de l’ONU", "Le président d’une coopérative"], "a": 1, "x": "La page des Assemblées annuelles attribue cette vision à Sidi Ould Tah.", "source": "annual"});
QUESTIONS.push({"id": "afdb-108", "d": "afdb", "lv": 2, "fr": "Que confirme la page des Assemblées annuelles 2026 sur cette vision ?", "o": ["L’abandon de tout financement", "Son approbation par les gouverneurs", "La disparition du FAD", "Une nouvelle monnaie mondiale"], "a": 1, "x": "La page officielle mentionne l’approbation des quatre points cardinaux par les gouverneurs.", "source": "annual"});
QUESTIONS.push({"id": "afdb-109", "d": "afdb", "lv": 2, "fr": "Une formation professionnelle reliée aux besoins des employeurs contribue surtout à :", "o": ["Améliorer la qualité de vie et les perspectives d’emploi", "Fixer les taux de change", "Remplacer toutes les entreprises", "Réduire les compétences"], "a": 0, "x": "Le capital humain et l’emploi s’inscrivent dans la qualité de vie.", "source": "strategy"});
QUESTIONS.push({"id": "afdb-110", "d": "afdb", "lv": 2, "fr": "Quel couple traduit les ambitions de la stratégie décennale ?", "o": ["Croissance verte inclusive et économies prospères et résilientes", "Croissance nominale seule et isolement", "Importations seules et monnaie unique", "Privatisation sans conditions et dette illimitée"], "a": 0, "x": "Il faut articuler inclusion, durabilité et résilience.", "source": "strategy"});
QUESTIONS.push({"id": "afdb-111", "d": "afdb", "lv": 2, "fr": "Quelle lecture évite de confondre les cadres de la BAD ?", "o": ["Quatre points cardinaux = cinq secteurs identiques", "Stratégie décennale, High 5 et vision présidentielle sont des cadres à distinguer", "Le FAD est une priorité High 5", "Mission 300 est une banque centrale"], "a": 1, "x": "Des cadres complémentaires peuvent avoir des fonctions différentes.", "source": "annual"});
QUESTIONS.push({"id": "afdb-112", "d": "afdb", "lv": 2, "fr": "Quel projet contribue directement à Nourrir l’Afrique ?", "o": ["Une chaîne de stockage réduisant les pertes alimentaires", "Un changement de logo", "Une restriction générale des semences", "Une spéculation sans production"], "a": 0, "x": "Les chaînes alimentaires plus efficaces soutiennent disponibilité et revenus agricoles.", "source": "strategy"});
QUESTIONS.push({"id": "afdb-113", "d": "afdb", "lv": 2, "fr": "Dans un prêt concessionnel, concessionnel signifie :", "o": ["Remboursement toujours inutile", "Conditions plus favorables que le marché", "Absence totale de contrat", "Aucune analyse des risques"], "a": 1, "x": "Une concession porte sur les conditions du financement ; elle ne transforme pas automatiquement un prêt en don.", "source": "adf"});
QUESTIONS.push({"id": "afdb-114", "d": "afdb", "lv": 2, "fr": "Quel est le statut d’une annonce de financement ?", "o": ["Preuve immédiate de l’impact", "Information à distinguer du décaissement et des résultats", "Garantie que tous les travaux sont terminés", "Montant nécessairement reçu par chaque ménage"], "a": 1, "x": "Il faut vérifier chaque étape et ne pas confondre annonce, approbation, décaissement et résultats.", "source": null});
QUESTIONS.push({"id": "afdb-115", "d": "afdb", "lv": 2, "fr": "Le sigle ADF correspond en français à :", "o": ["Fonds africain de développement", "Autorité des devises françaises", "Association des douanes fédérales", "Fonds monétaire international"], "a": 0, "x": "African Development Fund se traduit par Fonds africain de développement.", "source": "adf"});
QUESTIONS.push({"id": "africa-100", "d": "africa", "lv": 2, "fr": "Une croissance du PIB réel de 6 % et une croissance démographique de 4 % impliquent approximativement :", "o": ["10 % de croissance réelle par habitant", "2 % de croissance réelle par habitant", "6 % de baisse des prix", "Un recul automatique de la pauvreté"], "a": 1, "x": "(1,06 / 1,04 − 1) ≈ 1,92 %. La distribution des gains reste à examiner.", "source": null});
QUESTIONS.push({"id": "africa-101", "d": "africa", "lv": 2, "fr": "Quel exemple relève principalement de l’adaptation climatique ?", "o": ["Des variétés tolérantes à la sécheresse", "Une taxe supprimée sans analyse", "Un changement de devise", "Une campagne sans rapport au climat"], "a": 0, "x": "Ces variétés cherchent à réduire la vulnérabilité à la sécheresse.", "source": null});
QUESTIONS.push({"id": "africa-102", "d": "africa", "lv": 2, "fr": "Quel exemple relève principalement de l’atténuation climatique ?", "o": ["Réduire les émissions en remplaçant du diesel par du solaire", "Construire une digue uniquement contre les crues", "Déplacer des logements hors d’une zone inondable", "Renforcer une alerte inondation"], "a": 0, "x": "L’atténuation agit sur les émissions ; les autres exemples répondent surtout aux effets du climat.", "source": null});
QUESTIONS.push({"id": "africa-103", "d": "africa", "lv": 2, "fr": "Un projet forme 500 jeunes. Quelle information manque pour juger l’insertion ?", "o": ["Le nombre de chaises", "Le taux d’emploi durable après formation", "La couleur des attestations", "Le nombre de diapositives"], "a": 1, "x": "La formation est un produit. L’accès durable à un emploi est un résultat.", "source": null});
QUESTIONS.push({"id": "africa-104", "d": "africa", "lv": 2, "fr": "Pourquoi désagréger un indicateur par sexe et territoire ?", "o": ["Pour identifier des écarts masqués par la moyenne", "Pour augmenter artificiellement le total", "Pour éviter les enquêtes", "Pour garantir la causalité"], "a": 0, "x": "Une moyenne globale peut cacher des différences importantes d’accès ou d’effets.", "source": null});
QUESTIONS.push({"id": "africa-105", "d": "africa", "lv": 2, "fr": "Une route transfrontalière est construite mais le commerce stagne. Que vérifier ?", "o": ["Uniquement la peinture", "Procédures douanières et coûts logistiques", "Uniquement les inaugurations", "Le nombre de photos"], "a": 1, "x": "Les barrières administratives et les coûts de transport peuvent limiter les bénéfices de l’infrastructure.", "source": null});
QUESTIONS.push({"id": "africa-106", "d": "africa", "lv": 2, "fr": "Quel indicateur décrit le mieux la rentabilité d’une exploitation ?", "o": ["Chiffre d’affaires sans coûts", "Revenu net après coûts pertinents", "Surface seule", "Quantité de semences achetée"], "a": 1, "x": "Une hausse des ventes peut s’accompagner d’une hausse encore plus forte des coûts.", "source": null});
QUESTIONS.push({"id": "africa-107", "d": "africa", "lv": 2, "fr": "Le dividende démographique est-il automatique ?", "o": ["Oui dès que la population augmente", "Non, il nécessite notamment santé, compétences et emplois", "Oui sans investissement", "Il dépend uniquement de la superficie"], "a": 1, "x": "La structure démographique crée un potentiel qui nécessite des conditions économiques et sociales.", "source": null});
QUESTIONS.push({"id": "africa-108", "d": "africa", "lv": 2, "fr": "Quel risque accompagne une dette en devises pour un emprunteur payé en monnaie locale ?", "o": ["Le risque de change", "Aucun risque", "Une réduction certaine du remboursement", "Une disparition des intérêts"], "a": 0, "x": "La dépréciation de la monnaie locale peut augmenter le coût du service de la dette.", "source": null});
QUESTIONS.push({"id": "africa-109", "d": "africa", "lv": 2, "fr": "Une garantie publique sur un PPP est :", "o": ["Toujours sans coût possible", "Un engagement pouvant créer un risque budgétaire", "Un don déjà payé", "Une recette fiscale certaine"], "a": 1, "x": "Une garantie peut être appelée : il faut examiner les passifs éventuels.", "source": null});
QUESTIONS.push({"id": "africa-110", "d": "africa", "lv": 2, "fr": "Une hausse de rendement sans marché fiable peut entraîner :", "o": ["Un revenu forcément accru", "Des pertes ou une baisse des prix à la récolte", "Une hausse automatique des exportations", "La suppression des coûts"], "a": 1, "x": "Les débouchés, le stockage et les prix comptent autant que la production.", "source": null});
QUESTIONS.push({"id": "africa-111", "d": "africa", "lv": 2, "fr": "Quel dispositif soutient la redevabilité d’un projet ?", "o": ["Un mécanisme accessible de plaintes et de suivi", "Des résultats secrets pour tous", "La suppression des consultations", "Des chiffres sans source"], "a": 0, "x": "La redevabilité implique possibilité de retour, examen des plaintes et suivi des réponses.", "source": null});
QUESTIONS.push({"id": "africa-112", "d": "africa", "lv": 2, "fr": "Une hausse du revenu observée après un projet prouve-t-elle son effet causal ?", "o": ["Oui toujours", "Non, d’autres facteurs peuvent expliquer la hausse", "Oui si la hausse dépasse 10 %", "Oui si le rapport est long"], "a": 1, "x": "Une comparaison appropriée et une analyse des autres facteurs sont nécessaires.", "source": null});
QUESTIONS.push({"id": "africa-113", "d": "africa", "lv": 2, "fr": "L’inclusion financière consiste surtout à :", "o": ["Accéder à des services adaptés, utilisables et abordables", "Distribuer du crédit sans évaluation", "Imposer un compte inutilisable", "Remplacer tous les paiements en espèces immédiatement"], "a": 0, "x": "L’accès formel seul ne suffit pas : qualité, usage et protection des clients comptent.", "source": null});
QUESTIONS.push({"id": "africa-114", "d": "africa", "lv": 2, "fr": "Une irrigation solaire sans suivi des nappes présente quel risque ?", "o": ["Surexploitation de l’eau souterraine", "Disparition automatique des sécheresses", "Risque nul grâce au solaire", "Hausse garantie des nappes"], "a": 0, "x": "Une énergie moins coûteuse peut accroître le pompage ; la gestion de la ressource reste indispensable.", "source": null});
QUESTIONS.push({"id": "africa-115", "d": "africa", "lv": 2, "fr": "Quel arbitrage est pertinent pour une infrastructure ?", "o": ["Coût initial seulement", "Coût du cycle de vie, entretien, bénéfices et risques", "Nombre de discours seulement", "Vitesse d’inauguration seulement"], "a": 1, "x": "L’entretien et les risques conditionnent la pérennité des services.", "source": null});
QUESTIONS.push({"id": "sjt-100", "d": "sjt", "lv": 2, "fr": "Un partenaire offre un cadeau coûteux pendant une sélection. Que faire ?", "o": ["Accepter puis le partager", "Refuser et suivre la procédure de déclaration", "Accepter si personne ne voit", "Reporter la sélection sans explication"], "a": 1, "x": "Préserver l’indépendance et déclarer selon les règles évite un conflit réel ou apparent.", "source": null});
QUESTIONS.push({"id": "sjt-101", "d": "sjt", "lv": 2, "fr": "Un fichier confidentiel a été envoyé au mauvais destinataire. Première réponse ?", "o": ["Effacer son propre message et se taire", "Signaler rapidement par le canal prévu et limiter l’exposition", "Attendre le rapport annuel", "Publier une capture"], "a": 1, "x": "Il faut contenir et signaler l’incident, sans le dissimuler ni amplifier la fuite.", "source": null});
QUESTIONS.push({"id": "sjt-102", "d": "sjt", "lv": 2, "fr": "Une analyse présente une incertitude qui pourrait changer la décision. Que faire ?", "o": ["La cacher dans une annexe inaccessible", "Présenter les hypothèses et une analyse de sensibilité", "Remplacer les données", "Choisir le résultat préféré du client"], "a": 1, "x": "La décision doit connaître les limites matérielles et les scénarios pertinents.", "source": null});
QUESTIONS.push({"id": "sjt-103", "d": "sjt", "lv": 2, "fr": "Un collègue n’a pas livré sa partie. Avant d’escalader un retard ordinaire :", "o": ["Clarifier le blocage et convenir d’un rattrapage", "L’accuser dans un message collectif", "Réécrire son évaluation annuelle", "Cesser toute communication"], "a": 0, "x": "La coordination directe permet souvent de résoudre un problème courant ; escalader si le risque persiste.", "source": null});
QUESTIONS.push({"id": "sjt-104", "d": "sjt", "lv": 2, "fr": "Lors d’une visite, un danger immédiat menace des travailleurs. Priorité ?", "o": ["Finir les photos", "Alerter les responsables de sécurité et faire appliquer les mesures urgentes adaptées", "Attendre la prochaine réunion mensuelle", "Éviter de documenter"], "a": 1, "x": "La protection immédiate des personnes prime, en utilisant les responsabilités et canaux appropriés.", "source": null});
QUESTIONS.push({"id": "sjt-105", "d": "sjt", "lv": 2, "fr": "Une communauté exprime une opposition à un projet. Réponse adaptée ?", "o": ["La considérer comme mal informée", "Écouter, documenter les préoccupations et examiner les ajustements possibles", "Annuler sans analyse", "Ignorer les personnes non titulaires de contrat"], "a": 1, "x": "La consultation et le traitement des impacts renforcent la qualité et la légitimité du projet.", "source": null});
QUESTIONS.push({"id": "sjt-106", "d": "sjt", "lv": 2, "fr": "Votre supérieur conteste un résultat technique fondé. Que faire ?", "o": ["Changer le résultat pour plaire", "Présenter les données et discuter les hypothèses avec respect", "Le ridiculiser publiquement", "Refuser toute discussion"], "a": 1, "x": "L’intégrité technique et le respect professionnel se renforcent mutuellement.", "source": null});
QUESTIONS.push({"id": "sjt-107", "d": "sjt", "lv": 2, "fr": "Une demande dépasse votre expertise. Quelle réponse est la plus utile ?", "o": ["Inventer une réponse plausible", "Clarifier le besoin et mobiliser un expert avec un délai convenu", "Ignorer la demande", "Promettre une validation immédiate"], "a": 1, "x": "Reconnaître une limite et chercher l’expertise protège la qualité sans abandonner le besoin.", "source": null});
QUESTIONS.push({"id": "sjt-108", "d": "sjt", "lv": 2, "fr": "Vous constatez une erreur dans un rapport déjà envoyé. Que faire ?", "o": ["Corriger la copie locale seulement", "Informer les destinataires concernés avec une correction traçable", "Attendre qu’on la découvre", "Accuser un collègue sans vérifier"], "a": 1, "x": "La correction doit atteindre ceux qui pourraient utiliser l’information erronée.", "source": null});
QUESTIONS.push({"id": "sjt-109", "d": "sjt", "lv": 2, "fr": "Deux demandes importantes ont la même échéance et dépassent votre capacité. Que faire ?", "o": ["Promettre les deux sans réserve", "Clarifier les priorités, négocier le périmètre et rechercher un appui", "Choisir au hasard", "Travailler en silence sans alerter"], "a": 1, "x": "Rendre le conflit de capacité visible permet un arbitrage explicite.", "source": null});
QUESTIONS.push({"id": "sjt-110", "d": "sjt", "lv": 2, "fr": "Un collègue junior propose une idée contraire à la vôtre. Réponse adaptée ?", "o": ["L’écarter selon son ancienneté", "Tester les arguments selon les mêmes critères", "Accepter automatiquement", "Lui retirer la parole"], "a": 1, "x": "L’évaluation des idées doit reposer sur les faits et non sur le statut.", "source": null});
QUESTIONS.push({"id": "sjt-111", "d": "sjt", "lv": 2, "fr": "Un indicateur est impossible à vérifier avant une échéance. Que faire ?", "o": ["L’inventer à partir de la cible", "Signaler la limite et proposer une validation datée", "Le déclarer atteint", "Copier celui d’un autre pays"], "a": 1, "x": "La transparence sur une donnée manquante est préférable à une précision fictive.", "source": null});
QUESTIONS.push({"id": "sjt-112", "d": "sjt", "lv": 2, "fr": "Un partenaire veut vos identifiants pour accélérer un travail. Réponse adaptée ?", "o": ["Les envoyer par messagerie privée", "Proposer un accès autorisé à son nom", "Partager seulement le mot de passe", "Les écrire dans le rapport"], "a": 1, "x": "Un accès nominatif adapté préserve traçabilité et sécurité.", "source": null});
QUESTIONS.push({"id": "sjt-113", "d": "sjt", "lv": 2, "fr": "Une plainte sensible implique votre responsable direct. Que faire ?", "o": ["Lui transmettre automatiquement tous les détails", "Utiliser le canal indépendant prévu en préservant la confidentialité", "Publier sur les réseaux sociaux", "Écarter la plainte"], "a": 1, "x": "Un canal adapté évite de compromettre l’examen de la plainte et protège les personnes.", "source": null});
QUESTIONS.push({"id": "sjt-114", "d": "sjt", "lv": 2, "fr": "Un fournisseur demande les prix confidentiels des concurrents. Réponse ?", "o": ["Les donner pour obtenir une remise", "Refuser et maintenir l’égalité de traitement", "Les donner oralement", "Indiquer seulement le prix le plus bas"], "a": 1, "x": "La confidentialité et l’équité s’appliquent quel que soit le mode de transmission.", "source": null});
QUESTIONS.push({"id": "sjt-115", "d": "sjt", "lv": 2, "fr": "Vous devez agir vite mais une procédure comporte une dérogation encadrée. Que faire ?", "o": ["Utiliser la dérogation avec les autorisations requises", "Contourner sans trace", "Refuser toute accélération possible", "Obtenir seulement l’accord du fournisseur"], "a": 0, "x": "L’efficacité peut passer par des mécanismes autorisés et documentés.", "source": null});
QUESTIONS.push({"id": "reason-100", "d": "reason", "lv": 2, "fr": "Un taux passe de 40 % à 50 %. La hausse est de :", "o": ["10 points et 25 % en relatif", "10 % en relatif seulement", "25 points", "50 points"], "a": 0, "x": "50−40 = 10 points ; 10/40 = 25 %. Attention aux unités.", "source": null});
QUESTIONS.push({"id": "reason-101", "d": "reason", "lv": 2, "fr": "Un coût augmente de 10 %, puis de 10 %. Hausse totale ?", "o": ["20 %", "21 %", "10 %", "19 %"], "a": 1, "x": "1,10 × 1,10 = 1,21.", "source": null});
QUESTIONS.push({"id": "reason-102", "d": "reason", "lv": 2, "fr": "Après une réduction de 20 %, un équipement coûte 80 000 FCFA. Prix initial ?", "o": ["96 000", "100 000", "64 000", "120 000"], "a": 1, "x": "80 000 / 0,8 = 100 000.", "source": null});
QUESTIONS.push({"id": "reason-103", "d": "reason", "lv": 2, "fr": "Un budget de 50 M est partagé dans le ratio 2:3. La plus petite part vaut :", "o": ["20 M", "25 M", "30 M", "10 M"], "a": 0, "x": "5 parts au total ; 50 × 2/5 = 20.", "source": null});
QUESTIONS.push({"id": "reason-104", "d": "reason", "lv": 2, "fr": "Suite : 3, 7, 15, 31, …", "o": ["47", "62", "63", "64"], "a": 2, "x": "Chaque terme vaut le précédent × 2 + 1.", "source": null});
QUESTIONS.push({"id": "reason-105", "d": "reason", "lv": 2, "fr": "Tous les projets A sont audités. Certains projets audités sont retardés. Peut-on conclure que certains A sont retardés ?", "o": ["Oui", "Non, pas nécessairement", "Tous les A sont retardés", "Aucun projet A ne peut être retardé"], "a": 1, "x": "Le sous-ensemble des projets retardés peut ne contenir aucun A.", "source": null});
QUESTIONS.push({"id": "reason-106", "d": "reason", "lv": 2, "fr": "A précède B et B précède C. Que sait-on ?", "o": ["C précède A", "A précède C", "B précède A", "A et C sont simultanés"], "a": 1, "x": "La relation de précédence est transitive.", "source": null});
QUESTIONS.push({"id": "reason-107", "d": "reason", "lv": 2, "fr": "Un tableau fictif donne : A budget 12, décaissé 9 ; B budget 20, décaissé 10. Quel taux de décaissement global ?", "o": ["62,5 %", "59,375 %", "75 %", "50 %"], "a": 1, "x": "Total décaissé 19 / budget 32 = 59,375 %. Ne pas faire la moyenne simple des deux taux.", "source": null});
QUESTIONS.push({"id": "reason-108", "d": "reason", "lv": 2, "fr": "80 % de 250 dossiers sont complets ; 15 % des dossiers complets sont rejetés. Combien restent complets et non rejetés ?", "o": ["170", "200", "212,5", "35"], "a": 0, "x": "250 × 0,8 = 200 ; 200 × 0,85 = 170.", "source": null});
QUESTIONS.push({"id": "reason-109", "d": "reason", "lv": 2, "fr": "Un programme dépense 18 M sur 24 M. Quelle part reste ?", "o": ["75 %", "25 %", "6 %", "18 %"], "a": 1, "x": "6 M restent sur 24 M, soit 25 %.", "source": null});
QUESTIONS.push({"id": "reason-110", "d": "reason", "lv": 2, "fr": "Le texte dit : « Les coûts ont augmenté ; la fréquentation est stable. » Les recettes ont-elles augmenté ?", "o": ["Oui", "Non", "Impossible à déterminer", "Elles ont doublé"], "a": 2, "x": "Sans information sur les tarifs et autres revenus, on ne peut pas conclure.", "source": null});
QUESTIONS.push({"id": "reason-111", "d": "reason", "lv": 2, "fr": "Une moyenne de 60 porte sur 10 observations ; une moyenne de 80 sur 30 observations. Moyenne totale ?", "o": ["70", "75", "80", "65"], "a": 1, "x": "(60 × 10 + 80 × 30) / 40 = 75.", "source": null});
QUESTIONS.push({"id": "reason-112", "d": "reason", "lv": 2, "fr": "Deux événements indépendants ont probabilités 0,5 et 0,4. Probabilité que les deux se produisent ?", "o": ["0,9", "0,1", "0,2", "0,45"], "a": 2, "x": "Pour des événements indépendants : 0,5 × 0,4 = 0,2.", "source": null});
QUESTIONS.push({"id": "reason-113", "d": "reason", "lv": 2, "fr": "Un projet de 120 jours a consommé 30 jours. Part du temps écoulée ?", "o": ["20 %", "25 %", "30 %", "40 %"], "a": 1, "x": "30/120 = 1/4 = 25 %.", "source": null});
QUESTIONS.push({"id": "reason-114", "d": "reason", "lv": 2, "fr": "Un rendement passe de 2 à 2,6 t/ha. Hausse relative ?", "o": ["0,6 %", "23,1 %", "30 %", "60 %"], "a": 2, "x": "(2,6−2)/2 = 0,3.", "source": null});
QUESTIONS.push({"id": "reason-115", "d": "reason", "lv": 2, "fr": "Un projet coûte 9 M pour 3 000 bénéficiaires. Coût moyen par bénéficiaire ?", "o": ["300", "3 000", "30 000", "27 000"], "a": 1, "x": "9 000 000 / 3 000 = 3 000, dans la même devise.", "source": null});
QUESTIONS.push({"id": "reason-116", "d": "reason", "lv": 2, "fr": "Le ratio femmes/hommes est de 3:2 parmi 150 participants. Nombre de femmes ?", "o": ["60", "75", "90", "100"], "a": 2, "x": "150 × 3/5 = 90.", "source": null});
QUESTIONS.push({"id": "reason-117", "d": "reason", "lv": 2, "fr": "Un budget baisse de 20 %, puis augmente de 25 %. Par rapport au budget initial :", "o": ["Il est identique", "Il augmente de 5 %", "Il diminue de 5 %", "Il double"], "a": 0, "x": "0,8 × 1,25 = 1.", "source": null});
QUESTIONS.push({"id": "reason-118", "d": "reason", "lv": 2, "fr": "Quel est le nombre médian de 4, 7, 8, 11, 25 ?", "o": ["7", "8", "11", "10"], "a": 1, "x": "La médiane est la valeur centrale de la série ordonnée : 8.", "source": null});
QUESTIONS.push({"id": "reason-119", "d": "reason", "lv": 2, "fr": "Une unité produit 12 dossiers en 3 heures. Au même rythme, durée pour 30 dossiers ?", "o": ["6 h", "7,5 h", "8 h", "9 h"], "a": 1, "x": "4 dossiers par heure ; 30/4 = 7,5 heures.", "source": null});
QUESTIONS.forEach(q=>{if(!q.source && q.d==="afdb")q.source=({1:"adf",2:"strategy",3:"strategy",4:"strategy",5:"annual",21:"adf"})[q.id]||null;});
QUESTIONS.push(
{id:'advanced-1',d:'sjt',lv:3,fr:'Une note doit partir dans une heure. Une donnée secondaire reste incertaine, mais la recommandation ne change pas dans les scénarios testés. Quelle réponse est la plus proportionnée ?',o:['Reporter toute la note jusqu’à une vérification exhaustive','Soumettre en explicitant la limite, sa faible sensibilité et la vérification prévue','Retirer toute mention de l’incertitude pour ne pas distraire','Transmettre uniquement les annexes sans recommandation'],a:1,x:'Une limite documentée dont la sensibilité a été évaluée peut être communiquée avec la note. Le report systématique n’est pas nécessaire ; la dissimulation reste inadaptée.'},
{id:'advanced-2',d:'sjt',lv:3,fr:'Votre collègue juge un modèle trop optimiste ; vous jugez ses hypothèses excessivement prudentes. Avant de demander un arbitrage, quelle action privilégier ?',o:['Présenter au responsable les deux conclusions sans comparer les hypothèses','Retenir la moyenne des deux résultats pour gagner du temps','Comparer les hypothèses déterminantes et tester les scénarios sur des critères partagés','Choisir le modèle de la personne la plus expérimentée'],a:2,x:'La comparaison des hypothèses et la sensibilité permettent de comprendre le désaccord. Une moyenne mécanique ne résout pas les différences de méthode.'},
{id:'advanced-3',d:'sjt',lv:3,fr:'Un partenaire réclame un changement de périmètre utile mais coûteux, juste avant validation. Quelle réponse est la plus appropriée ?',o:['Accepter le besoin puis ajuster les coûts après signature','Chiffrer effets, délais et risques puis soumettre le changement à la validation compétente','Refuser tout changement à ce stade sans examen','Demander au fournisseur d’absorber le surcoût sans modifier le contrat'],a:1,x:'Le besoin mérite examen, mais les engagements doivent intégrer explicitement les conséquences et les validations requises.'},
{id:'advanced-4',d:'africa',lv:3,fr:'Deux projets d’eau ont le même coût : A touche davantage de personnes, B dessert une zone isolée très défavorisée. Quelle analyse est la plus pertinente ?',o:['Choisir A uniquement selon le nombre total','Comparer coût-efficacité, équité, faisabilité et durabilité','Choisir B sans autre information','Faire une loterie puisque les coûts sont égaux'],a:1,x:'Le nombre de bénéficiaires est important, mais l’équité d’accès, les besoins et la durabilité peuvent modifier l’arbitrage.'},
{id:'advanced-5',d:'reason',lv:3,fr:'Dans ce portefeuille fictif, quel projet a le coût engagé par bénéficiaire le plus faible ?',table:'<table><caption>Projets fictifs · montants en millions de FCFA</caption><thead><tr><th>Projet</th><th>Coût</th><th>Bénéficiaires</th></tr></thead><tbody><tr><td>A</td><td>60</td><td>1 500</td></tr><tr><td>B</td><td>90</td><td>3 000</td></tr><tr><td>C</td><td>40</td><td>800</td></tr></tbody></table>',o:['A','B','C','Ils sont égaux'],a:1,x:'A : 40 000 FCFA/personne ; B : 30 000 ; C : 50 000. B a le coût moyen le plus faible, sans que cela prouve à lui seul le meilleur impact.'},
{id:'advanced-6',d:'reason',lv:3,fr:'Les exportations fictives valent 100 M, dont 60 M de cacao. Le cacao augmente de 20 %, les autres exportations baissent de 10 %. Nouveau total ?',o:['110 M','108 M','112 M','104 M'],a:1,x:'60 × 1,20 + 40 × 0,90 = 72 + 36 = 108 M.'},
{id:'advanced-7',d:'reason',lv:3,fr:'Un audit a lieu seulement si le seuil est dépassé. L’audit a eu lieu. Quelle conclusion est nécessaire selon cette règle ?',o:['Le seuil a été dépassé','Tout dépassement déclenche forcément un audit','Le seuil n’a pas été dépassé','Impossible de savoir si le seuil a été dépassé'],a:0,x:'« Audit seulement si dépassement » signifie audit ⇒ dépassement. La réciproque n’est pas affirmée.'},
{id:'advanced-8',d:'reason',lv:3,fr:'Une dépense prévue de 10 M USD valait 6 milliards FCFA au taux fictif de 600 FCFA/USD. Au taux de 660, son coût local augmente de :',o:['60 millions FCFA','600 millions FCFA','6 millions FCFA','660 millions FCFA'],a:1,x:'10 000 000 × (660−600) = 600 000 000 FCFA. Taux fictifs, sans valeur de cotation.'},
{id:'advanced-9',d:'africa',lv:3,fr:'Un financement mixte attire des investisseurs qui auraient financé le projet sans aide. Quel point doit être particulièrement examiné ?',o:['L’additionnalité et le risque de subvention inutile','Uniquement la taille du logo du bailleur','La suppression des contrôles','La croissance de la population mondiale'],a:0,x:'L’additionnalité examine ce que l’intervention apporte réellement. Subventionner un financement qui aurait eu lieu peut être inefficace.'}
);
QUESTIONS.push(
{id:'news-1',d:'afdb',lv:2,fr:'Selon le communiqué du 8 septembre 2026, le GEFCRF répond principalement à :',o:['La crise énergétique et des engrais','La création d’une monnaie continentale','La construction de sièges administratifs','La réforme du calendrier YPP'],a:0,x:'Le cadre vise les chocs sur l’énergie et les engrais ainsi que la résilience des pays africains.',source:'crisis'},
{id:'news-2',d:'afdb',lv:2,fr:'Quel est le rôle du FAD dans le financement annoncé du GEFCRF ?',o:['Jusqu’à 960 millions USD','La totalité des 5,1 milliards USD','Aucune contribution','960 milliards USD'],a:0,x:'L’annonce prévoit jusqu’à 960 millions USD du FAD, en complément de 4,1 milliards USD de prêts BAD supplémentaires.',source:'crisis'},
{id:'news-3',d:'reason',lv:2,fr:'Un communiqué annonce 4,1 milliards USD plus 960 millions USD. Somme en milliards, avant arrondi ?',o:['5,06','5,6','964,1','4,196'],a:0,x:'960 millions = 0,96 milliard ; 4,1 + 0,96 = 5,06 milliards, soit environ 5,1 à une décimale.',source:'crisis'},
{id:'news-4',d:'afdb',lv:2,fr:'Dans le communiqué BAD–AXIAN du 2 septembre 2026, le Togo est explicitement inclus dans :',o:['Le volet formation dans cinq pays','Le volet financier limité à trois pays','Une union monétaire nouvelle','Aucun volet cité'],a:0,x:'Le volet formation couvre Madagascar, Tanzanie, Sénégal, Togo et Comores ; le volet financier de 34 000 entreprises concerne les trois premiers pays.',source:'axian'},
{id:'news-5',d:'reason',lv:3,fr:'Le prêt BAD Clean Air est de 200 M EUR, pour un coût estimé de 833 M EUR. Part approximative du prêt ?',o:['24 %','42 %','60 %','76 %'],a:0,x:'200 / 833 × 100 ≈ 24 %. Le prêt de la BAD ne correspond pas au coût total.',source:'sir'},
{id:'news-6',d:'afdb',lv:2,fr:'Quel thème structure l’annonce KOAFEC de septembre 2026 ?',o:['IA et infrastructures numériques au service de la transformation africaine','Monnaie unique mondiale','Tourisme uniquement','Abandon des compétences numériques'],a:0,x:'La conférence annoncée porte sur l’IA et les infrastructures numériques. L’annonce n’établit pas à elle seule les décisions finales.',source:'koafec'},
{id:'news-7',d:'afdb',lv:2,fr:'Dans le communiqué KOAFEC, NAFAD renvoie à :',o:['New African Financial Architecture for Development','National Agricultural Food and Dairy','Network for Asian Fiscal Debt','New African Fixed Annual Deposit'],a:0,x:'Il s’agit de la nouvelle architecture financière africaine pour le développement, rattachée aux quatre points cardinaux.',source:'koafec'},
{id:'news-8',d:'africa',lv:3,fr:'Un programme vise 34 000 entreprises pour des services et 25 000 femmes pour des formations. Peut-on annoncer 59 000 bénéficiaires uniques ?',o:['Non, unités et recoupements doivent être vérifiés','Oui par simple addition','Oui si les pays sont africains','Non car on doit multiplier les chiffres'],a:0,x:'Entreprises et personnes sont des unités différentes, avec des recoupements possibles ; leur somme ne mesure pas un nombre de personnes uniques.',source:'axian'}
);
