
/* TOGO LIFE 3D — self-contained procedural WebGL simulation, MIT licensed. No remote dependencies. */
(()=>{'use strict';
const $=id=>document.getElementById(id), on=(id,ev,fn)=>$(id).addEventListener(ev,fn), money=n=>Math.round(n).toLocaleString('fr-FR')+' F';
const PREF=[['Agoè-Nyivé','M',6.285,1.205],['Agou','P',6.755,.767],['Akébou','P',7.828,.753],['Amou','P',7.54,1.066],['Anié','P',7.696,1.403],['Assoli','K',9.337,1.185],['Avé','M',6.439,.914],['Bas-Mono','M',6.471,1.661],['Bassar','K',9.252,.769],['Binah','K',9.754,1.281],['Blitta','C',8.152,.933],['Cinkassé','S',11.05,.102],['Dankpen','K',9.726,.593],['Danyi','P',7.231,.693],['Doufelgou','K',9.838,1.033],['Est-Mono','P',8.139,1.448],['Golfe','M',6.19,1.134],['Haho','P',7.025,1.224],['Kéran','K',10.069,.975],['Kloto','P',6.92,.63],['Kozah','K',9.558,1.143],['Kpélé','P',7.116,.806],['Kpendjal','S',10.801,.701],['Lacs','M',6.299,1.697],['Lomé','M',6.157,1.246],['Moyen-Mono','P',7.196,1.558],['Naki-Ouest','S',10.831,.45],['Ogou','P',7.463,1.276],['Oti','S',10.406,.411],['Oti-Sud','S',10.288,.719],['Plaine du Mô','C',8.765,.549],['Sotouboua','C',8.705,.961],['Tandjouaré','S',10.606,.16],['Tchamba','C',8.819,1.477],['Tchaoudjo','C',8.992,1.13],['Tône','S',10.868,.169],['Vo','M',6.393,1.5],['Wawa','P',7.543,.76],['Yoto','M',6.67,1.452],['Zio','M',6.533,1.156]];
const REG={M:{name:'Maritime',factor:1.16,tint:'#619a82',ground:[.41,.59,.46],feature:'🌊 Brise du littoral, ports et échanges'},P:{name:'Plateaux',factor:1.03,tint:'#70bd8c',ground:[.32,.57,.39],feature:'🌿 Collines, cacao, café et marchés'},C:{name:'Centrale',factor:.97,tint:'#c2a56e',ground:[.52,.58,.37],feature:'🚚 Marchés et corridors commerciaux'},K:{name:'Kara',factor:1.01,tint:'#b7896c',ground:[.55,.55,.35],feature:'⛰️ Artisanat, élevage et universités'},S:{name:'Savanes',factor:.88,tint:'#ceb16d',ground:[.67,.58,.35],feature:'🌾 Marchés céréaliers et savane'}};
const $canvas=$('world');let gl=$canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'high-performance'});
const canvasFallback=!gl;let ctx2d=null;
if(canvasFallback){ctx2d=$canvas.getContext('2d');const noop=()=>{};gl=new Proxy({createShader:()=>({}),createProgram:()=>({}),createBuffer:()=>({}),getShaderParameter:()=>true,getProgramParameter:()=>true,getAttribLocation:()=>0,getUniformLocation:()=>null}, {get:(t,p)=>p in t?t[p]:noop});}

const vs=`attribute vec3 aPos;attribute vec3 aCol;uniform mat4 uVP;uniform vec3 uEye;varying vec3 vColor;varying float vDistance;void main(){gl_Position=uVP*vec4(aPos,1.);vColor=aCol;vDistance=distance(aPos,uEye);}`;
const fs=`precision mediump float;varying vec3 vColor;varying float vDistance;uniform vec3 uFog;uniform float uLight;void main(){float f=smoothstep(42.,105.,vDistance);vec3 c=mix(vColor*uLight,uFog,f*.78);gl_FragColor=vec4(c,1.);}`;
function shader(type,src){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
const loc={position:gl.getAttribLocation(program,'aPos'),color:gl.getAttribLocation(program,'aCol'),vp:gl.getUniformLocation(program,'uVP'),eye:gl.getUniformLocation(program,'uEye'),fog:gl.getUniformLocation(program,'uFog'),light:gl.getUniformLocation(program,'uLight')};
gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.clearColor(.46,.69,.71,1);
const staticBuffer=gl.createBuffer(),dynamicBuffer=gl.createBuffer();let staticCount=0, staticData=null;
let world=[], places=[], cars=[], pedestrians=[], pops=[], camYaw=-.17,player={x:1.5,z:11,yaw:Math.PI},selectedCity=24,selectedAvatar=0,activeNear=null,sound=false,audio=null;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),rad=Math.PI/180;
const mkState=()=>({name:'Kossi',avatar:0,city:24,day:1,time:8,money:25000,energy:83,food:75,mood:82,rep:8,experience:0,biz:false,stock:0,debt:0,loans:0,rentPaid:0,done:false,actions:0});let state=mkState(),started=false,modalOpen=true,lastToast=0;
let staticGeom=[],dynamicGeom=[],g=staticGeom;let seed=1;
function random(){seed=(Math.imul(seed,1664525)+1013904223)|0;return (seed>>>0)/4294967296}
const color=(hex)=>{if(Array.isArray(hex))return hex;let x=parseInt(hex.replace('#',''),16);return [(x>>16&255)/255,(x>>8&255)/255,(x&255)/255]};
function lighten(c,f){let a=color(c);return a.map(v=>Math.min(1,v*f))}
function vert(p,c){g.push(p[0],p[1],p[2],c[0],c[1],c[2])}
function tri(p1,p2,p3,c){let cl=color(c);vert(p1,cl);vert(p2,cl);vert(p3,cl)}
function quad(a,b,c,d,col){tri(a,b,c,col);tri(a,c,d,col)}
function box(x,y,z,w,h,d,col,yaw=0){let co=color(col),u=w/2,v=d/2,cy=Math.cos(yaw),sy=Math.sin(yaw),p=[];for(let Y of [-h/2,h/2])for(let Z of [-v,v])for(let X of [-u,u]){p.push([x+X*cy+Z*sy,y+Y,z-X*sy+Z*cy])}let sides=[[0,1,3,2,.7],[4,6,7,5,1.11],[0,4,5,1,.87],[2,3,7,6,.91],[0,2,6,4,.8],[1,5,7,3,.95]];for(let t of sides)quad(p[t[0]],p[t[1]],p[t[2]],p[t[3]],lighten(co,t[4]));}
function pyramid(x,y,z,w,h,d,col){let u=w/2,v=d/2,p=[[x-u,y,z-v],[x+u,y,z-v],[x+u,y,z+v],[x-u,y,z+v]],top=[x,y+h,z];for(let i=0;i<4;i++)tri(p[i],p[(i+1)%4],top,lighten(col,[.92,1.11,.79,1][i]));}
function cone(x,y,z,r,h,col,n=7){let p=[x,y+h,z];for(let i=0;i<n;i++){let a=i*2*Math.PI/n,b=(i+1)*2*Math.PI/n;tri([x+r*Math.cos(a),y,z+r*Math.sin(a)],[x+r*Math.cos(b),y,z+r*Math.sin(b)],p,lighten(col,.8+((i%3)*.11)));}}
function cylinder(x,y,z,r,h,col,n=8){let c=color(col);for(let i=0;i<n;i++){let a=i*2*Math.PI/n,b=(i+1)*2*Math.PI/n;quad([x+r*Math.cos(a),y,z+r*Math.sin(a)],[x+r*Math.cos(b),y,z+r*Math.sin(b)],[x+r*Math.cos(b),y+h,z+r*Math.sin(b)],[x+r*Math.cos(a),y+h,z+r*Math.sin(a)],lighten(c,1-.22*(i%3)));}}
function roofHouse(x,z,w,d,c,roof){box(x,1.75,z,w,3.5,d,c);pyramid(x,3.5,z,w+1,1.8,d+1,roof);for(let sz of [-1,1]){box(x+sz*w*.25,2.15,z+d/2+.04,1,.93,.09,'#274353');box(x+sz*w*.25,2.15,z-d/2-.04,1,.93,.09,'#274353')}box(x,1,z+d/2+.12,1.15,2,.1,'#94694a');}
function blockRoads(){const grass=REG[PREF[state.city][1]].ground;box(0,-.31,0,155,.55,155,grass);box(0,-.08,0,12,.17,154,'#485b61');box(0,-.08,0,154,.17,11,'#485b61');for(let i=-72;i<73;i+=7){box(0,.017,i,.22,.008,3,'#f9e6aa');box(i,.017,0,3,.008,.22,'#f9e6aa')}for(let x of [-7.2,7.2])box(x,.035,0,2.4,.12,154,'#bbad92');for(let z of [-6.8,6.8])box(0,.035,z,154,.12,2.4,'#bbad92');for(let sign of [-1,1]){for(let k=-4;k<=4;k++){box(sign*8,.06,k*.68,.36,.016,.3,'#f8f4e2');box(k*.68,.06,sign*7.5,.3,.016,.36,'#f8f4e2')}}}
function palm(x,z,size=1){cylinder(x,0,z,.19*size,4.6*size,'#876443',6);for(let i=0;i<6;i++){let a=i*Math.PI/3;cone(x+Math.cos(a)*1.15*size,4.15*size,z+Math.sin(a)*1.15*size,1.18*size,1.27*size,i%2?'#245f46':'#2d7853',5);}cone(x,4.6*size,z,.62*size,.95*size,'#368858');}
function tree(x,z,size=1){cylinder(x,0,z,.18*size,2*size,'#866f50',6);cone(x,1.55*size,z,2.15*size,3.4*size,'#3e7750',8);cone(x,3*size,z,1.65*size,2.2*size,'#4b9962',7)}
function lamp(x,z){cylinder(x,0,z,.07,5,'#394752',6);box(x+.5,5,z,1.08,.13,.38,'#eecb87');box(x+.5,4.94,z,.8,.03,.23,'#f6ebaf')}
function stall(x,z,colors){box(x,.57,z,4.6,1.12,3.3,'#9b7255');box(x,1.4,z,4.1,.2,2.8,colors[0]);for(let i=-1;i<2;i++)box(x+i*1.3,2.77,z,1.27,.18,3.2,colors[(i+3)%colors.length]);for(let X of [-1.92,1.92])for(let Z of [-1.3,1.3])cylinder(x+X,.5,z+Z,.05,2.4,'#4b4d48');for(let i=0;i<9;i++)box(x-1.4+(i%3)*1.4,1.26,z-.92+Math.floor(i/3)*.95,.62,.29,.48,i%2?'#e79a4d':'#64a46f')}
function decorations(){let key=PREF[state.city][1];seed=111+state.city*139;let vacant=[[-45,-42],[-34,-46],[39,-40],[-43,37],[41,35],[36,45],[-48,15],[47,17],[-45,-18],[45,-17]];for(let v of vacant){let x=v[0]+random()*8-4,z=v[1]+random()*7-3; if(key==='S')tree(x,z,.6+random()*.25);else if(key==='P'||key==='K')tree(x,z,.75+random()*.5);else palm(x,z,.7+random()*.35)}for(let n=-45;n<=45;n+=17){lamp(-8.8,n);lamp(8.8,n)}for(let n=-35;n<=35;n+=18){lamp(n,-8.3);lamp(n,8.3)}}
function cityLandmarks(){places=[];let definitions=[
{name:'Chez toi',kind:'home',x:-23,z:21,w:15,d:13,c:'#e3b58b',r:'#a55e55',ico:'🏠'},
{name:'Grand marché',kind:'market',x:24,z:22,w:19,d:15,c:'#e6a979',r:'#e9bd79',ico:'🥭'},
{name:'Cyber & Studio IA',kind:'tech',x:24,z:-23,w:15,d:14,c:'#85b3be',r:'#e6dac1',ico:'💻'},
{name:'Centre de formation',kind:'school',x:-24,z:-23,w:17,d:14,c:'#e0c899',r:'#a47b5c',ico:'🎓'},
{name:'Banque / Mobile Money',kind:'bank',x:43,z:-19,w:14,d:14,c:'#9bbdb2',r:'#555e79',ico:'🏦'},
{name:'Gare routière',kind:'bus',x:-43,z:-17,w:14,d:14,c:'#e5aa82',r:'#ba775d',ico:'🚌'},
{name:'Terrain à kiosque',kind:'kiosk',x:39,z:21,w:11,d:10,c:'#c6ae8a',r:'#d6a05e',ico:'🏪'}];
for(let t of definitions){places.push({...t}); if(t.kind==='market'){stall(t.x-4,t.z-2,['#d18561','#f3d09a','#5d9782']);stall(t.x+3.8,t.z+2,['#f4cf77','#b2ddc0','#de9a6a']);box(t.x,.1,t.z+7.5,t.w,.2,1.2,'#e5d0aa')}
else if(t.kind==='bus'){box(t.x,.21,t.z,t.w,.35,t.d,'#b9b1a2');box(t.x,2.7,t.z+2,10,.34,5.8,'#eec47b');for(let xi of [-4.4,4.4])for(let zi of [-.5,4.4])cylinder(t.x+xi,.1,t.z+zi,.12,2.7,'#74756c')}
else if(t.kind==='kiosk'){box(t.x,.16,t.z,11,.3,10,'#c7ad8a');if(state.biz){stall(t.x,t.z,['#65b4a2','#ffe4b1','#b47d62']);box(t.x,3.34,t.z,5,.35,4,'#317563')}}
else{roofHouse(t.x,t.z,t.w,t.d,t.c,t.r);box(t.x,4.35,t.z+t.d/2+1.25,Math.min(6,t.w*.5),.73,.19,t.kind==='tech'?'#225b67':t.kind==='bank'?'#39765d':'#674f46');}}
let little=[[-48,30],[-47,-39],[-25,-46],[-6,-40],[20,-46],[41,43],[1,29],[-43,50],[18,43],[-19,48]];const walls=['#d99e7e','#c2c8a3','#aabbb7','#dfad8d','#cfba94'];for(let i=0;i<little.length;i++){let [x,z]=little[i],w=9+random()*5,d=9+random()*5;roofHouse(x,z,w,d,walls[i%5],i%2?'#b4725b':'#937e72')}
for(let i=0;i<13;i++){let x=-51+random()*110,z=-52+random()*112;if(Math.abs(x)>14&&Math.abs(z)>11 && !places.some(p=>Math.hypot(x-p.x,z-p.z)<13)) (PREF[state.city][1]==='S'?tree:palm)(x,z,.52+random()*.5)}
decorations();let region=PREF[state.city][1];if(region==='P'||region==='K'||region==='C')for(let i=0;i<10;i++){let x=-74+i*15,z=-71+(i%3)*3;let height=(region==='P'?16:region==='K'?12:7)+random()*12;pyramid(x,0,z,23,height,17,region==='P'?'#789780':region==='K'?'#9c9075':'#aeab84')};if(region==='M'){box(0,-.14,-70,140,.12,11,'#65a7b4');for(let i=-6;i<=6;i++)box(i*9,-.05,-64,2,.06,9,'#e5cda0')}if(region==='S')for(let i=0;i<14;i++){let x=-64+random()*128,z=-63+random()*124;if(Math.abs(x)>15&&Math.abs(z)>15)cone(x,0,z,1.2+random()*1.5,.5+random(),'#957f4e',5)}}
function createTown(){g=staticGeom=[];seed=2026+state.city*197;blockRoads();cityLandmarks();staticData=new Float32Array(staticGeom);gl.bindBuffer(gl.ARRAY_BUFFER,staticBuffer);gl.bufferData(gl.ARRAY_BUFFER,staticData,gl.STATIC_DRAW);staticCount=staticData.length/6;pedestrians=[{x:15,z:17,heading:0,walk:0,role:'vendeur',type:'person',name:'Ama'},{x:-15,z:-15,heading:1.5,walk:1,role:'étudiant',type:'person',name:'Yao'},{x:38,z:-9,heading:2.7,walk:2,role:'agent',type:'person',name:'Akou'},{x:-11,z:25,heading:1.5,walk:3,role:'voisin',type:'person',name:'Afi'},{x:15,z:-16,heading:3.3,walk:4,role:'développeur',type:'person',name:'Kodjo'},{x:-35,z:-9,heading:1,walk:5,role:'chauffeur',type:'person',name:'Komi'}];cars=[{x:2,z:-54,axis:'z',speed:8,dir:1,color:'#f0c465'},{x:-2,z:48,axis:'z',speed:7,dir:-1,color:'#97ccbb'},{x:-48,z:2,axis:'x',speed:8,dir:1,color:'#efae7b'},{x:49,z:-2,axis:'x',speed:9,dir:-1,color:'#e0c17c'}];updateCityUI();}
function face(x,y,z,skin='#754a35',shirt='#9fba9f',pants='#263f52',facing=0,anim=0,scale=1){let co=Math.cos(facing),si=Math.sin(facing);function part(dx,dy,dz,w,h,d,c,rot=0){let xx=x+(dx*co+dz*si)*scale,zz=z+(-dx*si+dz*co)*scale;box(xx,y+dy*scale,zz,w*scale,h*scale,d*scale,c,facing+rot)}let step=Math.sin(anim)*.4;part(0,1.46,0,.7,1.06,.38,shirt);part(0,2.27,0,.51,.56,.48,skin);part(0,2.62,-.05,.59,.15,.55,'#293c3a');part(-.23,.5,step,.22,.96,.28,pants);part(.23,.5,-step,.22,.96,.28,pants);part(-.49,1.40,-step*.45,.21,.82,.29,skin);part(.49,1.4,step*.45,.21,.82,.29,skin)}
function carBody(x,z,c,dir=0){box(x,.86,z,2.55,.75,4.15,c,dir);box(x,1.6,z-.12,2.06,.88,2.3,'#4a696c',dir);box(x,.55,z,2.2,.3,3.9,'#33464e',dir);for(let i of [-1,1])for(let j of [-1,1]){box(x+i*1.3,.42,z+j*1.2,.35,.65,.78,'#263139',dir)}}
function buildDynamics(t){g=dynamicGeom=[];const avatar=state.avatar===1?['#673a2e','#e6aa6d']:state.avatar===2?['#805035','#4c956f']:['#81513b','#dfb57b'];face(player.x,0,player.z,avatar[0],avatar[1],'#284853',player.yaw,t*9*(player.moving?1:0));for(let i=0;i<pedestrians.length;i++){let p=pedestrians[i];face(p.x,0,p.z,['#633b29','#a16b4d','#55392d'][i%3],['#e4ae6d','#c8e4b8','#e5aaa2','#99b9dd'][i%4],['#364b68','#484f51'][i%2],p.heading,t*3+i)}for(let c of cars)carBody(c.x,c.z,c.color,c.axis==='x'?Math.PI/2:0);if(state.biz){for(let i=0;i<3;i++){box(35+i*2,1.23,21.5,.65,.5,.7,['#e09f57','#84ad63','#e9d3a3'][i])}}return new Float32Array(dynamicGeom)}
function perspective(fov,asp,near,far){let f=1/Math.tan(fov/2),r=new Float32Array(16);r[0]=f/asp;r[5]=f;r[10]=(far+near)/(near-far);r[11]=-1;r[14]=2*far*near/(near-far);return r}
function lookAt(eye,tgt){let z=norm([eye[0]-tgt[0],eye[1]-tgt[1],eye[2]-tgt[2]]),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1])}
function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}
function norm(a){let len=Math.hypot(...a)||1;return a.map(v=>v/len)}function cross(a,b){return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
function mul(a,b){let out=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let v=0;for(let k=0;k<4;k++)v+=a[k*4+r]*b[c*4+k];out[c*4+r]=v}return out}
let eye=[0,11,20],look=[0,1,0],VP=null,resizeStamp=0;const bind=(buff,data,kind)=>{gl.bindBuffer(gl.ARRAY_BUFFER,buff);if(data)gl.bufferData(gl.ARRAY_BUFFER,data,kind);gl.vertexAttribPointer(loc.position,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(loc.position);gl.vertexAttribPointer(loc.color,3,gl.FLOAT,false,24,12);gl.enableVertexAttribArray(loc.color)};
function render(t){const rect=$canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,1.6);let w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if($canvas.width!==w||$canvas.height!==h){$canvas.width=w;$canvas.height=h;gl.viewport(0,0,w,h)}let mobile=w/dpr<750;let dist=mobile?18:21,lo=mobile?11:13;let cameraTarget=[player.x,1.65,player.z],desired=[player.x+Math.sin(camYaw)*dist,lo,player.z+Math.cos(camYaw)*dist];eye=eye.map((v,i)=>v+(desired[i]-v)*.105);look=look.map((v,i)=>v+(cameraTarget[i]-v)*.16);VP=mul(perspective(mobile?56*rad:57*rad,w/h,.12,170),lookAt(eye,look));let night=state.time>18?clamp((state.time-18)/5,0,.73):0;let fog=[.45-night*.31,.66-night*.46,.68-night*.43];if(canvasFallback){if(t-lastFallbackPaint>.08){lastFallbackPaint=t;drawFallback(fog,w,h)}return;}gl.clearColor(...fog,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(loc.vp,false,VP);gl.uniform3fv(loc.eye,eye);gl.uniform3fv(loc.fog,fog);gl.uniform1f(loc.light,1-night*.50);bind(staticBuffer,null,gl.STATIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,staticCount);let data=buildDynamics(t);bind(dynamicBuffer,data,gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,data.length/6);}

let lastFallbackPaint=0;
function drawFallback(fog,w,h){
  let ctx=ctx2d;ctx.fillStyle='#628b8e';ctx.fillRect(0,0,w,h);
  const d=buildDynamics(performance.now()/1000),combined=[staticData,d];let triangles=[];
  for(const geo of combined){for(let i=0;i<geo.length;i+=18){let pts=[],depth=0,colorv=[];let visible=true;
    for(let j=0;j<3;j++){let k=i+j*6,x=geo[k],y=geo[k+1],z=geo[k+2];let cw=VP[3]*x+VP[7]*y+VP[11]*z+VP[15];if(cw<.14){visible=false;break}let px=(VP[0]*x+VP[4]*y+VP[8]*z+VP[12])/cw,py=(VP[1]*x+VP[5]*y+VP[9]*z+VP[13])/cw;if(Math.abs(px)>5||Math.abs(py)>5){visible=false;break}pts.push([(px+1)*w/2,(1-py)*h/2]);depth+=cw; colorv=[geo[k+3],geo[k+4],geo[k+5]]}
    if(!visible||!pts.length)continue;
    if((pts.every(p=>p[0]<0))||(pts.every(p=>p[0]>w))||(pts.every(p=>p[1]<0))||(pts.every(p=>p[1]>h)))continue;
    let area=Math.abs((pts[1][0]-pts[0][0])*(pts[2][1]-pts[0][1])-(pts[1][1]-pts[0][1])*(pts[2][0]-pts[0][0]));if(area<.18)continue;
    triangles.push([depth/3,pts,colorv]);
  }}
  triangles.sort((a,b)=>b[0]-a[0]);
  let night=state.time>18?clamp((state.time-18)/5,0,.73):0;
  let light=1-night*.50;
  for(let [depth,pts,c] of triangles){let fogFactor=clamp((depth-45)/100,0,.48);let v=c.map((n,i)=>Math.floor(255*(n*light*(1-fogFactor)+fog[i]*fogFactor)));ctx.fillStyle='rgb('+v[0]+','+v[1]+','+v[2]+')';ctx.beginPath();ctx.moveTo(pts[0][0],pts[0][1]);ctx.lineTo(pts[1][0],pts[1][1]);ctx.lineTo(pts[2][0],pts[2][1]);ctx.closePath();ctx.fill()}
}

const keys=new Set();let joystick={x:0,y:0},touchSprint=false,drag=null;
window.addEventListener('keydown',e=>{if(e.target&&['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;let k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','e','shift'].includes(k))e.preventDefault();keys.add(k);if(k==='e'&&!e.repeat)interact()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
$canvas.addEventListener('pointerdown',e=>{if(!started||modalOpen)return;drag={x:e.clientX,y:e.clientY,pointer:e.pointerId};$canvas.setPointerCapture(e.pointerId)});$canvas.addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId)return;camYaw=clamp(camYaw-(e.clientX-drag.x)*.0065,-Math.PI*10,Math.PI*10);drag.x=e.clientX;drag.y=e.clientY});$canvas.addEventListener('pointerup',()=>drag=null);
let joyPointer=null;const joy=$('joystick');joy.addEventListener('pointerdown',e=>{joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e)});joy.addEventListener('pointermove',e=>{if(joyPointer===e.pointerId)moveJoy(e)});function moveJoy(e){const r=joy.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),len=Math.max(1,Math.hypot(x,y)),scale=Math.min(len,39)/len;joystick={x:x*scale/39,y:y*scale/39};$('stick').style.transform='translate('+x*scale+'px,'+y*scale+'px)'}function endJoy(){joyPointer=null;joystick={x:0,y:0};$('stick').style.transform='translate(0px,0px)'}joy.addEventListener('pointerup',endJoy);joy.addEventListener('pointercancel',endJoy);
const tr=$('touchRun');tr.addEventListener('pointerdown',e=>{touchSprint=true;tr.setPointerCapture(e.pointerId)});tr.addEventListener('pointerup',()=>touchSprint=false);tr.addEventListener('pointercancel',()=>touchSprint=false);on('touchInteract','click',interact);
function distance(a,b){let p1=a[2]*rad,p2=b[2]*rad,dp=p2-p1,dl=(b[3]-a[3])*rad,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return Math.round(12742*Math.asin(Math.sqrt(h)))}
function nearest(){const opts=places.map(p=>({item:p,d:Math.hypot(player.x-p.x,player.z-p.z)-(Math.max(p.w,p.d)/2-1)}));for(let n of pedestrians){opts.push({item:{kind:'npc',name:n.name,x:n.x,z:n.z,role:n.role,ico:'👋'},d:Math.hypot(player.x-n.x,player.z-n.z)})}opts.sort((a,b)=>a.d-b.d);return opts[0].d<5.8?opts[0].item:null}
function collision(x,z){if(Math.abs(x)>68||Math.abs(z)>68)return true;return places.some(p=>p.kind!=='market'&&p.kind!=='bus'&&p.kind!=='kiosk'&&Math.abs(x-p.x)<p.w/2+.62&&Math.abs(z-p.z)<p.d/2+.62)}
function move(dt){let f=0,r=0;if(keys.has('w')||keys.has('z')||keys.has('arrowup'))f++;if(keys.has('s')||keys.has('arrowdown'))f--;if(keys.has('d')||keys.has('arrowright'))r++;if(keys.has('a')||keys.has('q')||keys.has('arrowleft'))r--;f-=joystick.y;r+=joystick.x;let len=Math.hypot(f,r);player.moving=len>.05;let running=keys.has('shift')||touchSprint,speed=(running?10.5:6.0)*dt;if(player.moving){f/=Math.max(1,len);r/=Math.max(1,len);let dx=(-Math.sin(camYaw)*f+Math.cos(camYaw)*r)*speed,dz=(-Math.cos(camYaw)*f-Math.sin(camYaw)*r)*speed;let nx=player.x+dx,nz=player.z+dz;if(!collision(nx,player.z))player.x=nx;if(!collision(player.x,nz))player.z=nz;player.yaw=Math.atan2(dx,dz);if(started){state.energy=clamp(state.energy-(running?.016:.006)*dt*60,0,100);state.food=clamp(state.food-.0034*dt*60,0,100)}}}
function updateActors(dt,t){for(let car of cars){car[car.axis]+=car.speed*car.dir*dt;if(car[car.axis]>61)car[car.axis]=-61;if(car[car.axis]<-61)car[car.axis]=61}pedestrians.forEach((p,i)=>{p.heading+=Math.sin(t*.29+i*1.8)*dt*.19;p.walk+=dt;p.x+=Math.sin(p.heading)*dt*.55;p.z+=Math.cos(p.heading)*dt*.55;if(p.x>58||p.x< -58||p.z>58||p.z< -58){p.heading+=Math.PI;p.x=clamp(p.x,-58,58);p.z=clamp(p.z,-58,58)}})}
function updateNear(){activeNear=nearest();const el=$('placeTag');if(activeNear&&started&&!modalOpen){el.style.opacity='1';el.childNodes[0].textContent=(activeNear.ico||'✦')+' '+activeNear.name+' ';$('interactBtn').disabled=false;$('hint').textContent='Appuie sur E pour '+(activeNear.kind==='npc'?'parler à '+activeNear.name:'entrer : '+activeNear.name)}else{el.style.opacity='0';$('interactBtn').disabled=true;$('hint').textContent='Explore le quartier, approche-toi des bâtiments ou des habitants.'}}
function updateCityUI(){$('locationLabel').textContent='📍 '+PREF[state.city][0]+' · '+REG[PREF[state.city][1]].name}
function updateHUD(){$('money').textContent=money(state.money);$('day').textContent=String(state.day).padStart(2,'0')+' / 14';let t=Math.floor(state.time*60);$('hour').textContent=String(Math.floor(t/60)%24).padStart(2,'0')+':'+String(t%60).padStart(2,'0');$('rep').textContent=Math.round(state.rep)+' / 100';$('energyBar').style.width=state.energy+'%';$('foodBar').style.width=state.food+'%';$('moodBar').style.width=state.mood+'%';$('taskGoal').textContent=state.biz?'✅ Tu possèdes un kiosque. Développe ton activité.':'🎯 Objectif : gagner 28 000 F pour ouvrir ton commerce'}
function beep(success=true){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),v=audio.createGain();o.type='sine';o.frequency.value=success?640:250;v.gain.value=.035;o.connect(v);v.connect(audio.destination);o.start();v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.14);o.stop(audio.currentTime+.15)}catch(e){}}
function toast(txt,ok=true){$('toast').textContent=txt;$('toast').classList.add('show');beep(ok);let now=++lastToast;setTimeout(()=>{if(now===lastToast)$('toast').classList.remove('show')},3000)}
function save(){try{localStorage.setItem('togo_life_3d_v1',JSON.stringify(state))}catch(e){}}
function open(id){modalOpen=true;$(id).classList.add('show');keys.clear()}function close(id){$(id).classList.remove('show');modalOpen=Array.from(document.querySelectorAll('.modal')).some(m=>m.classList.contains('show'))}
function selection(kind,title,desc,options){$('actionTag').textContent=kind;$('actionTitle').textContent=title;$('actionDescription').textContent=desc;const el=$('actionChoices');el.innerHTML='';for(let op of options){let b=document.createElement('button');b.className='choice';b.innerHTML='<span>'+op.name+'</span><b>'+op.price+'</b>';b.disabled=op.disabled||false;b.addEventListener('click',()=>{if(op.run()){close('actionModal');updateHUD();save()}});el.appendChild(b)}open('actionModal')}
function buy(cost,fn,success){if(state.money<cost){toast('Pas assez d’argent : il manque '+money(cost-state.money),false);return false}state.money-=cost;fn?.();toast(success||'Transaction effectuée');return true}
function work(pay,energy,need=0){if(state.rep<need){toast('Réputation requise : '+need,false);return false}if(state.energy<energy||state.food<12){toast('Tu es épuisé ou affamé : mange ou dors.',false);return false}state.money+=Math.round(pay*REG[PREF[state.city][1]].factor/100)*100;state.energy-=energy;state.food=clamp(state.food-10,0,100);state.rep=clamp(state.rep+3,0,100);state.experience++;toast('Mission réussie ! +'+money(pay*REG[PREF[state.city][1]].factor));return true}
function optionsFor(p){let role=p.kind,lev=REG[PREF[state.city][1]].factor;const cost=(n)=>Math.round(n*lev/100)*100;
switch(role){
case 'home':return ['TON LOGEMENT','Maison du quartier','Ici, tu peux récupérer ton énergie et terminer ta journée.',[
{name:'🛌 Dormir jusqu’au lendemain',price:'Gratuit',run:()=>{nextDay();return true}},
{name:'🍚 Préparer un repas',price:'-1 400 F',run:()=>buy(1400,()=>{state.food=clamp(state.food+40,0,100);state.mood=clamp(state.mood+8,0,100)},'Tu as bien mangé !')}]];
case 'market':return ['COMMERCE LOCAL','Marché vivant','Achète des produits puis revends-les. Les marges sont simulées et varient selon les régions.',[
{name:'📦 Acheter un lot de marchandises',price:'-'+money(cost(3600)),run:()=>buy(cost(3600),()=>state.stock++,'Stock +1 lot')},
{name:'🛍️ Revendre un lot',price:'+'+money(cost(5050)),disabled:state.stock<1,run:()=>{if(!state.stock)return false;state.stock--;state.money+=cost(5050);state.rep=clamp(state.rep+4,0,100);toast('Belle vente ! +'+money(cost(5050)));return true}},
{name:'🧺 Travailler comme vendeur',price:'+'+money(cost(3600)),run:()=>work(3600,13)}]];
case 'tech':return ['OPPORTUNITÉS NUMÉRIQUES','Cyber & Studio IA','Réalise des prestations numériques, développe ton réseau et ton niveau professionnel.',[
{name:'💻 Mission de saisie informatique',price:'+'+money(cost(4500)),run:()=>work(4500,17)},
{name:'🤖 Prototype IA pour un client',price:'+'+money(cost(9000)),disabled:state.rep<22,run:()=>work(9000,25,22)},
{name:'🧠 Atelier de formation digitale',price:'-2 000 F',run:()=>buy(2000,()=>{state.rep=clamp(state.rep+9,0,100);state.mood=clamp(state.mood+3,0,100)},'Compétence acquise : +9 réputation')}]];
case 'school':return ['FORMATION','Centre de formation','Apprendre augmente ta réputation. Les nouvelles compétences ouvrent de meilleures missions.',[
{name:'🎓 Formation pratique',price:'-3 000 F',run:()=>buy(3000,()=>{state.rep=clamp(state.rep+14,0,100);state.experience++},'Tu progresses ! +14 réputation')},
{name:'📝 Animer un cours',price:'+'+money(cost(3100)),disabled:state.rep<20,run:()=>work(3100,11,20)}]];
case 'bank':return ['FINANCE','Banque & Mobile Money','Le crédit aide au démarrage mais crée une dette. Aucun argent réel ne circule.',[
{name:'💳 Microcrédit : 15 000 F',price:'Dette +18 000 F',disabled:state.loans>=1,run:()=>{if(state.loans>=1)return false;state.loans++;state.money+=15000;state.debt+=18000;toast('Crédit accordé. Pense à rembourser.');return true}},
{name:'💸 Rembourser une partie de la dette',price:'-5 000 F',disabled:state.debt<=0||state.money<5000,run:()=>buy(5000,()=>state.debt=Math.max(0,state.debt-5000),'Dette réduite de 5 000 F')}]];
case 'bus':return ['GARE ROUTIÈRE','Voyage à travers le Togo','Tu peux te déplacer vers l’une des 40 préfectures répertoriées.',[
{name:'🗺️ Ouvrir la carte nationale',price:'40 destinations',run:()=>{close('actionModal');openMap();return true}},
{name:'🛵 Livraison dans le quartier',price:'+'+money(cost(5200)),run:()=>work(5200,21)}]];
case 'kiosk':return ['ENTREPRENEURIAT','Mon commerce','Investis dans un kiosque et gagne un revenu passif fictif de 3 200 F par jour.',[
{name:state.biz?'✅ Tu es déjà propriétaire':'🏪 Ouvrir mon kiosque',price:'-28 000 F',disabled:state.biz,run:()=>{if(state.biz)return false;return buy(28000,()=>{state.biz=true;state.rep=clamp(state.rep+15,0,100);createTown()},'Tu es devenu entrepreneur !')}},
{name:'📣 Faire de la publicité',price:'-2 500 F',disabled:!state.biz,run:()=>buy(2500,()=>state.rep=clamp(state.rep+10,0,100),'Ta publicité attire des clients.')}]];
case 'npc':return ['RENCONTRE','Parler à '+p.name,`${p.name} travaille comme ${p.role} à ${PREF[state.city][0]}. Chaque personne peut t’aider à découvrir des opportunités.`,[
{name:'👋 Discuter de la vie locale',price:'+4 réputation',run:()=>{state.rep=clamp(state.rep+4,0,100);state.mood=clamp(state.mood+6,0,100);toast(p.name+' : « Courage ! Ici, on construit sa réussite. »');return true}},
{name:'🤝 Proposer une aide',price:'+'+money(cost(1800)),run:()=>work(1800,10)}]];
}
return ['DÉCOUVERTE',p.name,'Le quartier est vivant.',[{name:'Continuer',price:'',run:()=>true}]]}
function interact(){if(!started||modalOpen||state.done)return;let p=activeNear;if(!p){toast('Approche-toi d’un commerce, d’une maison ou d’un habitant.',false);return}let [tag,title,desc,ops]=optionsFor(p);selection(tag,title,desc,ops)}
function nextDay(){if(state.done)return;state.day++;state.time=8;state.energy=clamp(state.energy+63,0,100);state.food=clamp(state.food-20,0,100);state.mood=clamp(state.mood+10,0,100);let passive=state.biz?3200:0;state.money+=passive;if(state.day===8||state.day===15){let rent=12000*Math.ceil(REG[PREF[state.city][1]].factor*10)/10;if(state.money>=rent){state.money-=rent;state.rentPaid++}else{state.debt+=rent-state.money;state.money=0;state.mood=clamp(state.mood-23,0,100)}}if(state.day>14){finish();return}let events=[['⚡ Coupure de courant',()=>{state.energy=clamp(state.energy-8,0,100)},'La panne réduit ton énergie.'],['🌦️ Pluie tropicale',()=>{state.mood=clamp(state.mood-3,0,100)},'Les déplacements sont plus pénibles.'],['🎉 Festival de quartier',()=>{state.mood=clamp(state.mood+12,0,100);state.rep=clamp(state.rep+2,0,100)},'Tu rencontres de nouvelles personnes.'],['📦 Bonne affaire au marché',()=>{state.money+=1000},'Bonus de 1 000 F pour les habitants.']];let ev=events[(state.day+state.city)%events.length];ev[1]();toast('Jour '+state.day+' · '+ev[0]+' · '+ev[2]);updateHUD();save()}
function finish(){state.done=true;close('actionModal');$('endTitle').textContent=state.biz?'🏆 Te voilà entrepreneur !':'🌅 14 jours d’aventure';$('endText').textContent=state.name+' termine à '+PREF[state.city][0]+' avec '+money(state.money)+' en poche, '+Math.round(state.rep)+' points de réputation, '+money(state.debt)+' de dettes et '+(state.biz?'un kiosque ouvert.':'aucun commerce.');open('endModal');save()}
function openMap(){selectedCity=state.city;populateMap();open('mapModal')}
function populateMap(){const regSel=$('regionSelect'),prefSel=$('prefSelect');if(!regSel.options.length)for(let key of ['M','P','C','K','S'])regSel.add(new Option(REG[key].name,key));let r=PREF[selectedCity][1];regSel.value=r;prefSel.innerHTML='';PREF.forEach((p,i)=>{if(p[1]===r)prefSel.add(new Option(p[0],i))});prefSel.value=String(selectedCity);for(let path of document.querySelectorAll('#countryMap path'))path.classList.toggle('active',path.dataset.region===r);let dots=$('mapDots');dots.innerHTML='';PREF.forEach((p,i)=>{if(p[1]!==r)return;let el=document.createElementNS('http://www.w3.org/2000/svg','circle');el.setAttribute('cx',40+(p[3]+.3)*170);el.setAttribute('cy',30+(11.25-p[2])*123);el.setAttribute('r',selectedCity===i?'7':'4');el.setAttribute('fill',selectedCity===i?'#ffe39e':'#153943');el.setAttribute('stroke','#f8edd7');el.setAttribute('stroke-width','2');el.style.cursor='pointer';el.addEventListener('click',()=>{selectedCity=i;populateMap()});dots.appendChild(el)});let km=distance(PREF[state.city],PREF[selectedCity]);let fare=Math.ceil((700+km*27)/100)*100;$('destinationDesc').innerHTML='<strong>'+PREF[selectedCity][0]+'</strong><br>'+REG[r].feature+'<br>Distance directe : '+km+' km<br>Transport simulé : '+money(fare);let same=state.city===selectedCity;$('travelBtn').textContent=same?'📍 Tu es déjà ici':'🚌 Voyager · '+money(fare);$('travelBtn').disabled=same||state.money<fare||state.energy<10;$('travelBtn').dataset.fare=fare}
function travel(){let fare=+($('travelBtn').dataset.fare||0);if(state.money<fare||state.city===selectedCity||state.energy<10)return;state.money-=fare;state.energy-=10;state.city=selectedCity;player.x=0;player.z=11;camYaw=-.17;createTown();close('mapModal');updateHUD();save();toast('Bienvenue à '+PREF[state.city][0]+' ! Voyage : -'+money(fare))}
on('regionSelect','change',e=>{selectedCity=PREF.findIndex(p=>p[1]===e.target.value);populateMap()});on('prefSelect','change',e=>{selectedCity=Number(e.target.value);populateMap()});for(let path of document.querySelectorAll('#countryMap path'))path.addEventListener('click',()=>{selectedCity=PREF.findIndex(p=>p[1]===path.dataset.region);populateMap()});on('travelBtn','click',travel);
on('mapBtn','click',openMap);on('closeMap','click',()=>close('mapModal'));on('closeAction','click',()=>close('actionModal'));on('interactBtn','click',interact);on('sleepBtn','click',()=>{if(!started||modalOpen)return;nextDay()});on('audioBtn','click',()=>{sound=!sound;$('audioBtn').textContent=sound?'♫':'♪';if(sound)beep()});on('replayBtn','click',()=>{state=mkState();selectedCity=24;player.x=1.5;player.z=11;camYaw=-.17;started=false;createTown();$('endModal').classList.remove('show');open('startModal');updateHUD()});
for(let btn of document.querySelectorAll('[data-avatar]'))btn.addEventListener('click',()=>{selectedAvatar=Number(btn.dataset.avatar);document.querySelectorAll('[data-avatar]').forEach(b=>b.classList.toggle('selected',b===btn))});
let sc=$('startCity');let startOptions=PREF.map((_,i)=>i);for(let i of startOptions)sc.add(new Option(PREF[i][0]+' · '+REG[PREF[i][1]].name,i));sc.value='24';
on('startBtn','click',()=>{state=mkState();state.name=$('nameInput').value.trim().slice(0,20)||'Kossi';state.avatar=selectedAvatar;state.city=Number(sc.value);started=true;player.x=1.5;player.z=11;camYaw=-.17;createTown();close('startModal');updateHUD();save();toast('Bienvenue à '+PREF[state.city][0]+', '+state.name+' !')});
function restore(){try{let x=JSON.parse(localStorage.getItem('togo_life_3d_v1')||'null');if(x&&typeof x.city==='number'&&PREF[x.city]&&!x.done){state={...mkState(),...x};$('nameInput').value=state.name;sc.value=String(state.city);selectedAvatar=state.avatar;for(let b of document.querySelectorAll('[data-avatar]'))b.classList.toggle('selected',Number(b.dataset.avatar)===selectedAvatar);$('startBtn').textContent='REPRENDRE MON AVENTURE →';$('startBtn').onclick=()=>{started=true;createTown();close('startModal');updateHUD();toast('Bon retour à '+PREF[state.city][0]+' !')};}}catch(e){}}
let prev=0,acc=0,uiTimer=0;function frame(ms){let t=ms/1000,dt=Math.min(.06,(ms-prev)/1000||.016);prev=ms;if(started&&!modalOpen&&!state.done){move(dt);state.time=Math.min(21.99,state.time+dt*.075);updateActors(dt,t);if(state.time>=21.99){nextDay()}}else updateActors(dt*.35,t);render(t);uiTimer+=dt;if(uiTimer>.15){uiTimer=0;updateNear();updateHUD()}requestAnimationFrame(frame)}
createTown();updateHUD();restore();requestAnimationFrame(frame);
window.TOGO_LIFE_DEBUG={getState:()=>({...state}),getPlayer:()=>({...player}),getPrefectures:()=>PREF.length,teleportForTest:(x,z)=>{player.x=x;player.z=z;updateNear();},goTo:(i)=>{state.city=i;createTown();updateCityUI()},simulateDay:()=>{nextDay();updateHUD()}};
})();

