import {mkdir,cp,readFile,writeFile,readdir} from 'node:fs/promises';import path from 'node:path';
const root=path.resolve(new URL('..',import.meta.url).pathname),out=path.join(root,'dist');await mkdir(out,{recursive:true});
for(const name of ['index.html','life.css','src','vendor','assets','legacy.html','style.css','game.js'])await cp(path.join(root,name),path.join(out,name),{recursive:true});
// Validate all relative ES imports in production files. No package installation required.
let bytes=0,files=0;async function inspect(dir){for(const item of await readdir(dir,{withFileTypes:true})){const full=path.join(dir,item.name);if(item.isDirectory())await inspect(full);else{const data=await readFile(full);bytes+=data.length;files++;if(full.endsWith('.js'))for(const match of data.toString().matchAll(/(?:from\s*|import\s*)['"]([^'"]+)['"]/g)){if(match[1].startsWith('.'))await readFile(path.resolve(path.dirname(full),match[1]));}}}}
await inspect(out);const report={files,bytes,method:'Static ES module build; validated local import paths; no Vite/npm download',entry:'dist/index.html'};await mkdir(path.join(root,'artifacts'),{recursive:true});await writeFile(path.join(root,'artifacts/build.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
// Offline monofile uses import maps and embedded original glTF; prototype stays preserved.
const modules={};async function collect(dir){for(const e of await readdir(dir,{withFileTypes:true})){const file=path.join(dir,e.name);if(e.isDirectory())await collect(file);else if(e.name.endsWith('.js')&&!file.includes('/exporters/')&&!file.endsWith('TextureUtils.js')){let code=await readFile(file,'utf8');code=code.replace(/(from\s*|import\s*)['"]([^'"]+)['"]/g,(full,prefix,spec)=>spec.startsWith('.')?prefix+JSON.stringify('tl:'+path.relative(root,path.resolve(path.dirname(file),spec)).split(path.sep).join('/')):full);modules['tl:'+path.relative(root,file).split(path.sep).join('/')]='data:text/javascript;base64,'+Buffer.from(code).toString('base64');}}}
await collect(path.join(root,'src'));await collect(path.join(root,'vendor'));let html=await readFile(path.join(root,'index.html'),'utf8');const css=await readFile(path.join(root,'life.css'),'utf8'),gltf=await readFile(path.join(root,'assets/avatar.gltf'));html=html.replace('<link rel="stylesheet" href="life.css">','<style>'+css+'</style>');html=html.replace('<script type="module" src="src/main.js"></script>','<script>globalThis.__TOGO_AVATAR_URL__='+JSON.stringify('data:model/gltf+json;base64,'+gltf.toString('base64'))+';</script><script type="importmap">'+JSON.stringify({imports:modules})+'</script><script type="module">import "tl:src/main.js";</script>');await writeFile(path.join(root,'TOGO_LIFE_MONTAGNE.html'),html);await writeFile(path.join(out,'TOGO_LIFE_MONTAGNE.html'),html);console.log('Offline monofile bytes: '+Buffer.byteLength(html));
