plugins {
    id 'com.android.application'
}

android {
    namespace 'com.live228.clash'
    compileSdk 35

    defaultConfig {
        applicationId "com.live228.clash"
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName "0.4.0"
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                'META-INF/DEPENDENCIES',
                'META-INF/LICENSE',
                'META-INF/LICENSE.txt',
                'META-INF/NOTICE',
                'META-INF/NOTICE.txt'
            ]
        }
    }
}

dependencies {
    implementation 'com.github.jwdeveloper.TikTok-Live-Java:Client:1.11.0-Release'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
}
